Add ability to get raw controller analog value
multitheftauto/mtasa-blue pull request #1165
Opened 2019-11-24 22:53 UTC by Addlibs

Adds a bool parameter to getAnalogControlValue and getPedAnalogControlValue to poll for raw controller input for a given control value, ignoring scripted overrides, control toggles, etc. Allows scripts to do things like mirroring analog input for accelerate onto brake_reverse. This will ignore non-analog inputs for the control, in other words, it'll return 0 for "accelerate" when pressing W on the keyboard unless you're actually pressing on a controller trigger (or whichever axis is bound to "accelerate")

2020-01-14 20:30 UTC, qaisjp approved these changes
Thanks for the pull request! Your proposal makes sense. I've left some comments.

2020-01-14 20:30 UTC, qaisjp commented on Client/mods/deathmatch/logic/CClientPed.h
> +    CControllerState                         m_rawControllerState;
A future programmer might be confused about the difference between `m_currentControllerState` and `m_rawControllerState` (specifically, what `current` has that `raw` doesn't have). I would suggest you include comments here that explain this.

2020-01-14 20:30 UTC, qaisjp commented on Client/mods/deathmatch/logic/CClientPad.cpp
>          // Do we have a script override?
This comment should be updated to say something like:

```suggestion
        // If we are not ignoring overrides and have a script override
```

2020-01-14 20:30 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +            cs = Ped.m_rawControllerState;
If `bRawInput` is `true` then line 1668 is useless. I would suggest this:

```suggestion
            cs = Ped.m_rawControllerState;
        else
            Ped.GetControllerState(cs);
```

2020-01-14 20:30 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
>          Ped.GetControllerState(cs);
```suggestion
```

(see below)

2020-01-14 20:30 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        cs = pLocalPlayer->m_rawControllerState;
```suggestion
        cs = pLocalPlayer->m_rawControllerState;
    else
        pLocalPlayer->GetControllerState(cs);
```

2020-01-14 20:30 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
>      pLocalPlayer->GetControllerState(cs);
```suggestion
```

2020-01-14 20:31 UTC, qaisjp requested changes
Whoops, meant to _request changes_.

2020-01-14 20:55 UTC, LosFaul commented
just to keep things on track
this might be connected to this stuff here:
https://github.com/multitheftauto/mtasa-blue/issues/567

2020-01-15 22:47 UTC, qaisjp approved these changes
lgtm, thank you! :shipit:

2020-01-15 22:50 UTC, merged