Added reloadacl command for server console (#9626)
multitheftauto/mtasa-blue pull request #131
Opened 2017-05-11 15:23 UTC by Timic3

This simple pull request adds reloadacl server command. See [#9626](https://bugs.multitheftauto.com/view.php?id=9626)

2017-05-13 18:10 UTC, qaisjp commented
Hey @Timic3! Thank you for your pull request.

The code looks great (although I am concerned about whether only administrators can run the command...), but I think it would be best to actually add this command to [the `admin` resource](https://github.com/multitheftauto/mtasa-resources/tree/master/%5Badmin%5D/admin).

Would you like to work on that? I'm happy to assign [mantis 9626](https://bugs.multitheftauto.com/view.php?id=9626) to you!

2017-05-14 12:18 UTC, Timic3 commented
Hi @qaisjp, the main reason I added this is because when people start the server for the first time, they don't edit the ACL (at least I don't) and to add themselves to Admin ACL group, they'd need to restart the server. If this would be added to the admin resource, will console still be able to use /reloadacl? And if people didn't download the resources package, they wouldn't be able to use this command.

I think players cannot use this command (correct me if I am wrong), because I did this only for server console.

2017-05-14 14:45 UTC, Dezash commented
Console has Admin permissions by default so they would be able to use it.

2017-05-14 14:52 UTC, Timic3 commented
Still, that doesn't eliminate the problem where they haven't downloaded the resources.

2017-05-14 15:06 UTC, 4O4 commented
I agree with @Timic3. ACL is built-in MTA feature, which is also tightly coupled with the xml config file. IMO there should also be a built-in command for such trivial task as reloading this config, which eliminates the need to install / code by hand any additional resources.

2017-05-14 16:57 UTC, qaisjp commented
These are reasonable arguments. 

Also, to answer your question, the console can execute normal `addCommandHandler` commands.

Thanks again for your pull request!

2017-05-14 16:58 UTC, qaisjp approved these changes

2017-05-14 17:16 UTC, ccw808 commented
I think the command needs to block anyone from using it. See the example here: https://github.com/multitheftauto/mtasa-blue/pull/131/files#diff-6f18ab7274d425bb8e56b0be74d40aeeL1701

2017-05-14 17:19 UTC, qaisjp commented
I'm not sure... the `start` command doesn't seem to have the block. [See here.](https://github.com/Timic3/mtasa-blue/blob/7bf2d93793053bbdf8927ed1fb37ee1c6a161d83/Server/mods/deathmatch/logic/CConsoleCommands.cpp#L53)

2017-05-14 17:22 UTC, ccw808 commented
start command is protected in acl.xml

2017-05-14 17:23 UTC, qaisjp requested changes

2017-05-14 17:23 UTC, qaisjp commented on Server/mods/deathmatch/logic/CConsoleCommands.cpp
> +{
Needs to make sure only console / people with rights can use this command. [See this example.](https://github.com/Timic3/mtasa-blue/blob/7bf2d93793053bbdf8927ed1fb37ee1c6a161d83/Server/mods/deathmatch/logic/CConsoleCommands.cpp#L1699)

2017-05-14 19:53 UTC, Timic3 commented
Okay, I added that check you requested - I also added the command to ACL, so only users in Admin group can execute it.

2017-05-14 19:55 UTC, qaisjp approved these changes

2017-05-15 02:06 UTC, ccw808 approved these changes

2017-08-02 13:27 UTC, Timic3 commented
I tested everything (reloading ACL with no rights, with rights & server console) and as far as I know, everything works. I think this can be merged, but if you want to test it again just to be sure, go ahead.

2018-02-15 09:48 UTC, merged