Allow to use peds and vehicles as a camera target
multitheftauto/mtasa-blue pull request #1398
Opened 2020-04-21 19:29 UTC by TheNormalnij

Allow to use peds and vehicles as a camera target in setCameraTarget function.
- [x] Clientside
- [ ] Serverside

2020-04-21 20:36 UTC, Citizen01 requested changes
Thanks for the PR. However, if it was this easy to add support for new element types as camera target, what blocks us to support all entity types ?
(I think there might be a valid reason for it to only support players in the 1st place but I don't know what it is then)

2020-04-21 20:36 UTC, Citizen01 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
>          // Make sure our target is a player element
Useless comment now.

2020-04-21 20:36 UTC, Citizen01 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    return true;
No, don't brake it and keep it to `false` there.

2020-04-21 20:47 UTC, TheNormalnij commented
I tried with objects but it didn't work.
Now i have bug with getCameraTarget. It need to be fixed.

2020-04-23 20:08 UTC, TheNormalnij commented
setCameraViewMode works only with 1-4 modes. Maybe it can be fixed later.

2020-04-26 16:34 UTC, sbx320 approved these changes
We'd need to lock this behaviour behind a min MTA version check, as otherwise this will cause issues with new vs old clients. Aside from that it looks good.  

So **before merging** (whoever does it): Please add a version check with an applicable version

2020-04-27 21:52 UTC, TheNormalnij commented
@sbx320 do you mean MinClientReqCheck and MinServerReqCheck or pBitStream->Version?

2020-10-09 19:44 UTC, Citizen01 approved these changes

2020-10-09 19:47 UTC, Citizen01 commented
Requires a min MTA version check still.
Do not merge yet.

2020-10-10 14:00 UTC, TheNormalnij commented
Added

2020-10-17 02:41 UTC, merged

2020-10-17 03:23 UTC, qaisjp commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +                if (pPlayer->GetBitStreamVersion() >= 0x5E)
Wrong bitstream you need to find the latest one