Refactor all post 1.5.7 funcs to use the new parser
multitheftauto/mtasa-blue pull request #1454
Opened 2020-05-22 05:14 UTC by Pirulax

I've talked with Qais, and he said it would be a big help to refactor all these new functions.

Also, the *not done list*:

- dxDrawPrimitive3D  / dxDrawMaterialPrimitive3D - hard to read table structure. Its pretty specific, so i wont bother trying it with the new parser, will just add a big overhead.
- engineGetModelTextures  - performance issue(returning std::unordred_map, with possibly a lot of strings: a lot of HEAP allocs, which would kill the performance. I suggest to implement `std::vector<std::pair<const char*, Type*>>, or with string_view.`
- SetColShapeSize - argument types depends on colshape type - impossible to do with the new parser(well, not impossible, but im not sure what would be the best way, ill leave it up to you)
- GetColPolygonPoints - modifying it would kill the performance because of std::vector heap allocation on return
- [Add possibility of modifying dynamic objects behavior  (#784)](https://github.com/multitheftauto/mtasa-blue/commit/)

2020-05-22 05:14 UTC, Pirulax commented
I know there are a few messed up commits. Im sorry.

2020-05-22 05:57 UTC, Pirulax commented
Seems like we either move 
`{"resetBlurLevel", CLuaDefs::ArgumentParser<CLuaFunctionDefs::ResetBlurLevel>},`  to `LuaDefs.World` or we make `CLuaDefs::ArgumentParser` functions public or we do a `private CLuaDefs` to `CLuaManager` which would be dumb.

2020-05-22 06:06 UTC, Pirulax commented
I also refactored the non OOP functions in ColShapeDefs to return numbers instead of vector(s)

2020-05-22 10:18 UTC, StrixG commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        throw std::invalid_argument("ColShape must be Polygon");
```suggestion
        throw std::invalid_argument("ColShape must be a polygon");
```

2020-05-22 10:18 UTC, StrixG commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        std::invalid_argument("Invalid points index");
```suggestion
        std::invalid_argument("Invalid point index");
```

2020-05-22 10:18 UTC, StrixG commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        throw std::invalid_argument("ColShape must be Polygon");
```suggestion
        throw std::invalid_argument("ColShape must be a polygon");
```

2020-05-22 10:18 UTC, StrixG commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        throw std::invalid_argument("ColShape must be Polygon");
```suggestion
        throw std::invalid_argument("ColShape must be a polygon");
```

2020-05-22 10:18 UTC, StrixG commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +    throw std::invalid_argument("Invalid points index");
```suggestion
    throw std::invalid_argument("Invalid point index");
```

2020-05-22 19:11 UTC, Pirulax commented
There you go.
The build doesnt compile. 
I need someone who could answer my previous question,

> Seems like we either move
> {"resetBlurLevel", CLuaDefs::ArgumentParser<CLuaFunctionDefs::ResetBlurLevel>}, to LuaDefs.World(Somehow, because CLuaManager loads all the defs from where) or we make CLuaDefs::ArgumentParser functions public or we do a private CLuaDefs to CLuaManager which would be dumb.

also, `DxDrawWiredSphere` has `const SColorARGB color`, how should we deal with that?

2020-05-23 19:45 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        pointIndex--; // lua starts at 1, we at 0
```suggestion
    pointIndex--; // lua starts at 1, we at 0
```

Should there be an extra indent here?

2020-05-24 00:11 UTC, qaisjp requested changes
Annotated each suggested change with the name of the commit it should be melded into, so try and batch matching names if you accept the changes.

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
> -    uint             uiIterations = 1;
Defaults are lost.

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
> +        throw std::invalid_argument("argument 'iterations' must be between 1 and 4");
```suggestion
        throw std::invalid_argument("Iterations must be between 1 and 4");
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +        throw std::invalid_argument("hour on must be between 0 and 24");
EngineSetModelVisibleTime

```suggestion
        throw std::invalid_argument("hourOn must be between 0 and 24");
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +        throw std::invalid_argument("hour on must be between 0 and 24");
EngineSetModelVisibleTime

```suggestion
        throw std::invalid_argument("hourOff must be between 0 and 24");
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +    const unsigned short modelID = std::holds_alternative<std::string>(variantModelID) ? CModelNames::ResolveModelID(std::get<std::string>(variantModelID)) : std::get<unsigned int>(variantModelID);
EngineSetModelVisibleTime

```suggestion
    unsigned short modelID;
    if (std::holds_alternative<std::string>(variantModelID))
        modelID = CModelNames::ResolveModelID(std::get<std::string>(variantModelID));
    else
        modelID = std::get<unsigned int>(variantModelID);
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +        throw std::invalid_argument(SString("Can't find model id %u", modelID));
Do we want to use `std::format` instead? Needs second opinion.

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +    const unsigned short modelID = std::holds_alternative<std::string>(variantModelID) ? CModelNames::ResolveModelID(std::get<std::string>(variantModelID)) : std::get<unsigned int>(variantModelID);
EngineGetModelVisibleTime

```suggestion
    unsigned short modelID;
    if (std::holds_alternative<std::string>(variantModelID))
        modelID = CModelNames::ResolveModelID(std::get<std::string>(variantModelID));
    else
        modelID = std::get<unsigned int>(variantModelID);

```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
> +    static bool EngineSetModelVisibleTime(lua_State* const luaVM, const std::variant<std::string, unsigned int> variantModelID, char hourOn, char hourOff);
EngineGetModelVisibleTime. This shouldn't be here

```suggestion
    static bool EngineSetModelVisibleTime(const std::variant<std::string, unsigned int> variantModelID, char hourOn, char hourOff);
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.h
> +    static inline  ID3DXFont* CStaticFunctionDefinitions::ResolveD3DXFont(eFontType fontType, CClientDxFont* pDxFontElement)
DxGetTextSize

```suggestion
    static inline ID3DXFont* CStaticFunctionDefinitions::ResolveD3DXFont(eFontType fontType, CClientDxFont* pDxFontElement)
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
> +            optFont.has_value() ? std::move(optFont.value()) : FONT_DEFAULT,
DxGetTextSize

Not sure if this will work, but might be preferable

```suggestion
            std::move(optFont.value_or(FONT_DEFAULT)),
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
> +        scale.fY = optScaleY.has_value() ? optScaleY.value() : scale.fX;
DxGetTextSize
```suggestion
        scale.fY = optScaleY.value_or(scale.fX);
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
> +        optColorCoded.value_or(false)
DxGetTextSize

```suggestion
        optColorCoded.value_or(false),
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.h
> +        std::variant<CClientDxFont*, eFontType> font, // is optional, so we can call it from DxGetTextSize with a std::nullopt, and we just grab the FONT_DEFAULT.
DxGetTextSize
```suggestion
        // This is a variant for use by DxGetTextSize
        std::variant<CClientDxFont*, eFontType> font,
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +        throw std::invalid_argument(SString("Invalid model id %u", modelID));
- Old code: just returns false
- New code: error

I think this should be a warning. Needs second opinion.

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +    const unsigned short modelID = std::holds_alternative<std::string>(variantModelID) ? CModelNames::ResolveModelID(std::get<std::string>(variantModelID)) : std::get<unsigned int>(variantModelID);
EngineResetModelLODDistance

```suggestion
    unsigned short modelID;
    if (std::holds_alternative<std::string>(variantModelID))
        modelID = CModelNames::ResolveModelID(std::get<std::string>(variantModelID));
    else
        modelID = std::get<unsigned int>(variantModelID);
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +    //Make sure we're dealing with a valid LOD distance, and not setting the same LOD distance
EngineResetModelLODDistance
```suggestion
    // Make sure we're dealing with a valid LOD distance, and not setting the same LOD distance
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +    if (originalDistance == 0.0f || originalDistance == modelInfo->GetLODDistance())
Does the new parser throw an error if a signed number is given to an unsigned type?

2020-05-24 00:11 UTC, qaisjp commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +            throw std::invalid_argument("You can only pass false to turn the debugger off, or a level(0 - 3)");
SetPlayerScriptDebugLevel

```suggestion
            throw std::invalid_argument("You can only pass false to hide the debug window or a level (0-3)");
```

Tbh this false thing is weird - should get rid of the false thing in a separate PR.

2020-05-24 00:11 UTC, qaisjp commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.h
> +
SetPlayerScriptDebugLevel
```suggestion
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
> +        throw std::invalid_argument("Style can only be between 4 and 16");
Before: silent failure
After: error

Should this be a warning?

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/lua/CLuaManager.cpp
> +#include "../logic/luadefs/CLuaDefs.h"
CLuaColshapeDefs

```suggestion
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +int CLuaColShapeDefs::GetColShapeType(lua_State* luaVM)
Has this and some other functions been moved around or something? Please undo

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        throw std::invalid_argument("Can't remove the last 3 points");
Should be warning, not error

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        throw std::invalid_argument("Invalid point index");
Should be warning, not error

2020-05-24 00:11 UTC, qaisjp commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> -}
Needs fixup ?

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +        throw std::invalid_argument("hour off must be between 0 and 24");
This commit needs a fixup

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +        pointIndex--;            // Lua indexing starts at 1, we start at 0.
colshape
```suggestion
        // Lua indexing starts at 1, we start at 0
        pointIndex--;
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +    pointIndex--;            // lua starts at 1, we at 0
colshape
```suggestion
    // Lua indexing starts at 1, we start at 0.
    pointIndex--;
```

2020-05-24 00:11 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +    pointIndex--;            // lua starts at 1, we at 0
colshape
```suggestion
    // Lua indexing starts at 1, we start at 0.
    pointIndex--;
```

2020-05-24 16:44 UTC, Pirulax commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +    const unsigned short modelID = std::holds_alternative<std::string>(variantModelID) ? CModelNames::ResolveModelID(std::get<std::string>(variantModelID)) : std::get<unsigned int>(variantModelID);
I'll just overload the `CModelNames::ResolveModelID` function to take an `variant` as an argument.

2020-05-24 16:45 UTC, Pirulax commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.h
> +    static bool EngineSetModelVisibleTime(lua_State* const luaVM, const std::variant<std::string, unsigned int> variantModelID, char hourOn, char hourOff);
I think ive squashed them when rearranging the commits yesterday.

2020-05-24 19:11 UTC, Pirulax commented
https://github.com/multitheftauto/mtasa-blue/pull/1454#discussion_r429587512
@qaisjp 
I cant comment on the issue, but no, its I've deleted the old function, and added the new, one liner(CStaticFDs was always returning true, so there was no need for that check)

2020-05-24 19:13 UTC, Pirulax commented
Its still not compiling because we need to resolve the `dxDrawWiredSphere` argument `SColorARGB`. What should we do with that? Should I revert that commit? Or we implement SColorARGB?

2020-05-24 19:14 UTC, qaisjp commented
Implement _SColor_ in a separate PR the same way the old parser works.

2020-05-26 05:14 UTC, Pirulax commented
alright, idk what ive fucked up.
i did rebase, and everything, but these non-sense commits are still here
please go ahead, and fix them, I dont have the nerves.

2020-05-26 05:24 UTC, Pirulax commented
Alright, alright, there we go.
I did it this time.

2020-05-26 20:12 UTC, qaisjp commented
Also, I didn't mention it earlier when I worked with you on the rebase since I didn't want to spend too much time with you watching rewords, but you need to reword every commit to be more clear.

"Refactor X" is not clear enough - someone must be able to read the commit message and know exactly what change was made.

It should be "Refactor X to use new Lua arg parser", and if there are other changes, include those in the commit descriptions.

2020-05-26 23:51 UTC, Pirulax commented
Okay, no problem.
Ill do it tomorrow.

2020-05-29 04:11 UTC, Pirulax commented
#6ed8668, #629e84e

2020-05-29 04:18 UTC, Pirulax commented
Actually i could just go to another branch, squash merge the whole branch, and stage-commit changes line-by-line, so every commit would be perfect.

If theres a way to merge without having a 'merged branch..' commit?

2020-05-29 04:21 UTC, Pirulax commented
Im not quite sure whats up with the new parser?
Please take a look at the build logs

2020-06-03 04:29 UTC, closed without merging

2020-06-03 04:29 UTC, Pirulax commented
All refactors have been moved to other PRs.