Fix #1456  Getting nil from account data has "nil" result
multitheftauto/mtasa-blue pull request #1457
Opened 2020-05-23 05:26 UTC by Pirulax

Fixes #1456

2020-05-23 16:30 UTC, qaisjp commented on Server/mods/deathmatch/logic/CAccountManager.cpp
> +        default:
```suggestion

        default:
```

2020-05-23 18:52 UTC, qaisjp requested changes
This PR doesn't fix the issue entirely because the cache doesn't return `nil` either:

https://github.com/multitheftauto/mtasa-blue/blob/6c6a1248adcdd9715c542a7dbdd05a5a2f99ee0e/Server/mods/deathmatch/logic/CAccountManager.cpp#L656-L660

https://github.com/multitheftauto/mtasa-blue/blob/6c6a1248adcdd9715c542a7dbdd05a5a2f99ee0e/Server/mods/deathmatch/logic/CAccount.cpp#L115-L140

2020-05-23 22:56 UTC, Pirulax commented
my bad..

2020-05-23 23:16 UTC, Pirulax commented
There you go.

2020-05-23 23:27 UTC, Pirulax commented
Il open a separate PR to refactor the code.
A few lines.

2020-05-24 00:53 UTC, qaisjp approved these changes
thanks!

2020-05-24 00:54 UTC, merged