Fix 1291 - getRotation returns incorrect values for ped when set with createPed
multitheftauto/mtasa-blue pull request #1506
Opened 2020-06-08 20:24 UTC by Pirulax

Basically, when you created a ped with `createPed` server side, and set a rotation there, the client side `getElemRot` returned incorrect values, but the ped was visually at the given rot.
This was caused by the matrix not being updated by GTA. We only set current/target rotations in the interface.

This PRr fixes the issue. I dont think it ruins backwards compatibility, since the only case this issue occurs is when the ped is created after setting the rotation values. This probably only occurs when creating the ped with `EntityAdd` packet.

2020-06-08 21:31 UTC, qaisjp requested changes
Firstly -- thanks for the pull request!

There's some style comments here - I know they can seem nitpicky but I hope you can bare with them!

But I am not certain this is a legit fix -- _I_ would expect the SetCurrentRotation method to update the matrix. I'm not 100% sure if that's the correct behaviour, though.

2020-06-08 21:31 UTC, qaisjp commented on Client/mods/deathmatch/logic/CClientPed.cpp
> +        }
Style comments:

- Please use correct capitalisation (`Update`), spelling (`through`) and punctuation (`doesn't`). Also, leave a space before your opening parenthesis (`interface (Set...)`).
- Please leave a blank line above comments.
- Please format your code to abide with .clang-format (brace spacing, comment spacing)

```suggestion

        m_pPlayerPed->SetCurrentRotation(m_fCurrentRotation);
        m_pPlayerPed->SetTargetRotation(m_fTargetRotation);

        // Fix GitHub #1291: also update the matrix to contain the current rotation
        // as just setting it through the interface above doesn't update our matrix.
        m_Matrix.SetRotation({0, 0, m_fCurrentRotation});
        SetMatrix(m_Matrix);            // also sets the matrix on m_pPlayerPed

```

2020-06-09 20:04 UTC, Pirulax commented
Well, when creating a ped server side with `createPed`, and the entity add packet arrives, and sets the rotation using `SetCurrentRotation` `m_pPlayerPed` isnt yet created, thats why the matrix isnt updated. Its pretty interesting as to why it doesnt update the matrix when the rotation is just fine.

2020-10-27 17:14 UTC, saml1er approved these changes

2020-10-29 08:56 UTC, qaisjp commented
> and sets the rotation using SetCurrentRotation

why doesn't SetCurrentRotation update the matrix?

2021-05-30 12:00 UTC, patrikjuvonen commented
I would like to merge this fix but is there an answer as to why SetCurrentRotation doesn't update the matrix and should that be the case or not?

2023-04-26 01:26 UTC, closed without merging