Add onVehicleDrown event
multitheftauto/mtasa-blue pull request #1657
Opened 2020-09-07 12:50 UTC by Unde-R

### Why we need It?
Well looks like we have `onVehicleExplode` and many other vehicle events but we don't have this one, also as requested in issue #1426, this PR introduces a new event in MTA since not everyone can use `cols` etc... and It's better than adding a `timer` or calling `onClientRender` or something to check if the element isInWater.
**(Also this event is triggered for unoccupied vehicles too)**
### Functionality
```lua
 function teteVehicle(thep)
 local x, y, z = getElementPosition(thep)
 teteCar = createVehicle(411, x+2, y, z)
 addEventHandler("onVehicleDrown", teteCar, function()
 outputChatBox("rip Tete car")
 end)
 end
 addCommandHandler("tetecar", teteVehicle)
```
This event is triggered when a vehicle drowns.
### Screenshots
![tete](https://user-images.githubusercontent.com/67543158/92388882-e65ed700-f10f-11ea-91b1-08cb57924745.png)

2020-09-07 20:16 UTC, TheNormalnij commented
I think that this event need to be complex. I see this like a `onElementWaterInteract` what will works with peds, vehicles and objects (maybe) and has `bWaterInOrOut` parameter.

2020-09-07 22:31 UTC, Unde-R commented
for objects not worth it.
We'll need to get a proper event name

2020-09-08 17:10 UTC, Unde-R commented
@qaisjp any ideas?

2020-09-12 12:28 UTC, Pirulax requested changes

2020-09-12 12:28 UTC, Pirulax commented on Server/mods/deathmatch/logic/CUnoccupiedVehicleSync.cpp
> +                            pVehicle->CallEvent("onVehicleDrown", Arguments);
This is a convention in the code more or less, afaik.
But I'd use `{}` there, or `CLuaArguments()` (but `{}` should work)
Not even sure why CallEvent doesn't default construct `CLuaArguments`

2020-09-12 12:28 UTC, Pirulax commented on Server/mods/deathmatch/logic/packets/CVehiclePuresyncPacket.cpp
> +                    pVehicle->CallEvent("onVehicleDrown", Arguments);
Same here

2020-10-19 01:38 UTC, StrixG commented on Server/mods/deathmatch/logic/CGame.cpp
> +    m_Events.AddEvent("onVehicleDrown", "", NULL, false);
```suggestion
    m_Events.AddEvent("onVehicleDrown", "", nullptr, false);
```

2020-10-20 15:06 UTC, ghost commented on Server/mods/deathmatch/logic/CVehicle.h
> +    bool           m_bLastSyncedIsInWater;
```suggestion
    bool           m_bLastSyncedIsInWater = false;
```
You don't have to initialize it in the constructor if you write the initial value for the member in the header file.

2020-10-20 15:06 UTC, ghost commented on Server/mods/deathmatch/logic/CVehicle.h
```suggestion
```
Always prefer `const` variables over preprocessors if possible. In fact, you don't even need this here.

2020-10-20 15:06 UTC, ghost commented on Server/mods/deathmatch/logic/CVehicle.cpp
> +    m_bLastSyncedIsInWater = DEFAULT_IS_IN_WATER;
```suggestion
```

2020-10-20 15:13 UTC, Unde-R commented on Server/mods/deathmatch/logic/CVehicle.h
> +    bool           m_bLastSyncedIsInWater;
oh got it

2020-10-20 20:07 UTC, qaisjp requested changes
> I think that this event need to be complex. I see this like a `onElementWaterInteract` what will works with peds, vehicles and objects (maybe) and has `bWaterInOrOut` parameter.

I agree with @TheNormalnij's comment (copied above, and here: https://github.com/multitheftauto/mtasa-blue/pull/1657#issuecomment-688497479)

This `onVehicleDrown` event doesn't look like it's detecting when a vehicle drowns, but when it interacts with water. Changing the event name now would make this a matter of finding a reason to merge code that accidentally doesn't work as intended.

Please create an issue *proposing* what feature you want to implement. In that issue, once we've discussed the what the feature should look like, we can discuss whether the code here is appropriate for that. In your issue, please try and provide answers to the questions written [here](https://github.com/Microsoft/calculator/blob/master/.github/ISSUE_TEMPLATE/feature_request.md). (Yes, it's a link to Windows Calculator's repo. See #887 for more context on what a "proposal" means.)

2020-10-28 19:51 UTC, Unde-R commented
> > I think that this event need to be complex. I see this like a `onElementWaterInteract` what will works with peds, vehicles and objects (maybe) and has `bWaterInOrOut` parameter.
> 
> I agree with @TheNormalnij's comment (copied above, from here: [#1657 (comment)](https://github.com/multitheftauto/mtasa-blue/pull/1657#issuecomment-688497479))
> 
> This `onVehicleDrown` event doesn't look like it's detecting when a vehicle drowns, but when it interacts with water. Changing the event name now would make this a matter of finding a reason to merge code that accidentally doesn't work as intended.
> 
> Please create an issue _proposing_ what feature you want to implement. In that issue, once we've discussed the what the feature should look like, we can discuss whether the code here is appropriate for that. In your issue, please try and provide answers to the questions written [here](https://github.com/Microsoft/calculator/blob/master/.github/ISSUE_TEMPLATE/feature_request.md). (Yes, it's a link to Windows Calculator's repo. See #887 for more context on what a "proposal" means.)

sure even if #1426 exists?

2020-10-28 21:23 UTC, TheNormalnij commented
GTA SA store IN_WATER state in physical flags. You can add `onClientElementPhysicalStateChanged ( oldState, newState )` for peds/vehicles/obejct. `oldState` - physical flags before GTA call `ProcessControl`, `newState` - after `ProcessControl`. You can find `ProcessControl` hooks in `multiplayer_keysync.cpp`

2020-10-31 12:12 UTC, TheNormalnij commented
If you want to add serverside event, you don't need save last isWater state.

```C++
if (flags.data.bIsInWater != pVehicle->IsInWater())
{
    ...
}
```

Correct me if it's wrong

2020-10-31 12:21 UTC, Unde-R commented
> If you want to add serverside event, you don't need save last isWater state.
> 
> ```c++
> if (flags.data.bIsInWater != pVehicle->IsInWater())
> {
>     ...
> }
> ```
> 
> Correct me if it's wrong

cheers gonna try I've seen flag code somewhere I'll try it

2020-10-31 12:31 UTC, TheNormalnij commented
![image](https://user-images.githubusercontent.com/6773493/97779278-14035200-1b8e-11eb-9eec-be3d8046e7e0.png)

2022-02-07 01:11 UTC, closed without merging