Fix onClientMarkerHit(Leave) ignores element's interior
multitheftauto/mtasa-blue pull request #1661
Opened 2020-09-10 20:58 UTC by Unde-R

According to #322 Looks like [onClientMarkerHit](https://wiki.multitheftauto.com/wiki/OnClientMarkerHit) doesn't care about element's interior and when I checked MTA's code looks like [onClientMarkerLeave](https://wiki.multitheftauto.com/wiki/OnClientMarkerLeave) does the same thing, and for [onMakerHit](https://wiki.multitheftauto.com/wiki/OnMarkerHit) and [onMakerLeave](https://wiki.multitheftauto.com/wiki/OnMarkerLeave) they do check for interior.
https://github.com/multitheftauto/mtasa-blue/blob/3b95ff48969474c691a8a4f2276f581377111f06/Server/mods/deathmatch/logic/CMarker.cpp#L315

2020-09-14 13:50 UTC, patrikjuvonen commented
I believe an extra event parameter must be added for backwards compatibility reason, but this is debatable.

2020-09-14 15:32 UTC, Unde-R commented
in discord, qaisjp said that we can fix it but without adding new parameter

2020-09-14 15:35 UTC, patrikjuvonen commented
> in discord, qaisjp said that we can fix it but without adding new parameter

@qaisjp What's your idea on backwards compatibility or is this a screw-it issue?

2020-09-14 16:24 UTC, qaisjp commented
screw it

2020-10-17 19:00 UTC, qaisjp requested changes
This works fine and is technically safe for merging... but I think, reduce confusion, we should only merge this once we've fixed interiors appearing in all dimensions (#601 needs to be reimplemented in a separate PR).

2021-05-04 10:00 UTC, Lpsd commented
Why have we decided to randomly break backwards compatibility here when a reasonable, alternative solution already exists?

I think we should just add `matchingInterior` parameter to both client and server-side versions of this event, as initially suggested.

2021-05-30 12:21 UTC, patrikjuvonen commented
Yeah, I think a parameter is good for now.

2021-05-30 12:22 UTC, patrikjuvonen requested changes

2021-05-30 12:22 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientMarker.cpp
> +    if (IS_PLAYER(&Entity) && GetInterior() == Entity.GetInterior())            // Matching interior?
For now, let's instead add the matching interior as an extra parameter to onClientMarkerHit call, just like matching dimension.

2021-05-30 12:22 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientMarker.cpp
> +    if (IS_PLAYER(&Entity) && GetInterior() == Entity.GetInterior())            // Matching interior?
For now, let's instead add the matching interior as an extra parameter to onClientMarkerHit call, just like matching dimension.

2022-02-07 01:11 UTC, closed without merging