onTransferBoxStateChange event
multitheftauto/mtasa-blue pull request #171
Opened 2017-11-19 16:21 UTC by CrosRoad95

This event allow to overwrite currently transfer box into your custom.
Arguments are `current progress` and `total size` in Bytes
example script: https://pastebin.com/Ny153ayg

2017-11-19 18:15 UTC, Citizen01 commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +    // Trasnfer box event
Typo

2017-11-19 18:30 UTC, Citizen01 commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +    m_pTransferBox->Hide( true );
Was it necessary to add `true` ?
From what I can see, the `Hide` method doesn't take any argument:
`void CTransferBox::Hide ( void )`
(But I can see that it is called that way for all the calls in that file so I don't know, maybe it's good for consistency ?)

2017-11-19 18:47 UTC, Citizen01 commented
Also as the event only sends the `new current progress` and the `total size` of the transfer and even though `onTransferBoxStateChange` would be a correct name for it, I feel like `onTransferBoxProgressChange` would better reflect what it actually sends.
With the current name you gave to that event, (before opening the code changes) I was expecting that you would send something like:
- "show"
- "progress", current, total
- "hide"

But you only do the 2nd point.

2017-11-19 19:35 UTC, Citizen01 commented
Maybe my english isn't good or you went too fast into making the changes but if you now trigger the 3 states then you should keep `onTransferBoxStateChange`. I was saying that if you only send the progress, then one would expect `onTransferBoxProgressChange` as the name for this event.
Sorry for the confusion, can you set the name back to `onTransferBoxStateChange` ?

2017-12-10 14:07 UTC, Necktrox commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +    m_Events.AddEvent( "onTransferBoxStateChange", "type, currentStatus, totalSize", NULL, false );
Should be `onTransferBoxProgressChange`

2017-12-11 20:10 UTC, Citizen01 commented
Can we discuss about the name of that event instead of changing it back and forth ?
@Necktrox This event was only sending the current download progress at the begining so `onTransferBoxProgressChange` was the right name for it.
But now, @CrosRoad95 modified the code of that PR so that it is also sending when the progress bar shows up and when it is hides itself so there are clearly 3 states:
1. The progress bar **shows** up, the event is triggered with `type="show"`.
2. The current **progress** changes, the event is triggered with  `type="progress"`, `currentStatus=<currentDownloadProgressInBits>`, `totalSize=<totalDownloadSizeInBits>`
3. The progress bar **hides** at the end, the event is triggered with `type="hide"`.

With that in mind, I don't see why we should stick with `onTransferBoxProgressChange` instead of `onTransferBoxStateChange` ?

I'm up for any discussion.

2017-12-11 20:46 UTC, Necktrox commented
@Citizen01 I agree, but my code was more about correctness, because the supplied code prior to the changes didn't work.

Furthermore, I would prefer two functions to control/get the visibility of the transfer window instead of cancelling the event.

2017-12-11 21:01 UTC, Citizen01 commented
> Furthermore, I would prefer two functions to control/get the visibility of the transfer window instead of cancelling the event.

I agree but we do so, can the transfer box still flash in the screen if the timing isn't right ?

2017-12-14 20:01 UTC, AlexTMjugador commented
I love the idea of giving scripters some control over the transfer progress GUI, because it is needed to integrate it visually with a scripted, custom GUI system, for example. However, this also allows the potential for scripters to hide the player how much bytes were downloaded from a server, which can be a concern when playing under metered connections. I think it'd be ideal to enforce MTA to display that information no matter what, and then allow scripters to build their own things on top of that if they want to. Maybe some subtle DirectX text in some place can do it when the event is cancelled.

2017-12-14 22:05 UTC, Necktrox commented
@AlexTMjugador Or combine this feature with pull request #154 (**Added size column in the server list**)

2017-12-17 20:30 UTC, AlexTMjugador commented
That'd be great for me, @Necktrox 👍 . A win-win for everyone.

About the event cancelling, I also think it'd be more appropiate to just provide two functions: one to set the hide status of the transfer window, and another to get it. It's not that hiding it by cancelling the event is incorrect, but in my opinion script logic can get easier the other way. If several scripts want to hide the transfer window, they can call that function once, and if the event triggers then they know that it's because other script enabled it back on. In the case that they didn't have that function, those scripts would have to keep track of the related operations of other scripts more actively, which would lead to more complex and therefore less mantainable code.

2018-02-20 16:46 UTC, MIKI785 commented
@Necktrox I understand the concerns for the size of the download still being known to the player, however, the scripter can easily work around this anyway. Simply don't put any files to be downloaded in the meta.xml and then download them using for example _triggerLatentClientEvent_.
The only way to be sure to see the amount of data being downloaded is to use the _shownetstat_ command.
The reason why I'm posting this is why worry about the scripters hiding the total amount if they already can?

2018-07-03 11:00 UTC, qaisjp commented
I haven't looked at the code or considered whether this feature is suitable. To answeer one of the things mentioned...

> However, this also allows the potential for scripters to hide the player how much bytes were downloaded from a server, which can be a concern when playing under metered connections.

There should be an MTA setting to prevent the server from controlling the transfer box: `Allow servers to control the transfer box`, default could be `true`.

With the box unchecked, `setTransferBoxEnabled` would return `false`.

2018-08-06 15:38 UTC, patrikjuvonen submitted a review, later dismissed
Please fix any compile errors (see AppVeyor: https://ci.appveyor.com/project/multitheftauto/mtasa-blue/build/ci-1458/messages).

2019-01-01 07:00 UTC, qaisjp submitted a review, later dismissed

2019-01-01 07:00 UTC, qaisjp commented on Client/core/CSettings.h
> +    bool bAllowScreenUploadEnabled;
Wrong variable? Something odd happening here as well in CSettings.cpp

2019-01-01 07:00 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> -    // bool guiEditIsReadOnly( element editField )
Unneeded changes. You can fix this by copying over this file from master, and then reapplying your additions in this file.

2019-02-23 22:22 UTC, patrikjuvonen commented
## Summary
  * New client setting "_Allow server to control transfer box_"
  * New event **onClientTransferBoxProgressChange** with two parameters: `int downloadedBytes`, `int totalBytes`
    * This event is only triggered if _Allow server to control transfer box_ setting is turned on
  * New function `bool isTransferBoxEnabled ( )` which returns a boolean representing whether the native transfer box is enabled or not
  * New function `bool setTransferBoxEnabled ( bool enabled )` which returns a boolean representing whether toggling the native transfer box was successful or not
    * It will return **false** if the client setting is turned off
  * Native transfer box will hide if the transfer box is disabled using `setTransferBoxEnabled`. This should also happen mid-transfer.
  * Native transfer box will show if the transfer box is enabled using `setTransferBoxEnabled`, or the client setting is turned off. This should also happen mid-transfer.
  * Bare in mind that in the current state of the PR, a client hang, which can be caused by the said download, will not necessarily show/hide the native transfer box immediately or at all, until client is responsive again. I don't think this is a problem, since you can create a very small resource to handle resource downloads and that will be able to call the necessary functions before any other transfer. If the setting gets toggled mid-transfer, I don't think that's something we should worry about. This also can be avoided by chunking downloads and using [triggerLatentClientEvent](https://wiki.multitheftauto.com/wiki/TriggerLatentClientEvent) for some scripts.

## Requesting scripting feedback
  * Let's work towards consensus on what triggers the event, what its name and parameters should be. There have been some great suggestions in this PR, but I would like to bring the discussion back alive and end with a voting of some sorts, considering this PR and discussion is quite old now.

Anything else we've missed?

2019-02-25 21:54 UTC, qaisjp commented
> Personally, I don't think this feature is required per se, but I don't mind having it around for more custom loading screens.

My silence on this PR (outside general code review) is due to the fact I am not so sure this feature is a good idea.

2019-03-11 14:53 UTC, moon91210 commented
> My silence on this PR (outside general code review) is due to the fact I am not so sure this feature is a good idea.

I don't see any reason for concern. People have been requesting this for ages. People just want to create better looking loading screens. Other games support this, take Garry's Mod for example. What's the worst that could happen?

2019-04-26 05:22 UTC, qaisjp commented
> I don't see any reason for concern. People have been requesting this for ages. They just want to create better looking loading screens. Other games support this, take Garry's Mod for example. What's the worst that could happen?

Better loading screens would indeed be nice, and I would be open to discussing such a proposal. However, the functions introduced in this pull request can't be used to implement better looking loading screens as client resources do not initially run until they have all been downloaded.

Thinking about it, I don't see any harm in this PR.

Some notes:
- should not be cancellable.
- a state change with "show", "progress"(+vals), and "hide" (as described here https://github.com/multitheftauto/mtasa-blue/pull/171#issuecomment-350843318) seems reasonable.

2020-04-02 13:58 UTC, qaisjp requested changes
I merged master in. hopefully i did it correctly. i didn't shift the GUI checkbox around, so someone needs to do that.

2020-10-28 16:15 UTC, iDannz-Breno commented
Will we have any update about this?

I think we wouldn't even need a checkbox to confirm whether or not the server can handle the transferbox, i think ideal would be that if the server disables it, it would be visible anyway by pressing esc, that is: allow the servers to use "setTransferBoxEnabled" but this effect would not apply to the main menu

2020-12-29 16:07 UTC, patrikjuvonen commented
Let's move to the latest, further and actively developed PR at #1955.

2020-12-29 16:07 UTC, closed without merging