Add intersectsSegmentTriangle method to Vector3
multitheftauto/mtasa-blue pull request #1711
Opened 2020-10-12 21:32 UTC by Pirulax

I was lazy to switch branches lol

This PR exposes the `intersectsSegmentTriangle` method that can be found in the `CVector` class. (its used in testLineAgainstWater)
The performance seems way better(300%, although my algorithm is more optimized, as it has everything possible cached) than the Lua implementation (with vectors. Without it probably would be way better).

Hope this gets merged fast, as the algorithm itself it tested already.

Note:  Haven't looked into the algorithm itself, but im pretty sure its optimized. The bottleneck is our Lua API probably. (Maybe the old parser would be a slightly bit faster)

2020-10-13 00:08 UTC, Woovie approved these changes

2020-10-13 00:13 UTC, Pirulax commented
@sbx320 Could you help me with this? The non msvc builds

2020-10-24 02:53 UTC, qaisjp requested changes
1. Non-windows will need fixing
2. Place them underneath "dot", there's no need to start a brand new section (in this case it starts with create/static, then special operations, then getters, then setters, then variables)

2021-02-06 14:56 UTC, botder commented
@Pirulax what's the status on this?

2021-03-07 16:17 UTC, Pirulax commented
Well should I make it work?

2021-03-07 16:22 UTC, botder commented
Sure, why not.

2021-08-04 10:00 UTC, patrikjuvonen commented
Hey @Pirulax, what's the status of this pull request, can we expect it for the upcoming release?

2021-08-17 20:22 UTC, Pirulax commented
This function can be called without an instance of a vector. Eg.:
```lua
Vector3.intersectsSegmentTriangle(0, 0, 0, 0, 5, 5, 5, 0, 0, 0, 5, 0, 0, 0, 5);
```
```lua
Vector3(0, 0, 0):intersectsSegmentTriangle(0, 5, 5, 5, 0, 0, 0, 5, 0, 0, 0, 5);
```
Will yield the same result.

Should it be added as a global function as well at this point?

2021-08-17 20:27 UTC, patrikjuvonen commented
> This function can be called without an instance of a vector. Eg.:
> 
> ```lua
> Vector3.intersectsSegmentTriangle(0, 0, 0, 0, 5, 5, 5, 0, 0, 0, 5, 0, 0, 0, 5);
> ```
> 
> ```lua
> Vector3(0, 0, 0):intersectsSegmentTriangle(0, 5, 5, 5, 0, 0, 0, 5, 0, 0, 0, 5);
> ```
> 
> Will yield the same result.
> 
> Should it be added as a global function as well at this point?

I'm not sure we have other Vector3-based global functions as such so this would stand out unnecessarily. I think it's fine like this.

2021-08-17 20:29 UTC, Pirulax commented
Well `getDistanceBetweenPoints` does the same as `(a - b).Length()`
So thats some kind of a wrapper.

2021-08-28 18:22 UTC, patrikjuvonen commented on Shared/mods/deathmatch/logic/lua/LuaBasic.h
> +
Are these additions needed?

2021-09-07 13:33 UTC, Pirulax commented
Just wanna make sure it gets merged to 1.5.9

2021-09-08 19:46 UTC, patrikjuvonen approved these changes
Thanks, tested lightly.

2021-09-08 19:46 UTC, merged

2021-09-20 16:13 UTC, patrikjuvonen commented
Please document this change on the Vector3 Wiki page at https://wiki.multitheftauto.com/wiki/Vector/Vector3