prevent multiple kick/ban of 1 player
multitheftauto/mtasa-blue pull request #173
Opened 2017-11-20 20:16 UTC by CrosRoad95

This PR disallow kick/ban player if player was kicked/banned

Currently code below will display hunders of information `player was kicked bla bla bla`

script serverside
```lua
function quitPlayer ( quitType )
	iprint("kick 2", kickPlayer(source))
end
addEventHandler ( "onPlayerQuit", getRootElement(), quitPlayer )
iprint("ban 1", kickPlayer(getRandomPlayer()))```

2017-12-01 20:48 UTC, Necktrox commented on Server/mods/deathmatch/logic/CPlayer.h
> +    bool                                        bIsQuit;
Member variables must be prefixed with **m_**. Furthermore, you might want to name this variable **m_bIsLeaving**, but this is up for debate.

2017-12-01 20:49 UTC, Necktrox commented on Server/mods/deathmatch/logic/CPlayer.h
> +    bool                                        IsQuit                      ( void )                        { return bIsQuit; }
You might want to name this method **IsLeavingServer**, but this is up for debate.

2017-12-01 20:51 UTC, Necktrox commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        return NULL;
Return **nullptr** instead.

2018-01-26 15:48 UTC, CrosRoad95 commented
```lua
addEventHandler ( "onPlayerQuit", getRootElement(), function()
  iprint("kick, redirect in onPlayerQuit event", kickPlayer(source), redirectPlayer(source,"",0)) -- return false, false
end )

plr = getRandomPlayer()
if(plr)then
  iprint("kick outside event", kickPlayer(getRandomPlayer()))
end

addEventHandler ("onPlayerJoin", root, function()
  iprint("kick in onPlayerJoint event", kickPlayer(source)) -- return true
end)
```
![dj-k9uzuqj2luslajlubxq](https://user-images.githubusercontent.com/22455534/35447707-aea21586-02b8-11e8-9d50-17736c98f5b8.png)

2018-07-14 02:39 UTC, qaisjp requested changes

2018-07-14 02:39 UTC, qaisjp commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    if ( pPlayer->IsLeavingServer() ) {
The ban here should still be applied

2018-07-14 02:39 UTC, qaisjp commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    if ( pPlayer->IsLeavingServer() ) {
please fix formatting (whitespace)

2018-07-14 02:39 UTC, qaisjp commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        if ( pPlayer->IsLeavingServer() ) {
please fix formatting (whitespace)

2018-07-14 02:39 UTC, qaisjp commented on Server/mods/deathmatch/logic/CPlayer.h
> +    bool      IsLeavingServer( void ){ return m_bIsLeavingServer; }
please fix formatting (whitespace)

2018-07-14 02:39 UTC, qaisjp commented on Server/mods/deathmatch/logic/CGame.cpp
> +    if ( Player.m_bIsLeavingServer) {   // prevent multiple kick one player
please fix formatting (whitespace)

2018-08-26 04:11 UTC, qaisjp requested changes
Thanks! The ban should still be applied on their way out, though.

2018-10-26 19:13 UTC, merged