Upgrade SString to the latest c++ standards (as much as possible)
multitheftauto/mtasa-blue pull request #1800
Opened 2020-11-04 12:14 UTC by Pirulax

According to @sbx320:
> well it might just randomly break net :smile:
I really hope it doesn't.

2020-11-14 01:16 UTC, Pirulax commented
@sbx320  are you sure about this "breaks net" thing?
https://github.com/multitheftauto/mtasa-blue/blob/7742f34b1fe9b12d3f75d8637e1d73d8fab7d997/Shared/sdk/net/CNetHTTPDownloadManagerInterface.h#L48-L58

2020-12-29 22:50 UTC, patrikjuvonen requested changes

2020-12-29 22:50 UTC, patrikjuvonen commented on Shared/sdk/SString.h
> +    SString(std::string_view view) : std::string(view) {}
Generates build errors on Windows: https://github.com/multitheftauto/mtasa-blue/pull/1800/checks?check_run_id=1352728735#step:8:5421

2020-12-29 22:50 UTC, patrikjuvonen commented on Shared/sdk/SString.h
> +    operator std::string_view() const { return *this; }
Generates build errors on Windows: https://github.com/multitheftauto/mtasa-blue/pull/1800/checks?check_run_id=1352728735#step:8:5425

2022-02-07 01:11 UTC, closed without merging