Use fmt::format instead of SString constructor for string formatting
multitheftauto/mtasa-blue pull request #1804
Opened 2020-11-05 20:49 UTC by Pirulax

Replace all SString consructors that are used for string formatting to `fmt::format`.
Replace SString ctors that are used for number -> string conversion with std::to_string.

Todo: 
- [ ]  Rewrite SString constructor to use `fmt::format` as well.

I've made a python script (250-300 lines, terrible code), that did all this for me, thankfully.

2020-11-05 21:20 UTC, ccw808 commented
Might cause an issue with localization

2020-11-05 21:34 UTC, Pirulax commented
And how could they be solved?

2020-11-05 22:06 UTC, ccw808 commented on Client/core/CConnectManager.cpp
> +        SString strBuffer(_("Connecting to {} at port {} failed!"), m_strHost, m_usPort);
Strings inside _() are matched and replaced depending on the selected language. e.g. "Connecting to %s at port %u failed!" is replaced with "تعذر الإتصال بـ %s في المنفذ %u!" when Arabic is selected. Changing the content of the original string will make the match fail, and probably flag the string as requiring a new translation at https://translate.mtasa.com/

2020-11-05 22:09 UTC, Pirulax commented on Client/core/CConnectManager.cpp
> +        SString strBuffer(_("Connecting to {} at port {} failed!"), m_strHost, m_usPort);
Yeah, this was done by a script, and I didnt verify it yet. (Forgot to mark the PR as draft).
I'll correct this, thanks!

2020-11-05 22:18 UTC, Pirulax commented on Client/core/CConnectManager.cpp
> +        SString strBuffer(_("Connecting to {} at port {} failed!"), m_strHost, m_usPort);
Yeah, this was done by a script, and I didnt verify it yet. (Forgot to mark the PR as draft).
I'll correct this, thanks!

Edit: Can I edit the `.po` files myself, to make it work? Eg.: Replace `Connecting to %s at port %u failed!`  with `Connecting to {} at port {} failed!` in the `.po` as well.

(Reposted it, as edits dont show up on dc)

2020-11-07 03:27 UTC, qaisjp commented on Client/core/CConnectManager.cpp
> +        SString strBuffer(_("Connecting to {} at port {} failed!"), m_strHost, m_usPort);
> Can I edit the `.po` files myself

The files are generated by one of the scripts here https://github.com/multitheftauto/mtasa-blue/tree/master/utils/src I think build_gettext_catalog.py

2020-11-07 03:27 UTC, qaisjp requested changes
As with #1804 I think we should wait for c++20 instead of adding another dependency.

Especially hopping from SString to fmt::format to std::string seems like a lot of unnecessary mass changes.

2020-11-12 23:05 UTC, qaisjp commented
"Set cppdialect to C++20 #1803" has been closed in favour of just waiting for C++20 to release. Going to close this too.

2020-11-12 23:05 UTC, closed without merging