Remove CRefCountableST
multitheftauto/mtasa-blue pull request #1825
Opened 2020-11-11 19:14 UTC by Pirulax

Before you go ahead and create a pull request, please make sure:

* [ ] [your code follows the coding guidelines](https://wiki.multitheftauto.com/index.php?title=Coding_guidelines)
* [ ] your commit messages are informative ("update file.cpp" is unhelpful. "fix missing model in getVehicleNameFromModel" is helpful)

If your work is incomplete, **do not prefix your pull request with "WIP"**, instead
create a _draft_ pull request: https://github.blog/2019-02-14-introducing-draft-pull-requests/

Thank you!

2020-11-11 19:39 UTC, ccw808 commented
Would it be possible to measure the performance difference between the two methods?

2020-11-11 20:29 UTC, Pirulax commented
Yeah, but not the c++ code directly as the compiler will optimize it(so its very hard to measure it head to head), and synthetic benchmarks are prone to CPU caching, while in our case the CPU has no chance to cache it at all.
What I can do is I can measure from the API side (eg from Lua) if a specific function got any slower. Altough, again, thats pretty synthetic, and the CPU might cache something.


From [here](https://quick-bench.com/q/2nS4gcb9CPlpuVXMUOjMfwDce4o) its seems like its 3x slower, but looking at the assembly makes me wonder whenever its actually measured properly. (aka I think `AddRef` and `Release` actually got optimized away, so the code doesnt do anything), I presume the compiler has realized that incrementing and decrementing the values after each other results in no change.

2022-09-11 15:31 UTC, botder requested changes

2022-09-11 15:31 UTC, botder commented on Client/mods/deathmatch/logic/CClientEntity.cpp
> +            m_pChildrenListSnapshot->push_back(*it);
```suggestion
        m_pChildrenListSnapshot->reserve(m_Children.size());

        for (auto iter = m_Children.begin(); iter != m_Children.end(); iter++)
            m_pChildrenListSnapshot->push_back(*iter);
```

2022-09-11 15:31 UTC, botder commented on Server/mods/deathmatch/logic/CElement.cpp
> +            m_pChildrenListSnapshot->push_back(*it);
```suggestion
        m_pChildrenListSnapshot->reserve(m_Children.size());

        for (auto iter = m_Children.begin(); iter != m_Children.end(); iter++)
            m_pChildrenListSnapshot->push_back(*iter);
```

2022-09-11 15:57 UTC, botder approved these changes

2022-09-11 15:57 UTC, merged