Update Unifont from 5.1 to 13.0.04
multitheftauto/mtasa-blue pull request #1875
Opened 2020-11-27 15:40 UTC by Dutchman101

This PR updates Unifont from version 5.1 (2008) to 13.0.04 (Nov 2020)

There's no reason not to update, it's tested and works fine, and in fact looks a little better overall. Comment #1 on issue #1864 inspired this PR.

2020-11-27 15:42 UTC, Dutchman101 commented
For verification purposes, the official source of Unifont is [http://unifoundry.com/unifont/index.html](http://unifoundry.com/unifont/index.html) and the release information for this .ttf is found under "**21 November 2020 Release (Unifont 13.0.04)**" on said page, and so is the download.

2020-11-27 16:07 UTC, Pirulax commented
Didn't try it, but lgtm.

2020-11-27 16:08 UTC, Pirulax approved these changes

2020-11-27 16:36 UTC, StrixG approved these changes

2020-11-27 19:02 UTC, qaisjp requested changes
I wonder if we can find a better solution than uploading a 11.7 MB font to Git. Hmm. We should think about this.

2020-11-27 19:09 UTC, Pirulax commented
Well, the whole repo is 600-700 megs, so + 6 megs won't make a difference imho.
These fonts need to be downloaded anyways.
But if we really don't want to host them on git, we could move it into `install_data.bat`

2020-11-27 19:17 UTC, CrosRoad95 commented
+11.7MB but -15.6MB, so worth

2020-11-27 19:36 UTC, qaisjp commented
> Well, the whole repo is 600-700 megs, so + 6 megs won't make a difference imho.
> These fonts need to be downloaded anyways.
> But if we really don't want to host them on git, we could move it into `install_data.bat`

It adds up. Git is not built for binary files!



> +11.7MB but -15.6MB, so worth

This makes no sense. Both files are kept in history

2020-11-27 19:51 UTC, Pirulax commented
Ah, good point.
Should we use `install_data` for fonts then?

2020-11-27 20:38 UTC, qaisjp commented
Yes, I think install_data will work. Should we host it on GitHub in a separate repo or upload it to mta servers?

2020-11-27 20:55 UTC, Pirulax commented
Well, everything seems to be on MTA's servers (netc, etc..), sooo.
Is there any advantage in using a repo for the files?

2020-11-27 22:04 UTC, qaisjp commented
> Well, everything seems to be on MTA's servers (netc, etc..), sooo.
> Is there any advantage in using a repo for the files?

Helps ensure reproducible builds and better tracking of uploaded files. Note that the (now removed) discord DLLs pull from GitHub!

2020-11-28 20:47 UTC, qaisjp commented
I've created a repo and release here: https://github.com/multitheftauto/unifont/releases/tag/v13.0.04

Direct download link: https://github.com/multitheftauto/unifont/releases/download/v13.0.04/unifont-13.0.04.ttf

2020-11-30 05:05 UTC, sbx320 commented
If we want this to be versioned in git, we could use submodules + individual repos per update.

2020-11-30 08:14 UTC, Pirulax commented
Just don't forget to add the sub module init steps to `readme.md`.

2020-11-30 13:12 UTC, qaisjp commented
Yeah there's lots of guidance on how to implement this with submodules in #319

2020-12-14 09:35 UTC, Dutchman101 commented
How to proceed, or incorporate (e.g pull from) [https://github.com/multitheftauto/unifont/](https://github.com/multitheftauto/unifont/) in this PR? I don't really get it.

What exactly does someone need to do for Unifont to get updated? Does it have to do with creating an install-date procedure or premake script that pulls directly from unifont repo? Then i gotta say it's not my thing, so someone that has experience with it feel free to add those changes to this PR (or create a new PR).

2021-01-04 13:01 UTC, patrikjuvonen commented
Follow up PR at #1980

2021-01-04 13:01 UTC, closed without merging