Height for colpolygon
multitheftauto/mtasa-blue pull request #1908
Opened 2020-12-07 16:49 UTC by CrosRoad95

Functions to set/get height of colpolygon. "false" as argument resets to +- float min, max value ( basicly, infinity ). Both are client and server side.
```lua
setColPolygonHeight( colpolygon, floor, roof ) 
polygon:setHeight(floor, roof)

floor, roof = getColPolygonHeight( colpolygon )
floor, roof = colpolygon:getHeight()
```

I don't know what version i need to set in Server/mods/deathmatch/logic/CResourceChecker.Data.h, i set 1.5.7 for now.

```cpp
        {"setColPolygonHeight", "1.5.7"},
        {"setColPolygonHeight", "1.5.7"},
```

test resource: [polygonheight.zip](https://github.com/multitheftauto/mtasa-blue/files/5654027/polygonheight.zip)

2020-12-07 16:54 UTC, qaisjp requested changes

2020-12-07 16:54 UTC, qaisjp commented on Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
> +                            if (BitStream.Version() >= 0x1DA)
Don't use BitStream.Version() use `BitStream.Can()`

2020-12-07 16:54 UTC, qaisjp commented on Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
> +    static bool                     SetColPolygonHeight(CColPolygon* pColPolygon, std::variant<bool, float> floor, std::variant<bool, float> ceil);
formatting

2020-12-07 16:54 UTC, qaisjp commented on Server/mods/deathmatch/logic/CResourceChecker.Data.h
> +        {"setColPolygonHeight", "1.5.7"},
we're on 1.5.8

2020-12-07 16:54 UTC, qaisjp commented on Client/mods/deathmatch/logic/rpc/CColShapeRPCs.h
> +};
Missing newline at end of file

2020-12-07 16:54 UTC, qaisjp commented on Client/mods/deathmatch/logic/rpc/CColShapeRPCs.cpp
> +}
Incorrectly formatted

2020-12-07 16:54 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +
Don't add to CStaticFunctionDefinitions when using the new parser, just add code directly to lua definitions

2020-12-07 16:55 UTC, qaisjp commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
> +#include "lua/CLuaFunctionParser.h"
Add to .cpp not the header

2020-12-07 16:57 UTC, qaisjp commented on Client/mods/deathmatch/logic/CClientColPolygon.cpp
> +            if (m_fFloor < fZ && fZ < m_fCeil)
shouldn't this be inclusive?

2020-12-17 13:15 UTC, CrosRoad95 commented
Fixed, and i'm thinking it is ready to marge

2021-01-16 20:04 UTC, patrikjuvonen requested changes
Thanks for the pull request. I've reviewed some formatting issues. All seems to be working 
good according to your provided test resource.

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientColPolygon.h
> +    void GetHeight(float &fFloor, float &fCeil) { fFloor = m_fFloor; fCeil = m_fCeil; };
- Nit: ampersand should be together with `float`
- Declare as `const`
```suggestion
    void GetHeight(float& fFloor, float& fCeil) const { fFloor = m_fFloor; fCeil = m_fCeil; };
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.cpp
> +
Nit: unwanted extra new line.
```suggestion
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
> +    static bool SetColPolygonHeight(CClientColPolygon* pColPolygon, std::variant<bool, float> floor, std::variant<bool, float> ceil);
Nit: fix formatting
```suggestion
    static bool                     SetColPolygonHeight(CClientColPolygon* pColPolygon, std::variant<bool, float> floor, std::variant<bool, float> ceil);
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/rpc/CColShapeRPCs.h
> +
Nit: unwanted extra new line.
```suggestion
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CPacketHandler.cpp
> +                                pPolygon->SetHeight(fFloor, fCeil);
```suggestion
                                if (bitStream.Read(fFloor) && bitStream.Read(fCeil))
                                    pPolygon->SetHeight(fFloor, fCeil);
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CColPolygon.h
> +    void GetHeight(float &fFloor, float &fCeil) { fFloor = m_fFloor; fCeil = m_fCeil; };
- Nit: ampersand should be together with `float`
- Declare as `const`

```suggestion
    void GetHeight(float& fFloor, float& fCeil) const { fFloor = m_fFloor; fCeil = m_fCeil; };
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        CBitStream      BitStream;
Nit: fix formatting
```suggestion
        CBitStream BitStream;
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Shared/sdk/net/rpc_enums.h
> +    COLSHAPE_POLYGON_SET_HEIGHT,
Perhaps rename to `SET_COLPOLYGON_HEIGHT` for consistency.
```suggestion
    SET_COLPOLYGON_HEIGHT,
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/rpc/CColShapeRPCs.cpp
> +    AddHandler(COLSHAPE_POLYGON_SET_HEIGHT, SetColShapePolygonHeight, "SetColShapePolygonHeight");
Perhaps rename to `SET_COLPOLYGON_HEIGHT` for consistency.
```suggestion
    AddHandler(SET_COLPOLYGON_HEIGHT, SetColShapePolygonHeight, "SetColShapePolygonHeight");
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/rpc/CElementRPCs.cpp
> +    AddHandler(COLSHAPE_POLYGON_SET_HEIGHT, SetColPolygonHeight, "setColShapePolygonHeight");
Perhaps rename to `SET_COLPOLYGON_HEIGHT` for consistency.
```suggestion
    AddHandler(SET_COLPOLYGON_HEIGHT, SetColPolygonHeight, "setColShapePolygonHeight");
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientColPolygon.cpp
> +    if (z > m_fCeil || z < m_fFloor)
Unnecessary variable.
```suggestion
    if (vecNowPosition.fZ > m_fCeil || vecNowPosition.fZ < m_fFloor)
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CColPolygon.cpp
> +    if (z > m_fCeil || z < m_fFloor)
Unnecessary variable.
```suggestion
    if (vecNowPosition.fZ > m_fCeil || vecNowPosition.fZ < m_fFloor)
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Shared/sdk/net/bitstream.h
> +    SetPolygonHeight,
Better clarification.
```suggestion
    SetColPolygonHeight,
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CPacketHandler.cpp
> +                            if (bitStream.Can(eBitStreamVersion::SetPolygonHeight))
Better clarification.
```suggestion
                            if (bitStream.Can(eBitStreamVersion::SetColPolygonHeight))
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/packets/CEntityAddPacket.cpp
> +                            if (BitStream.Can(eBitStreamVersion::SetPolygonHeight))
Better clarification.
```suggestion
                            if (BitStream.Can(eBitStreamVersion::SetColPolygonHeight))
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
> +    static bool SetColPolygonHeight(CColPolygon* pPolygon, float fFloor, float fCeil);
Nit: naming consistency
```suggestion
    static bool SetColPolygonHeight(CColPolygon* pColPolygon, float fFloor, float fCeil);
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/luadefs/CLuaColShapeDefs.h
> +	static bool                     SetColPolygonHeight(CColPolygon* pColPolygon, std::variant<bool, float> floor, std::variant<bool, float> ceil);
Fix indentation.
```suggestion
    static std::tuple<float, float> GetColPolygonHeight(CColPolygon* pColPolygon);
    static bool                     SetColPolygonHeight(CColPolygon* pColPolygon, std::variant<bool, float> floor, std::variant<bool, float> ceil);
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CPerfStat.RPCPacketUsage.cpp
> +ADD_ENUM1(COLSHAPE_POLYGON_SET_HEIGHT)
Perhaps rename to `SET_COLPOLYGON_HEIGHT` for consistency.
```suggestion
ADD_ENUM1(SET_COLPOLYGON_HEIGHT)
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        m_pPlayerManager->BroadcastOnlyJoined(CElementRPCPacket(pColPolygon, COLSHAPE_POLYGON_SET_HEIGHT, *BitStream.pBitStream));
Perhaps rename to `SET_COLPOLYGON_HEIGHT` for consistency.
```suggestion
        m_pPlayerManager->BroadcastOnlyJoined(CElementRPCPacket(pColPolygon, SET_COLPOLYGON_HEIGHT, *BitStream.pBitStream));
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientColPolygon.cpp
> +
Nit: unwanted extra new line.
```suggestion
```

2021-01-16 20:04 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientColPolygon.cpp
> +    }
Can these be merged in any way?

2021-01-16 21:38 UTC, patrikjuvonen approved these changes
Thanks for the pull request. Tested working with the provided test resource.

2021-01-16 21:57 UTC, merged