Add isBrowserRenderingPaused
multitheftauto/mtasa-blue pull request #1999
Opened 2021-01-13 22:47 UTC by cleopatradev

https://github.com/multitheftauto/mtasa-blue/issues/1996

```lua
isBrowserRenderingPaused(browser)
browser:isRenderingPaused

browser.renderingPaused
```

2021-01-13 22:59 UTC, Unde-R commented
try to use the new parser

2021-01-14 17:33 UTC, Lpsd commented
I don't think you should add this to `m_Properties`. Store it under `m_bIsRenderingPaused` instead.

2021-01-14 18:04 UTC, cleopatradev commented
> I don't think you should add this to `m_Properties`. Store it under `m_bIsRenderingPaused` instead.

Is there a reason for performance?

2021-01-14 20:20 UTC, Lpsd commented
There's no reason for a Lua script to be able to modify this value (as it's a property). If anything you don't want that.

This value should only be changed via `SetRenderingPaused`

2021-01-15 12:11 UTC, Lpsd requested changes
Looks good to me. Just a few unintentional formatting changes which need reverting and this is ready to go.

2021-01-15 12:11 UTC, Lpsd commented on Client/cefweb/CWebView.cpp
> +        this);
Unrelated formatting change. Please revert

2021-01-15 12:11 UTC, Lpsd commented on Client/cefweb/CWebView.cpp
> +        this);
Unrelated formatting change. Please revert

2021-01-15 12:11 UTC, Lpsd commented on Client/cefweb/CWebView.cpp
> +                                                                      CefRefPtr<CefRequestCallback> callback)
Unrelated formatting change. Please revert

2021-01-15 15:10 UTC, Lpsd approved these changes
Thanks for making the requested changes.

lgtm :shipit:

2021-01-15 15:10 UTC, merged