Add onClientObjectMove, onClientObjectMoveFinish event, add isObjectM…
multitheftauto/mtasa-blue pull request #2023
Opened 2021-01-18 11:00 UTC by cleopatradev

Added 2 events 1 functions:
```lua
bool isObjectMoving(object)
event onClientObjectMove
event onClientObjectMoveFinish
```

Code on lua:
```lua
local obj = createObject(5239, -2417.22339, -606.70374, 132.56250)
moveObject(obj, 3000, -2417.22339, -606.70374, 137.56250)

addEventHandler("onClientObjectMove", obj,
    function(x, y, z)
        outputChatBox("MOVE_OBJECT: "..x.." - "..y.." - "..z)
    end
)

addEventHandler("onClientObjectMoveFinish", obj,
    function()
        outputChatBox("done")
    end
)
setTimer(
    function()
        outputChatBox(tostring(isObjectMoving(obj)))
    end,
500, 0)
```

2021-01-18 11:22 UTC, botder commented on Client/mods/deathmatch/logic/CDeathmatchObject.cpp
> +    this->CallEvent("onClientObjectMove", Arguments, true);
This is going to crash the client if somebody decides to use `stopObject` or `moveObject` inside that event handler.

2021-01-18 17:29 UTC, Lpsd requested changes
Small thing, single-line ifs like this:
```cpp
if (true)
    foo.DoSomething();
```

2021-01-18 18:04 UTC, Lpsd reviewed
Looks good, left you one thing to deal with.

2021-01-18 18:04 UTC, Lpsd commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    return bIsMoving;
Remove this and just initialize `bIsMoving` as false.

2021-01-18 18:04 UTC, Lpsd commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    return bIsMoving;
Didn't mean to include the `return bIsMoving;` line

2021-01-19 18:51 UTC, Lpsd requested changes
Good work, just fix that extra newline and we're good.

2021-01-19 18:51 UTC, Lpsd commented on Client/mods/deathmatch/logic/CDeathmatchObject.cpp
> +
Unnecessary additional space

2021-01-20 22:09 UTC, Lpsd approved these changes

2021-01-20 22:09 UTC, merged

2021-01-21 19:40 UTC, patrikjuvonen commented
@cleopatradev Please create new Wiki pages for these event and the function, thank you.
https://wiki.multitheftauto.com/wiki/Main_Page