Add ToString to CXMLNodeImpl
multitheftauto/mtasa-blue pull request #2031
Opened 2021-01-20 16:50 UTC by Lpsd

Helps with #2026

2021-01-22 22:53 UTC, Pirulax requested changes, later dismissed

2021-01-22 22:53 UTC, Pirulax commented on Shared/XML/CXMLNodeImpl.cpp
> +        return std::string(printer.CStr());
return {printer.CStr()};

2021-01-22 22:53 UTC, Pirulax commented on Shared/XML/CXMLNodeImpl.cpp
> +    return std::string("");
return {};

2021-01-24 23:18 UTC, sbx320 approved these changes

2021-02-04 00:59 UTC, merged