Add new "raw" argument fix of #2052
multitheftauto/mtasa-blue pull request #2053
Opened 2021-01-28 14:34 UTC by Disinterpreter

New "raw" argument for manual handling requests #2052

2021-01-28 18:35 UTC, Citizen01 commented
hmmm what about `body` instead of `raw` ?
I don't think raw is meaningful enough as to what it is (could be the raw http request that contains the headers, cookies, body ...)
I like that WebServer is getting more features like providing the body content. The other thing I really wished it had at some point was to allow other HTTP methods (not just GET and POST) like DELETE and PUT (at least) and why not PATCH, HEAD, OPTIONS ? (I know it's out of the scope, I just wanted to let it out :p)

2021-01-28 18:44 UTC, Disinterpreter commented
> 
> 
> hmmm what about `body` instead of `raw` ?
> I don't think raw is meaningful enough as to what it is (could be the raw http request that contains the headers, cookies, body ...)
> I like that WebServer is getting more features like providing the body content. The other thing I really wished it had at some point was to allow other HTTP methods (not just GET and POST) like DELETE and PUT (at least) and why not PATCH, HEAD, OPTIONS ? (I know it's out of the scope, I just wanted to let it out :p)

DELETE/PUT/ETC... It does with ~raw~body. I get it. But as a problem we know nothing about type of request.

2021-01-28 19:34 UTC, Disinterpreter commented
I implemented new method as **method** it return the name of type of request, like GET/POST/PUT...

you can try it with
```
<*
iprint(requestHeaders)
iprint(method)
iprint(raw)
httpSetResponseHeader ( "content-type", "application/json")
httpWrite("ok")
*>
```

2021-01-29 01:04 UTC, Citizen01 requested changes
And I still want it to be named `body`. Here are my arguments:

1. You are exposing the `sBody` attribute of the HttpRequest why not naming it `body` ?
2. `sMethod` is exposed as `method`
3. `headers` list is exposed as `headers`
4. `formData` as `form`, `cookies` as `cookies`, then why `sBody` as `raw` ?
5. I think the `raw` only came from postman ?

2021-01-29 01:04 UTC, Citizen01 commented on Server/mods/deathmatch/logic/CResourceHTMLItem.cpp
> +                break;
```suggestion
            case REQUESTMETHOD_INVALID:
            default:
                sMethod = "INVALID";
                break;
```

2021-01-29 01:08 UTC, Citizen01 commented
I don't think there is a poll system so let's do it like this:

If you want the body to be exposed as `raw`,  react with ❤️ 
If you want the body to be exposed as `body`, react with 🚀

2021-01-29 09:39 UTC, botder commented on Server/mods/deathmatch/logic/CResourceHTMLItem.cpp
> +        std::string sMethod;
```suggestion
        const char* sMethod = "INVALID";
```
Is the heap allocation inside `std::string` really necessary, if you only assign strings from static storage?
With the suggestion you can also simplify the `default` case blow.
`CLuaArguments::PushString` should support pointer to const char.

2021-01-29 09:40 UTC, botder commented
> If you want the body to be exposed as `body`, react with 🚀

What about `requestBody`? That would be analog to `requestHeaders`.

2021-01-29 10:53 UTC, Disinterpreter commented
> 
> 
> > If you want the body to be exposed as `body`, react with 🚀
> 
> What about `requestBody`? That would be analog to `requestHeaders`.

sound fine for me, and I think for @Citizen01 so I did it. And added code suggestions of @botder

2021-01-30 15:54 UTC, botder approved these changes

2021-01-30 19:00 UTC, Citizen01 approved these changes
Tried to brake it sending weird postman requests but everthing I tried worked as expected so it's okay for me too.
Thanks for this PR, this will help me getting back into the API project I had and will simplify the whole thing too ! 👍 🚀

2021-01-31 14:59 UTC, merged