Add event onClientPedStep
multitheftauto/mtasa-blue pull request #212
Opened 2018-06-29 10:26 UTC by CrosRoad95

Type: **Clientside**
Name: **onClientPedStep**
Arguments: `bool foot`
if foot is equal `true` then ped put his left foot, otherwise he put right foot
Usage: Mainaly for sound system, you can detect which material hit foot and play different sounds for grass, sand, rocks etc.
LosFaul also suggested that will be able to make fitness step counter.

Test resource: ( you have to rename events to `onClientPedStep` )
[onPedTakeAStep.zip](https://github.com/multitheftauto/mtasa-blue/files/2148960/onPedTakeAStep.zip)

Player
![event test](https://user-images.githubusercontent.com/22455534/42087760-796ce1f4-7b97-11e8-903f-fc0ff3e9b9cb.png)
Ped
![event test for ped](https://user-images.githubusercontent.com/22455534/42087767-7e1d50bc-7b97-11e8-8be4-3fb5fe80351e.png)

2018-06-29 10:59 UTC, qaisjp commented
Hey - this looks pretty interesting! Well done.

My first comment for improvement would be to merge it into one event: `onClientPedStep`

2018-06-29 15:53 UTC, botder commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +    g_pMultiplayer->SetTakePedAStepHandler(NULL);
Please use **nullptr** and move the line up to the other `g_pMultiplayer->...` lines

2018-06-29 15:53 UTC, botder commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +    m_Events.AddEvent("onClientPedStep", "foot", NULL, false);
Use **nullptr** instead of NULL.

2018-06-29 15:53 UTC, botder commented on Client/multiplayer_sa/CMultiplayerSA.cpp
> +TakeAStepHandler*           m_pTakeAStepHandler = NULL;
Use **nullptr** here.

2018-06-29 15:53 UTC, botder commented on Client/multiplayer_sa/multiplayer_shotsync.cpp
> +DWORD   CONTINUE_CPed_DoFootLanded = 0x5E5386;
Prefix your variable with `static const` to keep the value in this translation unit and constant.

2018-06-29 15:53 UTC, botder commented on Client/multiplayer_sa/multiplayer_shotsync.cpp
> +void HOOK_PedTakeStep(void);
Prefix the function with `static` to keep it in the translation unit ("this .cpp file")

2018-06-29 15:53 UTC, botder commented on Client/sdk/game/CPed.h
> +enum eLandedPedFoot
Not needed?

2018-07-01 02:10 UTC, qaisjp requested changes

2018-07-01 02:10 UTC, qaisjp commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +    g_pMultiplayer->SetTakePedAStepHandler(CClientGame::StaticPedTakeAStepHandler);
`SetPedStepHandler`

2018-07-01 02:10 UTC, qaisjp commented on Client/mods/deathmatch/logic/CClientGame.cpp
> +void CClientGame::PedTakeAStepHandler(CPedSAInterface* pPedSA, bool bFoot)
`PedStepHandler` etc

2018-07-05 12:57 UTC, Jusonex commented
Why do you install the hooks in `multiplayer_shotsync.cpp`?

2018-09-04 20:09 UTC, qaisjp requested changes
Please fix as per Jusonex's comment

2018-10-25 19:15 UTC, merged