Trim keybind whitespace to avoid duplicates
multitheftauto/mtasa-blue pull request #2124
Opened 2021-03-17 12:04 UTC by patrikjuvonen

## Summary
- Trim keybind whitespace to avoid accidental duplicates

2021-03-18 18:48 UTC, Pirulax requested changes, later dismissed

2021-03-18 18:48 UTC, Pirulax commented on Client/core/CKeyBinds.cpp
> +        szCompArguments = strdup(szArguments);
Dont forget to call `free` :)

2021-04-09 17:34 UTC, Pirulax approved these changes
If it works LGTM.

2021-08-04 20:15 UTC, patrikjuvonen commented
Keep an eye out for reports. This may have to be reverted depending on wider user feedback.

2021-08-04 20:15 UTC, merged