Feature/on player weapon given taken
multitheftauto/mtasa-blue pull request #2164
Opened 2021-03-30 23:59 UTC by ricksterhd123

When this PR is merged it should fix #2157.

I would like second thoughts on whether I should add these events for peds as well, for e.g:
onPedWeaponGiven, onPedWeaponTaken, onPedWeaponsTaken because events like onPlayerWeaponSwitch and onPedWeaponSwitch are separate but have the same function signature. Maybe they aren't needed because scripts which do ped stuff generally have checks before giveWeapon/takeWeapon anyway whereas player scripts are more impromptu.

2021-03-31 00:01 UTC, ricksterhd123 commented
> I'm currently working on this to submit a PR
> 
> For giveWeapon:
> onPlayerWeaponGiven, source is a player element, function (weaponID)
> 
> For takeWeapon:
> onPlayerWeaponTaken, source is a player element, function (weaponID)
> 
> For takeAllWeapons
> onPlayerWeaponsTaken, source is a player element, function()

Just to clarify what events are added, this is a comment quoted from the issue

2021-08-20 16:44 UTC, PlatinMTA commented
Does takeAllWeapons() trigger the event by the number of weapons taken or only once?

It should only do it once, you could send a table of weapons taken OR a string saying "all". If you are going the table route, it should always send a table, even when its only one weapon. This could come in handy for knowing what function triggered the event.

2021-08-21 18:16 UTC, ricksterhd123 commented
> 
> 
> Does takeAllWeapons() trigger the event by the number of weapons taken or only once?
> 
> It should only do it once, you could send a table of weapons taken OR a string saying "all". If you are going the table route, it should always send a table, even when its only one weapon. This could come in handy for knowing what function triggered the event.

There's an event called "onPlayerWeaponsTaken", which is triggered before takeAllWeapons() So if you want to know which weapons are taken then you can simply use getPedWeapon and iterate through all weapon slots. There's no need for any params in the event because all weapons are taken, I think it's also cancelable too.

2021-08-21 18:19 UTC, PlatinMTA commented
> There's an event called "onPlayerWeaponsTaken", which is triggered before takeAllWeapons() So if you want to know which weapons are taken then you can simply use getPedWeapon and iterate through all weapon slots. There's no need for any params in the event because all weapons are taken, I think it's also cancelable too.

A use case for knowing which weapons are taken in takeAllWeapons() is to log them using outputServerLog() or any other log system you have in place. It could have some utility apart from logging stuff.

2021-08-21 18:25 UTC, ricksterhd123 commented
> 
> 
> > There's an event called "onPlayerWeaponsTaken", which is triggered before takeAllWeapons() So if you want to know which weapons are taken then you can simply use getPedWeapon and iterate through all weapon slots. There's no need for any params in the event because all weapons are taken, I think it's also cancelable too.
> 
> A use case for knowing which weapons are taken in takeAllWeapons() is to log them using outputServerLog() or any other log system you have in place. It could have some utility apart from logging stuff.

One of the reasons I added this functionality in the first place is that many servers use the default resource 'freeroam' and whenever you want to add new gamemodes that restrict which weapons are given then you will have to use either: export or element data or hardcode into the freeroam resource to check if a certain weapon is given which IMO is a sin. I would rather have an event handler in the gamemode than edit unlrelated resources causing unnecessary dependencies/coupling.

2021-12-06 09:15 UTC, Inder00 requested changes
Events should be generalized to „ped” type and clientside would be also implemented.

2021-12-06 09:15 UTC, Inder00 commented on Server/mods/deathmatch/logic/CGame.cpp
> +    m_Events.AddEvent("onPlayerWeaponsTaken", "", NULL, false);
All event should be generalized and simple as possible. A „onPlayerWeaponsTaken” should be removed and replaced with general event - „onPlayerWeaponToken” to avoid more spaghetti code.

2021-12-06 09:15 UTC, Inder00 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +                    Arguments.PushNumber(ucWeaponID);
Weapon slot and amount of ammo would be nice

2021-12-06 09:15 UTC, Inder00 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +                    CLuaArguments Arguments;
Weapon slot and amount of ammo would be nice

2021-12-06 09:15 UTC, Inder00 commented on Server/mods/deathmatch/logic/CGame.cpp
> +    m_Events.AddEvent("onPlayerWeaponGiven", "weapon", NULL, false);
Generalized event - onPedWeaponGiven

2021-12-06 09:15 UTC, Inder00 commented on Server/mods/deathmatch/logic/CGame.cpp
> +    m_Events.AddEvent("onPlayerWeaponTaken", "weapon", NULL, false);
Generalized event - onPedWeaponTaken

2024-11-06 10:36 UTC, Fernando-A-Rocha commented
PR abandoned

2024-12-31 16:14 UTC, botder commented
If anyone wants to pick up the work and continue it, feel free to.

2024-12-31 16:14 UTC, closed without merging