New optional inputBlocked argument for showChat
multitheftauto/mtasa-blue pull request #2170
Opened 2021-04-01 19:50 UTC by Pieter-Dewachter

A lot of people like to hide the chatbox so they can play without any distractions (eg. during a clanwar, tournament, ...). However there is also the muscle memory of typing commands into the chatbox, or quickly asking a referee for a "free" round. Unfortunately when hiding the chatbox, this also means all input to the chatbox is disabled (messages, but also commands etc.).

This PR adds an extra 'inputBlocked' argument to the existing showChat functions (client- and serverside) which allows to hide the chatbox messages but still keep input to the chatbox possible. The default for this argument is set to true so that existing scripts don't break by this change, but new scripts can implement it if they choose to do so. Also the bitstream changes should be backwards-compatbible as far as I'm aware.

2021-04-01 20:43 UTC, Lpsd requested changes
Just a couple of things. Looks good though, thanks for the PR!

2021-04-01 20:43 UTC, Lpsd commented on Client/core/CChat.h
> +    bool IsInputBlocked() { return m_bInputBlocked; }
```suggestion
    bool IsInputBlocked() const { return m_bInputBlocked; }
```

2021-04-01 20:43 UTC, Lpsd commented on Client/core/CChat.h
> +    bool IsInputVisible() { return !m_bInputBlocked && m_bInputVisible; }
```suggestion
    bool IsInputVisible() const { return !m_bInputBlocked && m_bInputVisible; }
```

2021-04-02 08:13 UTC, Pieter-Dewachter commented
> Just a couple of things. Looks good though, thanks for the PR!

Good catch, I included your suggestions!

2021-04-02 16:14 UTC, Lpsd commented on Client/core/CChat.cpp
> +    }
What if you want to show the chat but block input?

If you do `showChat(true, true)`, the chat is shown but you're still able to type. I don't see any reason why we *shouldn't* allow that.

2021-04-02 16:31 UTC, Lpsd commented
https://github.com/multitheftauto/mtasa-blue/pull/2170/files#diff-d462bfda71f5c318c95adfb0db198ba8bca363376ba084a902fe506f375f236cR779

Both `SetVisible` and `SetInputVisible` methods are currently kind of weird, especially this bit:

```cpp
    if (m_bInputBlocked)
        bVisible = false;
```

It's almost like it's trying to do the job of the Lua function definition code?

The code should be changed to:

```cpp
void CChat::SetVisible(bool bVisible, bool bInputBlocked)
{
    m_bVisible = bVisible;
    SetInputVisible(bInputBlocked);
}

void CChat::SetInputVisible(bool bVisible)
{
    if (!bVisible)
    {
        ClearInput();
        ResetHistoryChanges();
    }

    m_bInputVisible = bVisible;
}
```

We should then upgrade the Lua definitions on both the client and server to use the new parser and make use of `std::optional`, where we can set the `inputBlocked` argument to true by default if the chat is being hidden, and false if it is being shown.

2021-04-11 19:31 UTC, Pieter-Dewachter commented
I have fixed the merge conflicts, suggestions by @Lpsd were added in a previous commit as well.
Would it be possible to have another review?

2021-07-26 17:42 UTC, Lpsd approved these changes

2021-07-26 17:43 UTC, Lpsd commented
completely forgot about this. thanks for your PR. marged

2021-07-26 17:43 UTC, merged

2021-09-21 21:15 UTC, patrikjuvonen commented
Please document isChatInputBlocked on Wiki: https://wiki.multitheftauto.com/index.php?title=IsChatInputBlocked&action=edit&redlink=1

2021-09-22 18:00 UTC, Pieter-Dewachter commented
> Please document isChatInputBlocked on Wiki: https://wiki.multitheftauto.com/index.php?title=IsChatInputBlocked&action=edit&redlink=1

Done!