Refactor of CPlayerManager::IsValidPlayerModel() based on issue #2244
multitheftauto/mtasa-blue pull request #2250
Opened 2021-06-01 01:52 UTC by delinx

Hey, you meant this way of using static array? Let me know if this way of doing it works for you aesthetically, otherwise it behaves exactly the same as original IsValidPlayerModel based on the test I run.

2021-06-01 21:46 UTC, Pirulax requested changes

2021-06-01 21:46 UTC, Pirulax commented on Server/mods/deathmatch/logic/CPlayerManager.cpp
>  }
```suggestion
bool CPlayerManager::IsValidPlayerModel(unsigned short model)
{
    if (model > 312)
        return false; // TODO: On client side maybe check if a model was allocated with engineRequestModel and it is a ped
        
    switch (model)
    {
        case 3:
        case 4:
        case 5:
        case 6:
        case 8:
        case 42:
        case 65:
        case 74:
        case 86:
        case 119:
        case 149:
        case 208:
        case 273:
        case 289:
            return false;
        default:
            return true;
    }
}
```

I think this solution is the cleanest. 
We could add a function that returns an array (on server side a static one (eg.: `std::array<unsigned short, 300>`), on client we'd ideally also include the engineRequestModel ones as well).

2021-06-01 21:46 UTC, Pirulax commented on Server/mods/deathmatch/logic/CPlayerManager.h
> +
```suggestion
```
Merge this together with the above suggestion.

2021-06-01 21:46 UTC, Pirulax commented
I'm not sure if we should fix the client side now as well (as it doesnt include `engineRequestModel` models yet..)

2021-06-01 21:53 UTC, Lpsd commented on Server/mods/deathmatch/logic/CPlayerManager.cpp
>  }
I also prefer this for readability

2021-06-03 09:22 UTC, Lpsd commented
> Also, nearly forgot. I think you have to add this on the client side as well.

The clientside version of `getValidPedModels` uses `CClientPlayerManager::IsValidModel()`, here:

https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/mods/deathmatch/logic/CClientPlayerManager.cpp#L179-L187

Seems fine. The clientside is also already doing a check for models allocated with `engineRequestModel`, inside the `GetValidPedModels` method:

https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/mods/deathmatch/logic/lua/CLuaFunctionDefs.Util.cpp#L29-L36

We should try to also include a check for models allocated with `engineRequestModel` on the serverside too, but that's for another PR imo.

LGTM :shipit:

2021-06-16 23:02 UTC, Pirulax commented
Server-side doesnt yet know about client side models, so.. Theres that.

2021-06-16 23:03 UTC, Pirulax approved these changes
gut

2021-06-16 23:03 UTC, merged

2021-06-16 23:04 UTC, Pirulax commented
Thank you for the PR.