Add engineStreamingGetUsedMemory
multitheftauto/mtasa-blue pull request #2269
Opened 2021-06-19 00:59 UTC by Pirulax

Function for retrieving the amount of memory (in bytes) used by the GTA streamer.

2021-06-19 01:00 UTC, Pirulax commented
Maybe `engineStreamingGetMemoryInUse` is a better name?

2021-06-23 12:10 UTC, AlexTMjugador commented
I'd suggest `engineGetStreamingMemoryUsed`, because most engine functions are of the style `engine` + verb + object, so it's arguably more consistent. But your choice is as good as mine :smile:

2021-06-23 14:44 UTC, Pirulax commented
It is more consistent, but I want to add more streaming functions in the feature, so I thought that placing `streaming` after `engine` might make those functions more consistent.

2021-08-02 15:58 UTC, botder requested changes

2021-08-02 15:58 UTC, botder commented on Client/sdk/game/CStreaming.h
> +    virtual std::uint32_t GetMemoryUsed() = 0;
```suggestion
    virtual std::uint32_t GetMemoryUsed() const = 0;
```

2021-08-02 15:58 UTC, botder commented on Client/game_sa/CStreamingSA.cpp
> +    return *(std::uint32_t*)0x8E4CB4;
```suggestion
    return *reinterpret_cast<std::uint32_t*>(0x8E4CB4);
```

2021-08-02 15:58 UTC, botder commented on Client/game_sa/CStreamingSA.cpp
> +std::uint32_t CStreamingSA::GetMemoryUsed()
```suggestion
std::uint32_t CStreamingSA::GetMemoryUsed() const
```

2021-08-02 15:58 UTC, botder commented on Client/game_sa/CStreamingSA.h
> +    std::uint32_t GetMemoryUsed() override;
```suggestion
    std::uint32_t GetMemoryUsed() const override;
```

2021-08-03 00:24 UTC, botder approved these changes

2021-08-03 00:24 UTC, merged