Add case sensitivity parameter
multitheftauto/mtasa-blue pull request #230
Opened 2018-07-08 08:52 UTC by Dezash

2018-07-09 10:21 UTC, botder commented
Note for reviewer: Account names are case-sensitive by default, but addAccount supports case-insensitivity.

2018-07-09 12:19 UTC, ccw808 commented
If there are two accounts 'bob' and 'BOB', and bob is first in the account database, then getAccount("BOB", nil, true) will return the account for 'bob'

2018-07-09 12:33 UTC, Dezash commented
No it won't.
srun addAccount("bob", "hi", true)
[15:26:23] Console executed command: addAccount("bob", "hi", true)
[15:26:23] Command results: userdata: 075A41F8 [userdata]
srun addAccount("BOB", "hey", true)
[15:26:29] Console executed command: addAccount("BOB", "hey", true)
[15:26:29] Command results: userdata: 075A4400 [userdata]
srun getAccountName(getAccount("BOB", nil, true))
[15:26:54] Console executed command: getAccountName(getAccount("BOB", nil, true))
[15:26:54] Command results: BOB [string]

If you set the third argument to false (case insensitive) then it will return the first match however. Since this is not the default behavior, I think it would be acceptable if a warning in the wiki is added. Returning a table of accounts would make the function much slower so I chose to just return the first result.

2018-07-09 12:48 UTC, Dezash commented
I just looked into it again and noticed that it generates a table anyway so it wouldn't make it slower. Should I make it return a table when caseSensitive is set to false?

2018-07-09 12:53 UTC, ccw808 commented
What about doing a case sensitive search first? If that returns no results then do a case insensitive search

2018-07-09 12:58 UTC, Dezash commented
If there is no case sensitive match, should it return the first case insensitive match or all case insensitive matches?

2018-07-09 13:33 UTC, CrosRoad95 commented
but you can have `bob` and `BOB`, there should be option to get N result, by default return table with all found accounts.

2018-07-09 13:33 UTC, Dezash commented
I think returning a table would be inconsistent. Maybe there should be another function for this or an updated getAccount**s** function that could take a username argument and find all accounts with different case variations.

2018-07-09 13:37 UTC, Citizen01 commented
Something like `findAccounts` could be introduced to prevent braking scripts by changing the returned value type of `getAccount`

2018-07-09 13:43 UTC, Dezash commented
@Citizen01 it wouldn't break any scripts since no scripts use a third argument yet. What I mean is the function name itself screams one account, singular.

2018-07-09 14:04 UTC, Dezash commented
What do devs think?
1. Add username argument getAccounts
2. Implement findAccounts
3. Return a table from getAccount
4. Leave it as it is (returns exact match and if there is no exact match then the first case-insensitive match)
5. Something else???

2018-07-09 14:07 UTC, CrosRoad95 commented
`Implement findAccounts` with regex support :)

2018-07-09 17:31 UTC, ccw808 commented
_4. Leave it as it is (returns exact match and if there is no exact match then the first case-insensitive match)_

Plus the password should be checked during the search as well

2018-07-09 18:26 UTC, ccw808 commented
Just to rewind a bit, when would this feature be used by scripters?

2018-07-09 18:29 UTC, Dezash commented
One use would be to make login panels ignore case, thus reducing the chance of people forgetting their credentials.

2018-07-22 05:27 UTC, qaisjp commented
If `4. Leave it as it is (returns exact match and if there is no exact match then the first case-insensitive match)` is accurate, isn't what you've described already possible? As long as you prevent people from creating accounts with the same casing everything should be OK.

2018-07-22 05:33 UTC, Dezash commented
@qaisjp yes, this was to address servers that use case variations for their account usernames.

2018-07-22 05:37 UTC, qaisjp commented
I see. So you do want to disable the ability to accept case insensitive names because you (e.g) have accounts `James` and `JAMES`, and do not want to confuse users with the ability to log in with `james`?

2018-07-22 05:46 UTC, Dezash commented
No, it is already like that. I want to **add** an ability to accept case insensitive usernames. If the login panel example is too confusing, consider this: you want to add a real-time username availability checking (as user types their username). If there is an account called "JAMES" and user types in "James", getAccount("James") will return false and the script will say that the username is available even though it isn't since case variation is not allowed by that server. By using the feature from this PR you can check whether any case variation of "james" exists and thus return the correct result.

2019-01-02 19:44 UTC, botder requested changes

2019-01-02 19:44 UTC, botder commented on Server/mods/deathmatch/logic/CAccountManager.cpp
> +            return firstMatchAccount != nullptr ? firstMatchAccount : NULL;
Can be reduced to ` return firstMatchAccount;`

2019-01-02 19:44 UTC, botder commented on Server/mods/deathmatch/logic/CAccountManager.cpp
> +            for (uint i = 0; i < results.size(); i++)
Use a range-for loop: `for (CAccount* pAccount : results)`

2019-01-02 19:44 UTC, botder commented on Server/mods/deathmatch/logic/CAccountManager.cpp
> +            CAccount* firstMatchAccount = nullptr;
Prefix this variable with a **p**: `CAccount* pFirstMatchAccount = nullptr;`

2019-01-02 20:38 UTC, qaisjp approved these changes
Please address @botder's review, otherwise, looks good.

2019-01-07 12:55 UTC, merged