Vehicle audio settings
multitheftauto/mtasa-blue pull request #2350
Opened 2021-09-12 10:46 UTC by TheNormalnij

Hi, everybody. It's a old feature, that provide vehicle audio settings interface.
 
```lua
-- All functions are clinet-side
setVehicleModelAudioSetting( vehicle theVehicle, eVehicleSoundSetting parameter, var value ) 
getVehicleModelAudioSetting( vehicle theVehicle, eVehicleSoundSetting parameter )

setVehicleAudioSetting( vehicle theVehicle, eVehicleSoundSetting parameter, var value ) 
getVehicleAudioSetting( vehicle theVehicle, eVehicleSoundSetting parameter )
```
Possible parameters:
* door-sound
* engine-off-soundbank-id
* engine-on-soundbank-id
* horn-high (float)
* horn-ton
* horn-volume-delta (float)
* radion-num
* radio-type
* sound-type
* stereo
* unk3
* unk4
* unk6
* vehicle-type-for-audio

I didn't check this code last time. Maybe it can cause crash with wrong *-soundbank-id parameters

2021-09-12 14:42 UTC, Inder00 commented
What about RC Rider or RC Plane sound ?

2021-09-14 19:21 UTC, Allerek commented
> What about RC Rider or RC Plane sound ?

They're just vehicles like infernus, dodo, jetmax etc, there should not be a problem with those.

2023-04-08 11:42 UTC, patrikjuvonen commented
Merge conflicts must be resolved.

2023-07-14 19:59 UTC, TheNormalnij commented
Merge conflicts solved

2023-12-18 13:48 UTC, Fernando-A-Rocha commented
Nice feature. I think this can be merged. Radio sync (#2781) is a different feature that can be added later.

2024-06-16 00:51 UTC, Dutchman101 commented
@TheNormalnij Please resolve conflicts and see if there's anything you would have done differently if you'd make this feature in 2024

2024-06-16 08:17 UTC, TracerDS requested changes

2024-06-16 08:17 UTC, TracerDS commented on Client/game_sa/CVehicleSA.cpp
> +    }
early return + `using` instead of `typedef` maybe?

2024-06-16 08:17 UTC, TracerDS commented on Client/game_sa/CVehicleSA.h
> +    bool  IsPassenger(CPed* pPed);
`const noexcept`

2024-06-16 08:17 UTC, TracerDS commented on Client/game_sa/CVehicleAudioSettingsEntrySA.h
> +    float             GetHornVolumeDelta() { return m_Settings.m_fHornVolumeDelta; };
`const noexcept` maybe?

2024-06-16 08:17 UTC, TracerDS commented on Client/game_sa/CVehicleAudioSettingsManagerSA.h
> +    uint GetVehicleModelAudioSettingsID(eVehicleTypes eModel);
can be uint32_t?

2024-07-14 12:40 UTC, Fernando-A-Rocha commented
Will it work with allocated model IDs (engineRequestModel) ?

2024-09-01 12:30 UTC, Fernando-A-Rocha commented
Bump?

2024-09-16 16:33 UTC, TheNormalnij commented
> Will it work with allocated model IDs (engineRequestModel) ?

yes

2024-10-08 20:45 UTC, sydu3k commented
Is it still in progress?

2024-10-08 20:48 UTC, Fernando-A-Rocha commented
It would be nice to have this new feature, does it need testing?

2024-10-08 21:02 UTC, sydu3k commented
It seems that there is still some script left to work, that's what I think

2025-01-10 11:13 UTC, tederis commented
I'd love to see it merged. @TheNormalnij please, resolve the conflicts.

2025-02-03 13:34 UTC, Fernando-A-Rocha commented
Works with engine request model ids?

2025-02-03 14:41 UTC, TheNormalnij commented
> Works with engine request model ids?

setVehicleAudioSetting and getVehicleAudioSetting should work with aloocated models.

2025-04-10 21:31 UTC, Dutchman101 commented
Thank you for all the work on this, it will be nice to present for MTA 1.6.1
Please add it to wiki, @TheNormalnij

2025-04-10 21:32 UTC, merged

2025-04-10 21:55 UTC, Fernando-A-Rocha commented
Nice that this got added

2025-04-10 22:03 UTC, Dutchman101 commented
> Nice that this got added

yes, it's huge for MTA

2025-04-10 22:45 UTC, Dutchman101 commented
Also, i didnt see TheNormalnij active so much in recent weeks, it would be better if someone else adds documentation to wiki? Anyone interested?

2025-04-11 06:51 UTC, Xenius97 commented
Works well for me, here is a small snippet if anyone wants to test it:

```lua
local replaceDefaultSoundsEnabled = (type(setVehicleModelAudioSetting) == "function" and true or false)
local customParameters = {
	[478] = getVehicleModelAudioSettings(411) -- # walton <> infernus
}

local possibleValues = {
	["sound-type"] = true, ["engine-on-soundbank-id"] = true, ["engine-off-soundbank-id"] = true, ["bass-setting"] = true, ["bass-eq"] = true, ["field-c"] = true,
	["horn-ton"] = true, ["horn-high"] = true, ["engine-upgrade"] = true, ["door-sound"] = true, ["vehicle-type-for-audio"] = true, ["horn-volume-delta"] = true
}

addEventHandler("onClientResourceStart", resourceRoot, function()
	if not replaceDefaultSoundsEnabled then
		return
	end

	for modelId, values in pairs(customParameters) do
		for key, value in pairs(values) do
			if possibleValues[key] then
				setVehicleModelAudioSetting(modelId, key, value)
			end
		end
	end

	-- # fix streaming after resource start [instantly change sound of vehicle, otherwise you need to use engineRestreamWorld()]
	for _, vehicle in ipairs(getElementsByType("vehicle", root, true)) do
		local model = getElementModel(vehicle)
		if customParameters[model] and replaceDefaultSoundsEnabled then
			local values = customParameters[model]
			for key, value in pairs(values) do
				if possibleValues[key] then
					setVehicleAudioSetting(vehicle, key, value)
				end
			end
		end
	end
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
	if not replaceDefaultSoundsEnabled then
		return
	end
	
	for modelId in pairs(customParameters) do
		resetVehicleModelAudioSettings(modelId)
	end
end)
```

2025-04-11 07:09 UTC, PlatinMTA commented
You broke custom vehicles default sounds, I will open an issue.

2025-07-25 07:12 UTC, Dutchman101 commented
Please document the new features on wiki

Pages don't exist:
https://wiki.multitheftauto.com/wiki/setVehicleModelAudioSetting
https://wiki.multitheftauto.com/wiki/getVehicleModelAudioSettings
https://wiki.multitheftauto.com/wiki/resetVehicleModelAudioSettings
https://wiki.multitheftauto.com/wiki/setVehicleAudioSetting
https://wiki.multitheftauto.com/wiki/getVehicleAudioSettings
https://wiki.multitheftauto.com/wiki/resetVehicleAudioSettings

2025-07-25 07:13 UTC, Dutchman101 commented
Please document the new features on wiki

Pages don't exist:
https://wiki.multitheftauto.com/wiki/setVehicleModelAudioSetting
https://wiki.multitheftauto.com/wiki/getVehicleModelAudioSettings
https://wiki.multitheftauto.com/wiki/resetVehicleModelAudioSettings
https://wiki.multitheftauto.com/wiki/setVehicleAudioSetting
https://wiki.multitheftauto.com/wiki/getVehicleAudioSettings
https://wiki.multitheftauto.com/wiki/resetVehicleAudioSettings

Would be a shame if it saw no use..

2025-07-25 18:04 UTC, MohabCodeX commented
Documented. ✅