Bugfix invalid upgrade component id server-side
multitheftauto/mtasa-blue pull request #2482
Opened 2021-12-25 09:36 UTC by Inder00

The spoiler `1164` cannot be applied to any other vehicle than `Uranus` from server-side.

PoC:
```lua
srun me.vehicle:addUpgrade( 1164 )
```

2021-12-25 09:36 UTC, Inder00 commented
Fixes part of #2476

2021-12-26 16:52 UTC, Inder00 commented
Hold pr until resolve entire issue.

2022-04-09 22:15 UTC, Lpsd commented
I've made a test resource to compare the difference in upgrades for all vehicles between client & server, and vice versa.

[upgrades.zip](https://github.com/multitheftauto/mtasa-blue/files/8457833/upgrades.zip)

for all vehicles:
`/checkserverupgrades` will print a list of upgrades which are available on the server, but not on the client
`/checkclientupgrades` will print a list of upgrades which are available on the client, but not on the server

the lists are written as JSON to a file, `server_output.txt` or client_output.txt`. 

was this PR intended to completely resolve all differences, for all vehicles? because it seems there are still quite a few differences on both sides.

maybe my test resource overlooks something? check it out and let me know

2023-01-01 14:25 UTC, patrikjuvonen commented
Lpsd's comment needs to be addressed.

2023-01-01 17:00 UTC, patrikjuvonen requested changes
Seems to be incorrect. See Lpsd's comment.

2023-08-07 01:25 UTC, closed without merging