HMAC Support
multitheftauto/mtasa-blue pull request #2496
Opened 2022-01-03 11:18 UTC by Inder00

Fixes #2003
This pull request adds **HMAC Support**.

# hmac
```lua
string hmac( string data, string key, string algorithm )
```
Available algorithms: `md5`, `sha1`, `sha224`, `sha256`, `sha384`, `sha512`

To the moon 🚀

2022-01-03 23:56 UTC, Breaker59 commented
❤️

2022-01-04 00:51 UTC, Inder00 commented
I’ll refactor that feature to `encodeString` - https://github.com/multitheftauto/mtasa-blue/issues/2003#issuecomment-761828782

2022-01-05 13:02 UTC, Pieter-Dewachter commented
Maybe I am nitpicking here - or misunderstanding, but I feel like _encodeString_ is not the right function for HMAC.
Personally I think it makes more sense to add it as an option to the existing _hash_ function instead.

The current MTA standard seems to be as follows:
- _encodeString_ is used for ciphers (TEA and AES128 currently), which can be decoded if you have the correct key / info.
- _hash_ is used for hashes (unbelievable!), which means that you cannot go back to the input data (no decoding counterpart)

I think a syntax as follows would be quite nice: _hash ( string algorithm, string dataToHash [, table options ] )_
- New algorithms could be: "hmac-md5", "hmac-sha1", "hmac-sha224", "hmac-sha256", "hmac-sha384", "hmac-sha512"
- The new _options_ table is only needed for the HMAC algorithms as follows: _{ key = "secret" }_

2022-01-05 18:24 UTC, Inder00 commented
> Maybe I am nitpicking here - or misunderstanding, but I feel like _encodeString_ is not the right function for HMAC. Personally I think it makes more sense to add it as an option to the existing _hash_ function instead.
> 
> The current MTA standard seems to be as follows:
> 
> * _encodeString_ is used for ciphers (TEA and AES128 currently), which can be decoded if you have the correct key / info.
> * _hash_ is used for hashes (unbelievable!), which means that you cannot go back to the input data (no decoding counterpart)
> 
> I think a syntax as follows would be quite nice: _hash ( string algorithm, string dataToHash [, table options ] )_
> 
> * New algorithms could be: "hmac-md5", "hmac-sha1", "hmac-sha224", "hmac-sha256", "hmac-sha384", "hmac-sha512"
> * The new _options_ table is only needed for the HMAC algorithms as follows: _{ key = "secret" }_

However, in my opinion, we should work on encode/decodeString as much as possible. This is a good strategy to make it easier to add new features and for scripters to use them.
Big guys should decide that - @sbx320 @botder @Pirulax

2022-01-06 11:52 UTC, AlexTMjugador commented
HMAC is defined as successive applications of a hash function to the message, mixing that with a secret key to provide authentication, so the argument that it's a hash function after all makes sense. However, I think that the `encodeString` function is named generically enough so that HMAC fits in there (and in fact so do more traditional hash functions such as MD5 or SHA). From Wikipedia:

> In communications and information processing, code is a system of rules to convert information—such as a letter, word, sound, image, or gesture—into another form, sometimes shortened or secret, for communication through a communication channel or storage in a storage medium.

If `encodeString` is easier to maintain, I don't see a strong reason why not favor that function for new additions.

2022-01-12 11:46 UTC, Pirulax commented
IMHO we should just be consistent. 
Up to this point `encodeString` has only ciphers added to it. So let's continue that trend, and add only ciphers to it, while `hash` has the hashing functions.

2022-01-12 17:18 UTC, Inder00 commented
So far I have done 3 versions of the hmac implementation.
Implmenetation under the hash function (most relevant to hmac) has been rewritten under a new parser argument.
Please give me feedback which implementation is the most suitable.

1. hmac function (https://github.com/multitheftauto/mtasa-blue/pull/2496/commits/30aefdb197e0b5f7472ba4d46bb20cb1fcad6492)
```lua
string hmac( string data, string key, string algorithm )
```

2. encodeString function (https://github.com/multitheftauto/mtasa-blue/pull/2496/commits/47f336aff790c7866df2468b1305af6a6fc2212b)
```lua
string encodeString( "hmac", string data, array options { string key, string algorithm }, [ function callback ] )
```

3. hash function (https://github.com/multitheftauto/mtasa-blue/pull/2496/commits/0862a4cf30d3a00c70456a67efe5ca566ae80b81)
```lua
string hash("hmac", string data, array options { string key, string algorithm } )
```

2022-01-12 17:57 UTC, Inder00 commented
I'll also add that the cryptographic functions (md5, sha1, and derivatives...) on Linux returned the hash in lowercase, while on Windows in uppercase.
Refactoring the hash function can cause problems.

Linux needs to be tested ⏰

2022-01-22 17:36 UTC, Pirulax commented
I prefer the `hash` one.

2022-09-22 09:27 UTC, botder requested changes

2022-09-22 09:27 UTC, botder commented on Shared/sdk/SharedUtil.Hash.h
> +    SHA512
```suggestion
    SHA512,
```

2022-09-22 09:27 UTC, botder commented on Shared/sdk/SharedUtil.Hash.h
> +    RSA
```suggestion
    RSA,
```

2022-09-22 09:27 UTC, botder commented on Shared/sdk/SharedUtil.Hash.h
> +    HMAC
```suggestion
    HMAC,
```

2022-09-22 09:27 UTC, botder commented on Shared/sdk/SharedUtil.Hash.h
> +        SHA512
```suggestion
        SHA512,
```

2022-09-22 09:27 UTC, botder commented on Shared/sdk/SharedUtil.Crypto.h
> +        CryptoPP::HMAC<HmacType> hmac((CryptoPP::byte*)key.c_str(), key.size());
```suggestion
        CryptoPP::HMAC<HmacType> hmac(reinterpret_cast<CryptoPP::byte*>(key.c_str()), key.size());
```

2022-09-22 09:27 UTC, botder commented on Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp
> +        {"hash", ArgumentParser<Hash>},
```suggestion
        {"hash", ArgumentParserWarn<false, Hash>},
```

2022-09-22 09:27 UTC, botder commented on Shared/mods/deathmatch/logic/luadefs/CLuaCryptDefs.cpp
> +    catch(std::exception& ex)
```suggestion
    catch (std::exception& ex)
```

2022-09-22 09:29 UTC, botder submitted a review, later dismissed

2022-09-22 10:37 UTC, botder commented on Shared/sdk/SharedUtil.Crypto.h
> +        CryptoPP::HMAC<HmacType> hmac(reinterpret_cast<CryptoPP::byte*>(key.c_str()), key.size());
```suggestion
        CryptoPP::HMAC<HmacType> hmac(reinterpret_cast<const CryptoPP::byte*>(key.c_str()), key.size());
```

2022-09-22 11:32 UTC, merged