Add new world special property (corona ztest)
multitheftauto/mtasa-blue pull request #2529
Opened 2022-01-26 12:19 UTC by gta191977649

### Introduction
This PR adds the ability to toggle the corona z-testing in the engine, brings the possibility to create the ps2 classical big sun glare effect (when z test is disabled), more detail can be found in [here](https://youtu.be/EnvAASQ2els?t=1287)
![show](https://user-images.githubusercontent.com/2988235/151159098-74d5d1bd-162a-4db1-ba81-f042e26437aa.png)
### Summary
- This effect is `enabled` by default, keeping consistent with the SA PC version
- new propname: `coronaztest` is added into the world function, you can set it on or off like other world properties. this includes `setWorldSpecialPropertyEnabled`, `isWorldSpecialPropertyEnabled`
### Sample Useage:
- Enable: `setWorldSpecialPropertyEnabled("coronaztest",true) `
- Disable: `setWorldSpecialPropertyEnabled("coronaztest",false) `
### Test Resource
- command `/ztest (on/off)` to toogle the effect
[coronaztest.zip](https://github.com/multitheftauto/mtasa-blue/files/7941601/coronaztest.zip)

2022-01-30 02:00 UTC, Einheit-101 commented
Woah nice, is it possible to port other features of SkyGFX into SA? Like dual pass Alpha rendering to fix the ugly Alpha channels or grassFixPlacement?

2022-01-30 10:17 UTC, gta191977649 commented
> Woah nice, is it possible to port other features of SkyGFX into SA? Like dual-pass Alpha rendering to fix the ugly Alpha channels or grassFixPlacement?

yeah, I'm working on that at moment, the point is trying to port it as much as I can without touching much of MTA's client code.
but some engine related data might need some extract effort to re-create under the Lua script.
if you interested, it's in [here](https://github.com/gta191977649/MTASA-SkyGfx). :p

2022-04-08 17:12 UTC, gta191977649 commented
Ready for review.

2022-09-11 15:03 UTC, botder requested changes

2022-09-11 15:03 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +    m_bCoronaZTest = true;
```suggestion
```

2022-09-11 15:03 UTC, botder commented on Client/game_sa/CGameSA.h
> +    bool         m_bCoronaZTest;
```suggestion
    bool         m_isCoronaZTestEnabled{true};
```

2022-09-11 15:03 UTC, botder commented on Client/game_sa/CGameSA.h
> +    bool IsCoronaZTestEnabled();
```suggestion
    void SetCoronaZTestEnabled(bool isEnabled);
    bool IsCoronaZTestEnabled() const noexcept { return m_isCoronaZTestEnabled; }
```

2022-09-11 15:03 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +
```suggestion
void CGameSA::SetCoronaZTestEnabled(bool isEnabled)
{
    if (m_isCoronaZTestEnabled == isEnabled)
        return;

    if (isEnabled)
    {
        // Enable ZTest (PC)
        MemPut<BYTE>(0x6FB17C + 0, 0xFF);
        MemPut<BYTE>(0x6FB17C + 1, 0x51);
        MemPut<BYTE>(0x6FB17C + 2, 0x20);
    }
    else
    {
        // Disable ZTest (PS2)
        MemSet((void*)0x6FB17C, 0x90, 3);
    }
    
    m_isCoronaZTestEnabled = isEnabled;
}

```

2022-09-11 15:03 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +
```suggestion
```

2022-09-11 15:05 UTC, botder requested changes

2022-09-11 15:05 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +
```suggestion
    if (!strcmp(szCheatName, PROP_CORONA_ZTEST))
        return IsCoronaZTestEnabled();
 
```

2022-09-11 15:05 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +
```suggestion
```

2022-09-11 15:05 UTC, botder commented on Client/game_sa/CGameSA.cpp
>      CVehicleSA::SetVehiclesSunGlareEnabled(false);
```suggestion
    CVehicleSA::SetVehiclesSunGlareEnabled(false);

```

2022-09-11 17:08 UTC, botder approved these changes

2022-09-11 17:09 UTC, merged