Improve setSoundEffectParameters error messages
multitheftauto/mtasa-blue pull request #2552
Opened 2022-02-17 19:46 UTC by Pirulax

Right now, if anything goes wrong in BASS a very weird error message is given:
![image](https://user-images.githubusercontent.com/12902714/154558622-15658f69-64bd-4c78-bb62-fc42575b44da.png)

Now, instead it displays a pretty useful one:
![image](https://user-images.githubusercontent.com/12902714/154558699-9635c6fe-d611-4f17-96ea-9b1075c27c67.png)

But there's a catch.. `luaL_error` straight out crashes when I call it with a format string that has strings in it. I tested the feature by replacing `luaL_error` with  `m_pScriptDebugging->LogError` (which btw uses format string, but works fine..)

Now, there's ~~3~~ 4 options:
- Fix `luaL_error`
- Use `sprintf`
- Use `SString` to construct it
- Upgrade to C++20 and use `std::format` :D

Also, now it hard errors if the effect wasn't enabled (currently it only returns false, but we should hard error on usage mistakes) with the following message:
`Effect's parameters can't be set unless it's enabled"`

2022-02-17 19:56 UTC, Pirulax commented
`luaL_error` workaround added. I can't be bothered to fix it.
Good enough for now.
Let's get this merged fast, it's a pretty nice QoL [enhancement](https://github.com/multitheftauto/mtasa-blue/labels/enhancement).

2022-02-17 22:10 UTC, Lpsd commented
I did already reply on Discord, but your `luaL_error` crash is likely due to using `%i` instead of `%d` for int, see [here](https://www.lua.org/manual/5.3/manual.html#luaL_error) (and [here](https://www.lua.org/manual/5.3/manual.html#lua_pushfstring))

2022-02-18 12:55 UTC, Pirulax commented
Well, thank you very much!

2022-09-11 17:40 UTC, botder requested changes

2022-09-11 17:40 UTC, botder commented on Client/mods/deathmatch/logic/CBassAudio.cpp
> +        return "Unknown error - `CBassAudio::ErrorGetMessage` should be updated to return a message for it!";
```suggestion
        return "unknown error (?)";
```

2022-09-11 17:40 UTC, botder commented on Client/mods/deathmatch/logic/CBassAudio.h
> +    static int         ErrorGetCode();
```suggestion
    // Retrieves the error message for the most recent BASS function call in the current thread.
    static const char* ErrorGetMessage();

    // Retrieves the error code for the most recent BASS function call in the current thread.
    static int ErrorGetCode();
```

2022-09-11 17:40 UTC, botder commented on Client/mods/deathmatch/logic/CBassAudio.cpp
> +    // new error code that has to be added here
```suggestion
    // BASS may add new error codes in the future, which must be appended to the switch above.
    // Also, add-ons may introduce additional error codes.
```

2022-09-11 17:40 UTC, botder commented on Client/mods/deathmatch/logic/CBassAudio.cpp
> +// Just a wrapper
```suggestion
```

2022-09-11 17:40 UTC, botder commented on Client/mods/deathmatch/logic/luadefs/CLuaAudioDefs.cpp
> +    // Hard error on usage mistake
```suggestion
```

2022-09-11 17:42 UTC, botder approved these changes

2022-09-11 23:34 UTC, merged