Updating User agent for youtube.com/tv
multitheftauto/mtasa-blue pull request #2638
Opened 2022-06-03 19:34 UTC by MrSol0

Youtube has once again changed their platform so it no longer supports video resume for most user agents, however roku user agent seems to still work fine with no problems similar to the old user agent.

Before you go ahead and create a pull request, please make sure:

* [ ] [your code follows the coding guidelines](https://wiki.multitheftauto.com/index.php?title=Coding_guidelines)
* [ ] your commit messages are informative ("update file.cpp" is unhelpful. "fix missing model in getVehicleNameFromModel" is helpful)

If your work is incomplete, **do not prefix your pull request with "WIP"**, instead
create a _draft_ pull request: https://github.blog/2019-02-14-introducing-draft-pull-requests/

Thank you!

2022-06-05 10:05 UTC, ffsPLASMA commented
Wouldn't it be much more beneficial to set the browser user agent to a custom one via lua in conjunction with setBrowserProperty rather than hardcoding it?

2022-06-05 10:38 UTC, patrikjuvonen commented
> Wouldn't it be much more beneficial to set the browser user agent to a custom one via lua in conjunction with setBrowserProperty rather than hardcoding it?

It's set by MTA to respect the purpose of user agent header. It is used occasionally by ISPs and services to better route traffic. There isn't any reason to use any other custom user agent than what MTA provides. In this case a part is added which is needed to workaround automatic routing on YouTube. There may be other issues that we don't realize by allowing custom user agents. So for now, no, we're not going to change this behavior.

I'll also need to ask people to stop discussing this in this pull request, because it is off-topic. Please talk over in a new issue or discussion.

2022-06-13 22:01 UTC, theSarrum commented on Client/cefweb/CWebView.cpp
> +                iter->second = iter->second.ToString() + "; Roku 3/7.0";
Using "Roku 3/7.0" is not enough, so I tried it out and found that we could add "Wireless" and it works.
```suggestion
                iter->second = iter->second.ToString() + "; Roku 3/7.0, Wireless";
```

2022-07-05 22:02 UTC, lopezloo commented
Doesn't work for me. Neither current UA, `Roku 3/7.0` nor `Roku 3/7.0, Wireless`. I'm getting "who's watching?" screen on youtube.com/tv.

The URL I have used:
```
https://www.youtube.com/tv#/watch?mode=transport&v=jofNR_WkoCE
```

2022-07-05 22:03 UTC, lopezloo requested changes
Doesn't work for me. Neither current UA, `Roku 3/7.0` nor `Roku 3/7.0, Wireless`. I'm getting "who's watching?" screen on `youtube.com/tv`.

The URL I have used:
```
https://www.youtube.com/tv#/watch?mode=transport&v=jofNR_WkoCE
```

Please provide the URL you have used and/or reproduction code.

2022-07-06 09:45 UTC, MrSol0 commented
> Current user agent works for me. Please provide more information about this issue.

Youtube has restored their old system, the resume is now back again, however i still think "Roku 3/7.0" is better because it has no login page when you resume or watch videos.

2022-07-06 17:00 UTC, lopezloo commented
> > Current user agent works for me. Please provide more information about this issue.
> 
> Youtube has restored their old system, the resume is now back again, however i still think "Roku 3/7.0" is better because it has no login page when you resume or watch videos and even no ads!

I still see ads with `Roku 3/7.0` UA. What do you mean by saying "resuming" videos and "login page"?

If I visit video URL directly, ex. this one:
```
https://www.youtube.com/tv#/watch?mode=transport&v=jofNR_WkoCE
```

I'm getting "who's watching?" page on all user agents.

2022-07-06 21:04 UTC, MrSol0 commented
> https://www.youtube.com/tv#/watch?mode=transport&v=jofNR_WkoCE

i have tested `https://www.youtube.com/tv#/watch?v=jofNR_WkoCE` with user agent as `Roku 3/7.0` in chrome and i don't see the who's watching page, and i mean by resume video this `https://www.youtube.com/tv#/watch?v=jofNR_WkoCE&resume&t=120` as an example, it tells you who's watching with other user agents but not with Roku

2022-07-06 22:45 UTC, lopezloo commented
I'm getting this login page even with `Roku 3/7.0` UA.

2022-07-07 06:35 UTC, MrSol0 commented
> I'm getting this login page even with `Roku 3/7.0, Wireless` UA. Without `Wireless` I got redirect to desktop version.

It seems like you are using the wrong user agent changer, try use user-agent changer and manager which is a chrome extension. i would also like anyone else to confirm this.

2022-07-07 08:39 UTC, Lpsd commented
> > I'm getting this login page even with `Roku 3/7.0, Wireless` UA. Without `Wireless` I got redirect to desktop version.
> 
> It seems like you are using the wrong user agent changer, try use user-agent changer and manager which is a chrome extension. i would also like anyone else to confirm this.

Why are you using a Chrome extension for testing this? How can you be sure the request details are exactly the same as in MTA? If you've already accounted for this can you prove it?

2022-07-07 09:48 UTC, patrikjuvonen commented
Testing must be done through the MTA client, not external browser.

2022-07-07 10:05 UTC, Lpsd commented
It's also worth noting that YouTube generally rolls out their updates/changes slowly, so different users may have different experiences while performing the same actions. This could be down to browser, device, location, IP, account, and many other variables.

2022-09-20 04:49 UTC, closed without merging