Improve performance of CClientObjectManager::UpdateLimitInfo
multitheftauto/mtasa-blue pull request #2706
Opened 2022-08-09 21:53 UTC by Merlin

This improves the performance of CClientObjectManager::UpdateLimitInfo.
I measured with SharedUtil::GetTimeUs and it consistenly took 212 microseconds for these 3 calls.
It is called every frame and also whenever a object is streamed in or out.

Instead of calling these functions I hooked the pool functions that add and remove them and now keep track of the amount of used spaces in a separate variable.

Now it only takes 0-1 microseconds.

2022-08-15 21:26 UTC, Pirulax commented
I don't think that will work, because sometimes the delete operator is inlined.

2022-08-16 02:29 UTC, Merlin commented
I also patched all places that got inlined. There is also some test code left in a comment for whoever reviews this that can be used to check if the values match.

2022-09-10 16:03 UTC, botder requested changes

2022-09-10 16:03 UTC, botder commented on Client/sdk/multiplayer/CMultiplayer.h
> +    virtual unsigned int PtrNodeDoubleLinkPool_NoOfUsedSpaces() = 0;
```suggestion
    virtual unsigned int EntryInfoNodePool_NoOfUsedSpaces() const noexcept = 0;
    virtual unsigned int PtrNodeSingleLinkPool_NoOfUsedSpaces() const noexcept = 0;
    virtual unsigned int PtrNodeDoubleLinkPool_NoOfUsedSpaces() const noexcept = 0;
```

2022-09-10 16:03 UTC, botder commented on Client/multiplayer_sa/CMultiplayerSA_ObjectStreamerOptimization.cpp
> +}
```suggestion
unsigned int CMultiplayerSA::EntryInfoNodePool_NoOfUsedSpaces() const noexcept
{
    return CEntryInfoNodePool_UsedSpaces;
}

unsigned int CMultiplayerSA::PtrNodeSingleLinkPool_NoOfUsedSpaces() const noexcept
{
    return CPtrNodeSingleLinkPool_UsedSpaces;
}

unsigned int CMultiplayerSA::PtrNodeDoubleLinkPool_NoOfUsedSpaces() const noexcept
{
    return CPtrNodeDoubleLinkPool_UsedSpaces;
}
```

2022-09-10 16:03 UTC, botder commented on Client/multiplayer_sa/CMultiplayerSA.h
> +    unsigned int PtrNodeDoubleLinkPool_NoOfUsedSpaces();
```suggestion
    unsigned int EntryInfoNodePool_NoOfUsedSpaces() const noexcept override;
    unsigned int PtrNodeSingleLinkPool_NoOfUsedSpaces() const noexcept override;
    unsigned int PtrNodeDoubleLinkPool_NoOfUsedSpaces() const noexcept override;
```

2022-09-10 17:37 UTC, botder approved these changes

2022-09-10 17:37 UTC, merged