Add engineReinitMarkers()
multitheftauto/mtasa-blue pull request #2794
Opened 2022-10-20 16:57 UTC by TFP-dev

This function will reinit 3D markers. This can be useful if you want to replace marker 3D model. Fixes closed issue #2213.

**API:**
`engineReinitMarkers()`

**Test resource:** 
This resource replaces "arrow" marker and adds command `reinitMarkers`.
[marker_test_resource.zip](https://github.com/multitheftauto/mtasa-blue/files/9832216/marker_test_resource.zip)

**Screenshot:**
![comp](https://user-images.githubusercontent.com/72511827/197010131-254a9133-b55a-4fd3-809d-80fa0c35521a.png)

2022-10-22 05:09 UTC, CrosRoad95 commented
"marker 3D model."
so, make if you replace 3d model -> call "engineReinitMarkers", we don't use "reinitVehicles", "reinitObjects" ect after element will be replaced

2022-10-22 09:01 UTC, TFP-dev commented
> ". This can be useful if you want to replace marker 3D model." so, make if you replace 3d model of marker -> call "engineReinitMarkers", we don't use "reinitVehicles", "reinitObjects" ect after element will be replaced

But we use `engineRestreamWorld`. Currently servers can use fact that you can't replace marker model so `engineReinitMarkers` is backwards compatible.

2022-10-22 09:44 UTC, CrosRoad95 commented
you actually fixing a bug, everyone will happy if suddenly markers will work as intended

2022-10-22 15:09 UTC, TFP-dev commented
> you actually fixing a bug, everyone will happy if suddenly markers will work as intended

Check issue #2213

2022-10-22 22:42 UTC, lopezloo commented
This issue applies to `cylinder` markers too, right?

2022-10-24 13:51 UTC, sbx320 reviewed
Wouldn't it be more useful to apply this whenever we replac a marker model? That way scripters wouldn't need to work around it.

2022-10-24 14:18 UTC, TFP-dev commented
> Wouldn't it be more useful to apply this whenever we replac a marker model? That way scripters wouldn't need to work around it.

Currently you can use fact that you can't replace markers, for example you can replace id 1559 with the building model and use it instead of allocating new model id with `engineRequestModel` and markers will stay intact.

2022-10-24 14:59 UTC, sbx320 requested changes, later dismissed
Some minor comments regarding argparser usage

2022-10-24 14:59 UTC, sbx320 commented on Client/game_sa/C3DMarkersSA.cpp
> +    typedef int(__cdecl * Function_ShutdownMarkers)();
Should be using rather than typedef

2022-10-24 14:59 UTC, sbx320 commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
> +bool CLuaEngineDefs::EngineReinitMarkers(lua_State* const luaVM)
No need to return a bool here, if it's always `true`. Also if the lua_State* arg isn't used, it doesn't need to be specified. 

The argparse can handle `void [func]()`.

2023-05-19 15:29 UTC, lopezloo commented
> Wouldn't it be more useful to apply this whenever we replac a marker model? That way scripters wouldn't need to work around it.

Maybe that could be implemented and documented as 1.6 backwards incompatible change.

2023-09-19 20:10 UTC, botder commented
Superseded by pull request #3059.

2023-09-19 20:10 UTC, closed without merging