Add gui combobox missing functions
multitheftauto/mtasa-blue pull request #280
Opened 2018-07-29 17:52 UTC by FileEX

**Syntax**
```lua
int guiComboBoxGetItemCount(element theElement)
bool guiComboBoxSetState(element theElement, int state)
int guiComboBoxGetState(element theElement)
```

guiComboBoxGetState return 1 if combobox is 'open' and return 2 if is closed.
guiComboBoxSetState if state = 1 combobox will be open if state == 2 combobox will be close

2018-07-31 15:31 UTC, jushar requested changes

2018-07-31 15:31 UTC, Jusonex commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        if (IS_GUI(&Entity))
Please fix the indentation here and below.

2018-07-31 15:31 UTC, Jusonex commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> +    argStream.ReadNumber(state);
I'd personally prefer an enum string here (and ofc return a string in `guiComboxGetState`). I'd like to hear other opinions though.

**Or, an even better solution - as you only distinguish two states - is to rename the function to `guiComboxIsOpen` and make it return a _boolean_.**

2018-07-31 15:31 UTC, Jusonex commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +            int comboState;
Tip: Try reducing the scope of variables as much as possible, i.e. move `comboState` into the if block or avoid creating it entirely by directly returning from the `vs` / `!vs` - if blocks.

2018-07-31 16:31 UTC, FileEX commented
Everything fixed

2018-08-29 03:42 UTC, qaisjp requested changes

2018-08-29 03:42 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    RUN_CHILDREN(GUIComboBoxGetItemCount(**iter))
RUN_CHILDREN is unnecessary in Get methods

2018-08-29 03:42 UTC, qaisjp commented on Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +    RUN_CHILDREN(GUIComboBoxIsOpen(**iter))
As above, RUN_CHILDREN is unnecessary in Get methods

2018-08-29 03:42 UTC, qaisjp commented on Client/gui/CGUIComboBox_Impl.cpp
> +bool CGUIComboBox_Impl::GetState(void)
Should be renamed to IsOpen

2018-09-04 15:14 UTC, patrikjuvonen commented
@qaisjp @Jusonex What's the status on these reviews?

2018-09-22 18:19 UTC, merged