Add missing skin 313(BB.dff)
multitheftauto/mtasa-blue pull request #2808
Opened 2022-11-02 01:09 UTC by Allerek

Adding missing skin.
I think i did everything, skins works just fine(not a cutscene model, present in gta3.img)
Tested few animations.
![image](https://user-images.githubusercontent.com/12304071/199371118-bfad7e02-3f08-4e12-81ee-99a712a38a90.png)

2022-11-02 13:31 UTC, Allerek commented
![image](https://user-images.githubusercontent.com/12304071/199502379-83fbf8f4-8047-4d96-b88c-0ae556c8a937.png)
Bone count seems fine to me, so its not a cutscene model

2022-11-02 15:18 UTC, Allerek commented
Some of the skins have bugged textures, or they're just ugly - but they should be available within MTA.

2022-11-02 15:20 UTC, Allerek commented
![image](https://user-images.githubusercontent.com/12304071/199528722-a11d8c30-521b-468f-b6d8-9468adb8e20e.png)
![image](https://user-images.githubusercontent.com/12304071/199528748-d6a624f8-4ae2-43a3-98c7-11f5084c2261.png)
![image](https://user-images.githubusercontent.com/12304071/199528786-3e0ccb5e-b501-4ab2-8caa-e3295fd2f05f.png)
![image](https://user-images.githubusercontent.com/12304071/199528819-42c9caa9-f2e3-4901-9c7b-e56a35716cc5.png)
![image](https://user-images.githubusercontent.com/12304071/199528860-2d812344-cfe7-438d-8fd1-4a9eb2d7f099.png)
![image](https://user-images.githubusercontent.com/12304071/199528902-18c34581-c619-42f4-abae-b3ed27ee87ec.png)
![image](https://user-images.githubusercontent.com/12304071/199528951-ec71fb03-364e-4f37-9102-9a0065453378.png)
![image](https://user-images.githubusercontent.com/12304071/199528987-96784771-24df-4a72-943d-35d2a83da0b5.png)
![image](https://user-images.githubusercontent.com/12304071/199529012-41a81afd-07ad-4150-b72a-178eb74a06a1.png)

2022-11-14 19:49 UTC, TheNormalnij commented
![image](https://user-images.githubusercontent.com/6773493/201751509-55944210-9571-4326-9f54-a567147857e9.png)
Thanks you! What about [remaining](https://tcrf.net/Grand_Theft_Auto:_San_Andreas/Unused_Characters) ped models?

For next your PR create new branch from master.

2022-11-14 21:59 UTC, Allerek commented
> ![image](https://user-images.githubusercontent.com/6773493/201751509-55944210-9571-4326-9f54-a567147857e9.png) Thanks you! What about [remaining](https://tcrf.net/Grand_Theft_Auto:_San_Andreas/Unused_Characters) ped models?
> 
> For next your PR create new branch from master.

Rest of them have incorrect bone counts which may break animations or cause crashes
![image](https://user-images.githubusercontent.com/12304071/201776842-0795ad97-a991-408c-9df5-7d0ebbb329ef.png)

2023-01-01 12:49 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientModelCacheManager.cpp
> +        if (usModelId < 1 || usModelId > 313)
Why was the max changed from 312 to 313?

2023-01-01 12:49 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/CClientModelCacheManager.cpp
> +        if (usModelId < 1 || usModelId > 313)
Why was the max changed from 312 to 313?

2023-01-01 12:56 UTC, patrikjuvonen requested changes

2023-01-01 12:56 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CPlayerManager.cpp
>          case 273:
273 and 289 should also be removed.

2023-01-02 11:56 UTC, Allerek commented
[skins-test.zip](https://github.com/multitheftauto/mtasa-blue/files/10331355/skins-test.zip)
test resource.

!Important note! - Map editor resource needs new ped ID's added(F1 most likely too)

2023-01-02 12:36 UTC, patrikjuvonen approved these changes
Thanks!

2023-02-01 23:10 UTC, Fernando-A-Rocha commented
I think the smoke with bloody vest skin was forgotten.

Comparison: cssmokevest VS cssmokevest2 (found in custscene.img)

![img](https://i.imgur.com/Sfoux1Q.png)

2023-02-08 19:57 UTC, Allerek commented
> I think the smoke with bloody vest skin was forgotten.
> 
> Comparison: cssmokevest VS cssmokevest2 (found in custscene.img)
> 
> ![img](https://camo.githubusercontent.com/8bb0f6b7717f53bebc79a50e791677e5cad7b3bb60bbcaa0a7e9766996994591/68747470733a2f2f692e696d6775722e636f6d2f53666f757831512e706e67)

We do not support cutscene skins.

2023-04-07 18:39 UTC, merged