Add new world special property (water creatures)
multitheftauto/mtasa-blue pull request #3033
Opened 2023-05-23 19:36 UTC by samr46

From stale PR #276

Adds new property for [setWorldSpecialPropertyEnabled](https://wiki.multitheftauto.com/wiki/SetWorldSpecialPropertyEnabled):

**watercreatures** - toggle randomly created water creatures (default: true) ([picture](https://i.imgur.com/v3PYmIF.jpg))

Previously refactored / reviewed by @TheNormalnij

2023-07-18 18:15 UTC, TheNormalnij approved these changes, later dismissed

2023-07-18 18:15 UTC, TheNormalnij commented
LGTM

2023-07-26 09:38 UTC, botder requested changes

2023-07-26 09:38 UTC, botder commented on Client/game_sa/CGameSA.h
> +    bool         m_bWaterCreatures{true};
```suggestion
    bool         m_areWaterCreaturesEnabled{true};
```

2023-07-26 09:38 UTC, botder commented on Client/game_sa/CGameSA.h
> +    bool IsWaterCreaturesEnabled();
```suggestion
    bool IsWaterCreaturesEnabled() const noexcept { return m_areWaterCreaturesEnabled; }
```

2023-07-26 09:38 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +void CGameSA::SetWaterCreaturesEnabled(bool bEnabled)
```suggestion
void CGameSA::SetWaterCreaturesEnabled(bool isEnabled)
```

2023-07-26 09:38 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +    if (bEnabled == m_bWaterCreatures)
```suggestion
    if (isEnabled == m_areWaterCreaturesEnabled)
```

2023-07-26 09:38 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +    (Func_t(bEnabled ? 0x6E3F90 : 0x6E3FD0))((void*)0xC1DF30);            // Init/Deinit WaterCreateManager
```suggestion
    const auto manager = reinterpret_cast<class WaterCreatureManager_c*>(0xC1DF30);

    if (isEnabled)
    {
        unsigned char(__thiscall * Init)(WaterCreatureManager_c*) = reinterpret_cast<decltype(Init)>(0x6E3F90);
        Init(manager);
    }
    else
    {
        void(__thiscall * Exit)(WaterCreatureManager_c*) = reinterpret_cast<decltype(Exit)>(0x6E3FD0);
        Exit(manager);
    }
```

2023-07-26 09:38 UTC, botder commented on Client/game_sa/CGameSA.cpp
> +    m_bWaterCreatures = bEnabled;
```suggestion
    m_areWaterCreaturesEnabled = isEnabled;
```

2023-08-01 17:27 UTC, botder approved these changes

2023-08-01 17:28 UTC, merged