Add support for double click events in CEF
multitheftauto/mtasa-blue pull request #3040
Opened 2023-05-24 23:16 UTC by Lpsd

Resolves #2963

As mentioned in the issue description above, double click events previously weren't being sent to CEF.

Test resource: 
[cef.zip](https://github.com/multitheftauto/mtasa-blue/files/11559836/cef.zip)

Usage: start the resource & click your mouse. a status (`single` or `double` click) will be displayed on the browser page, as well as in the console

2023-05-26 18:58 UTC, lopezloo commented
I think we shouldn't test such things with jQuery. I have modified your script to look like this:
<details>
  <summary>index.html</summary>

```html
<html>
    <head>
        <title>CEF Test</title>
    </head>
    <style>
        div {
            width: 100%; 
            color: #ccc; 
            margin-top: 10vh; 
            text-align: center; 
            font-size: 30px
        }
    </style>
    <body style="background: #222;">
        <div>Click anywhere</div>
        <div class="output" style="color: rgb(184, 49, 49); margin-top: 25px;"></div>

        <script>
            function log(message) {
                console.log(message);
                document.querySelector('.output').innerHTML += '<br>' + message;
            }

            addEventListener("mousedown", (event) => {
                log("mousedown @" + new Date().getTime());
            });

            addEventListener("mouseup", (event) => {
                log("mouseup @" + new Date().getTime());
            });

            addEventListener("dblclick", (event) => {
                log("double click @" + new Date().getTime());
            });

            addEventListener("click", (event) => {
                log("click @" + new Date().getTime());
            });
        </script>
    </body>
</html>

```
</details>

2023-05-26 19:01 UTC, lopezloo commented
Tested and it works but I don't understand why Chromium can't handle it by own?

From https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event:
> dblclick fires after two [click](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) events (and by extension, after two pairs of [mousedown](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) and [mouseup](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event) events).

Possibly because because it doesn't fire mousedown for next click? This is how currently it works on master:

```
mousedown @1685127605133
mouseup @1685127605179
click @1685127605179
mouseup @1685127605278
```

2023-06-12 14:51 UTC, Lpsd commented
Can you review your comments above please @lopezloo as I'm fairly certain this PR fixes the issue in the correct way, and is working as intended, as discussed on Discord

2023-06-12 14:56 UTC, lopezloo commented
> Can you review your comments above please @lopezloo as I'm fairly certain this PR fixes the issue in the correct way, and is working as intended, as discussed on Discord: https://discord.com/channels/801330706252038164/801411628600000522/1111735006142939136

It works but it still looks strange to me that the `CEGUI::Window::EventMouseButtonDown` event is not being called on double click. Looks like CEGUI thing.

2023-07-26 09:24 UTC, botder requested changes
Is the default value necessary? From what I see you never rely on it.

2023-07-26 09:24 UTC, botder commented on Client/cefweb/CWebView.h
> +    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count = 1);
```suggestion
    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count);
```

2023-07-26 09:24 UTC, botder commented on Client/mods/deathmatch/logic/CClientWebBrowser.h
> +    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count = 1);
```suggestion
    void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count);
```

2023-07-26 09:24 UTC, botder commented on Client/sdk/core/CWebViewInterface.h
> +    virtual void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count = 1) = 0;
```suggestion
    virtual void InjectMouseDown(eWebBrowserMouseButton mouseButton, int count) = 0;
```

2023-08-15 09:47 UTC, botder submitted a review, later dismissed

2023-08-15 11:22 UTC, merged