Add unsafe resource marker
multitheftauto/mtasa-blue pull request #3128
Opened 2023-07-24 22:48 UTC by botder

This pull request introduces an `<unsafe>true</unsafe>` marker requirement for every resource that utilizes either the `load` or `loadstring` function. Furthermore, an unsafe resource is not allowed to be granted the `general.ModifyOtherObjects` permission. An unsafe resource can still use `general.ModifyOtherObjects.<resourceName>` to receive access to specific resources, if desired.

Without this unsafe marker, these two functions will not work, not on the server neither on the client (if the bitstream version supports it). If a player with a newer client joins a server which doesn't support the unsafe marker yet, the client will default to unsafe mode and thus allow the usage of  `load` and `loadstring` functions.

For developers I have added the `isUnsafeResource` function, which returns a boolean whether the current resource is marked as unsafe. For security reasons this function should never be capable of returning the unsafe marker for another resource. Now, if you want to use either `load` or `loadstring` in your resource, you need to:

- add `<unsafe>true</unsafe>` to the meta.xml
- grant `function.loadstring` and/or `function.load` permissions for the resource
- ensure that `general.ModifyOtherObjects` is not granted to the resource

At last, the server now also restricts the functions `load` and `loadstring` by default. That means the permission to use either of those must be explicitly granted by the ACL.

2023-07-24 23:30 UTC, sbx320 requested changes

2023-07-24 23:30 UTC, sbx320 commented on Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
> +        lua_pushboolean(luaVM, false);
Also here

2023-07-24 23:30 UTC, sbx320 commented on Server/mods/deathmatch/logic/CResource.cpp
> +        m_isUnsafe = (canModifyOtherObjects == false);
This should probably also cause a warning log

2023-07-24 23:30 UTC, sbx320 commented on Client/mods/deathmatch/logic/luadefs/CLuaResourceDefs.cpp
> +    if (!luaMain.IsUnsafe())
We should throw an error here / print an error log, to indicate why this has failed.

2023-07-24 23:30 UTC, sbx320 commented
This seems like an odd place to break backwards compatibility. Most issues around `loadscript` are with server owners who have no clue what they are doing. Those will 

- Complain everywhere that we're breaking their scripts, and then 
- Enable `unsafe` for their resources, negating any benefit of this.

They are unlikely to actually fix any of their issuses due to a lack of Lua skills. 

Also the security benefits regarding `general.ModifyOtherObjects.` are rather doubtful, since any `loadscript`-capable resource is likely also running in an acl-admin context. As such it could just grant itself access to the relevant other resource on-demand.

There are also more ways to run arbitrary Lua scripts than just `loadscript` that aren't affected by this change. 

> For security reasons this function should never be capable of returning the unsafe marker for another resource.

Which security reasons? I don't really see an attack vector where it would be relevant if another resource is running in unsafe mode. 

> At last, the server now also restricts the functions load and loadstring by default. That means the permission to use either of those must be explicitly granted by the ACL.

That seems like a reasonable thing to do. The whole `unsafe` notion seems to me like it would cause more pain than benefit for everyone involved.

2023-07-24 23:50 UTC, botder commented
> This seems like an odd place to break backwards compatibility. Most issues around `loadscript` are with server owners who have no clue what they are doing. Those will
> 
> * Complain everywhere that we're breaking their scripts, and then
> * Enable `unsafe` for their resources, negating any benefit of this.
> 
> They are unlikely to actually fix any of their issuses due to a lack of Lua skills.

The plan is to catch these developers/server operators, provide a dedicated wiki page and further explanations in our support channel(s), because the idea here is to protect them from being exploited due to lack of knowledge in security aspects and ACL. It's being annoying on purpose, because we can't expect everyone to update their resources and ACL.

> Also the security benefits regarding `general.ModifyOtherObjects.` are rather doubtful, since any `loadscript`-capable resource is likely also running in an acl-admin context. As such it could just grant itself access to the relevant other resource on-demand.

The solution here would be to disable `aclSetRight` for unsafe resources, no? I also noticed that map editor wouldn't work with these changes (see edf/scriptreader.lua)

> There are also more ways to run arbitrary Lua scripts than just `loadscript` that aren't affected by this change.

Alright, but this pull request is specifically for exploitation of loadstring and load. What else do you have on your mind?

> Which security reasons? I don't really see an attack vector where it would be relevant if another resource is running in unsafe mode.

I thought you shouldn't be able to loop over all resources to find the unsafe ones with a convenient function.

> > At last, the server now also restricts the functions load and loadstring by default. That means the permission to use either of those must be explicitly granted by the ACL.
> 
> That seems like a reasonable thing to do (regardless of the rest of this PR). (Edit: `loadstring` handled in #3127)

Yeah. My pull request is restricting these two functions in C++ by default, the linked pull request is just being explicit about it.

2023-07-25 08:12 UTC, xLive commented
The restriction of `loadstring` will break scripts that call [other resources](https://github.com/search?q=loadstring%28exports.&type=code) to import their OOP classes or functions. And it's also needed for other purposes as well. For example, [DGS](https://wiki.multitheftauto.com/wiki/Resource:DGS) has [G2D](https://wiki.multitheftauto.com/wiki/DgsG2DLoadHooker#Example), which hooks every CEGUI function/event and replaces it with DGS by adding just two lines.

The easiest solution for many people would be marking their resources as unsafe without knowing what it actually does, which ruins the goal of this PR.

2023-07-25 10:21 UTC, botder commented
> The restriction of `loadstring` will break scripts that call [other resources](https://github.com/search?q=loadstring%28exports.&type=code) to import their OOP classes or functions. And it's also needed for other purposes as well. For example, [DGS](https://wiki.multitheftauto.com/wiki/Resource:DGS) has [G2D](https://wiki.multitheftauto.com/wiki/DgsG2DLoadHooker#Example), which hooks every CEGUI function/event and replaces it with DGS by adding just two lines.
> 
> The easiest solution for many people would be marking their resources as unsafe without knowing what it actually does, which ruins the goal of this PR.

I am not going to merge this pull request, but I don't think the loadstring approach is the correct way to accomplish what you want - sharing code between resources should be easier/safer.

2023-07-25 11:48 UTC, thisdp commented
> > The restriction of `loadstring` will break scripts that call [other resources](https://github.com/search?q=loadstring%28exports.&type=code) to import their OOP classes or functions. And it's also needed for other purposes as well. For example, [DGS](https://wiki.multitheftauto.com/wiki/Resource:DGS) has [G2D](https://wiki.multitheftauto.com/wiki/DgsG2DLoadHooker#Example), which hooks every CEGUI function/event and replaces it with DGS by adding just two lines.
> > The easiest solution for many people would be marking their resources as unsafe without knowing what it actually does, which ruins the goal of this PR.
> 
> I am not going to merge this pull request, but I don't think the loadstring approach is the correct way to accomplish what you want - sharing code between resources should be easier/safer.

The loadstring approach is used to eliminate prefix in the code. For example "exports.dgs:dgsSetText()" is really an annoying usage.

2023-07-25 12:07 UTC, botder commented
> The loadstring approach is used to eliminate prefix in the code. For example "exports.dgs:dgsSetText()" is really an annoying usage.

That problem is easily solved without loadstring, though:
```lua
function import(resourceName, into)
    into = into or _G
    local resource = getResourceFromName(resourceName)
    local exports = resource and getResourceExportedFunctions(resource) or {}

    for _, name in pairs(exports) do
        into[name] = function (...)
            return call(resource, name, ...)
        end
    end
end

import "mapmanager"

addCommandHandler("mmtest", function (_, _, name)
    changeGamemode(getResourceFromName(name))
end)
```

2023-07-25 12:08 UTC, thisdp commented
> > The loadstring approach is used to eliminate prefix in the code. For example "exports.dgs:dgsSetText()" is really an annoying usage.
> 
> That problem is easily solved without loadstring, though:
> 
> ```lua
> function import(resourceName, into)
>     into = into or _G
>     local resource = getResourceFromName(resourceName)
>     local exports = resource and getResourceExportedFunctions(resource) or {}
> 
>     for _, name in pairs(exports) do
>         into[name] = function (...)
>             return call(resource, name, ...)
>         end
>     end
> end
> 
> import "mapmanager"
> 
> addCommandHandler("mmtest", function (_, _, name)
>     changeGamemode(getResourceFromName(name))
> end)
> ```

but you still need to define "import" in other resource

2023-07-25 12:09 UTC, botder commented
> but you still need to define "import" in other resource

Of course, but 11 lines are not going to annoy anyone and you don't have a loadstring-backdoor.

2023-07-25 12:10 UTC, thisdp commented
> > but you still need to define "import" in other resource
> 
> Of course, but 11 lines are not going to annoy anyone and you don't have a loadstring-backdoor.

using loadstring, just 1 line

2023-07-25 12:11 UTC, botder commented
> using loadstring, just 1 line

If we were to add this kind of `import` function directly to MTA (like we do with `exports`), then it also would be 1 line without the security nightmare.

2023-07-25 12:12 UTC, thisdp commented
> > using loadstring, just 1 line
> 
> If we were to add this kind of `import` function directly to MTA (like we do with `exports`), then it also would be 1 line without the security nightmare.

that's the best way

2023-07-25 13:12 UTC, xLive commented
We still need a way to import OOP classes from one resource to another, along with a method to import wrapper functions. Currently, the only options are either using the `loadstring` or asking the scripters to manually add the script to their resources. The latter is difficult to manage, especially when the resource gets updated and it's used by many resources.

2023-07-25 13:23 UTC, tederis commented
**loadstring** is heavily used in big projects. It is a heart of custom modules systems. This PR will complicate the life of those projects. But safety is important and these changes should have happeded a long ago.

2023-07-25 13:26 UTC, botder commented
> **Note**
> I am not going to merge this pull request. It's going to break map editor and the effort is not worth it.

2023-07-25 13:41 UTC, closed without merging

2023-07-25 13:50 UTC, botder commented
> We still need a way to import OOP classes from one resource to another, along with a method to import wrapper functions. Currently, the only options are either using `loadstring` or asking the scripters to manually add the script to their resources. The latter is difficult to manage, especially when the resource gets updated and it's used by many resources.

We need a way to share scripts from resource to resource then. How should that look like?

Maybe a combination of `<script export="true" .../>` in the *source* resource,
and `<script from="resourceName" src="relative/path/here.lua"/>` in the *target* resource?

2023-07-25 14:32 UTC, srslyyyy commented
I believe it should work similar to [Lua's require](https://www.lua.org/pil/8.1.html), which is widely present, e.g: in GMod/Project Zomboid. However **require** is disabled in MTA for security reasons.

Example from Project Zomboid:
![obraz](https://github.com/multitheftauto/mtasa-blue/assets/51768772/a51f709f-8869-4b29-bfb2-9289dfc630b9)

Now i can't really explain how it works in-depth (as-in i've didn't used Lua outside MTA), but i've seen some people complaining about it missing. Creating new function like **mtaRequire** or **requireLua** which is consistent with how **require** behaves seems like a good move (to those people, who could come to MTA and knew Lua before it.)

2023-07-31 12:55 UTC, thisdp commented
When require called, hash of the required part should be checked