Fixed setElementDimension resets attachElements
multitheftauto/mtasa-blue pull request #3140
Opened 2023-08-03 03:39 UTC by HYPER-00

This pr fixes the issue #3114 
when use attachElement with setElementDimension all attached elements are reset

2023-08-03 15:16 UTC, CrosRoad95 reviewed
lgtm

2023-09-09 16:56 UTC, botder commented
My problem with this solution is the recursive event trigger of `onClientElementDimensionChange`.

2024-07-04 19:37 UTC, Proxy-99 commented
> My problem with this solution is the recursive event trigger of `onClientElementDimensionChange`.

@HYPER-00 can u work on this and add function like 
`GetAttachedEntity(i)->SetAttachElemenstDimension(usDimension);`

2024-07-05 07:49 UTC, TracerDS requested changes

2024-07-05 07:49 UTC, TracerDS commented on Client/mods/deathmatch/logic/CClientEntity.cpp
> +    }
Use iterators instead + `auto` or `std::size_t` instead of `uint`

2024-11-09 01:41 UTC, closed without merging