Feature: dxDrawModel3d
multitheftauto/mtasa-blue pull request #3172
Opened 2023-09-03 15:15 UTC by CrosRoad95

This pull request adds function to draw arbitrary model in simillar fasion as other dxDraw* functions

syntax: `bool dxDrawModel3d(model, position, rotation, optional scale)` ( draw in onClientRender/onClientPreRender loop )

You can draw as many objects as you want, it has no limits both amount of models and draw distance.
Rendered models has no collision, they look exactly the same as objects created using "createObject" ( possibly transparency will be an issue )
use cases:
1. draw vegetation
2. draw ped/vehicles visual accessories
3. draw miscellaneous objects on ground as an items player can pick up

example: `dxDrawModel3d(3276, -719.64984, 951.26685, 12.13281, 0, 0,90)` - as you can see, it look 1:1 as createObject
![image](https://github.com/multitheftauto/mtasa-blue/assets/22455534/a0f4a851-6893-4a6a-9074-354ce47515d6)
![image](https://github.com/multitheftauto/mtasa-blue/assets/22455534/16faa4fe-dedf-4ff0-9e0f-6b708431f4e1)

No limits:
![image](https://github.com/multitheftauto/mtasa-blue/assets/22455534/33b79461-ab39-4e90-96d2-b4883c0bec87)
![image](https://github.com/multitheftauto/mtasa-blue/assets/22455534/102a36f8-0bf7-465d-9cec-ddd80b68db7c)

2023-09-03 17:34 UTC, Einheit-101 commented
This is nice. I guess you trade performance for free object streaming slots?

2023-09-03 17:37 UTC, CrosRoad95 commented
you can call it that

2023-09-08 15:29 UTC, Pirulax commented
Eh I'd argue this is faster than having objects, as they have a lot of overhead.
These don't have collisions either, so there's that.

2023-10-10 10:25 UTC, Lpsd requested changes

2023-10-10 10:25 UTC, Lpsd commented on Client/mods/deathmatch/logic/luadefs/CLuaDrawingDefs.cpp
> +        {"dxDrawModel3d", ArgumentParser<DxDrawModel3d>},
rename to `dxDrawModel3D` for case consistency with other functions

2023-10-14 05:47 UTC, Lpsd approved these changes

2023-10-14 06:14 UTC, merged

2023-10-14 08:50 UTC, tederis commented
There is a lot of commented out lines. I doubt that it should be merged in this "dirty" condition. But now it is too late to worry anyway.

2023-10-14 09:01 UTC, Lpsd commented
It's never too late to worry. https://github.com/multitheftauto/mtasa-blue/pull/3210

2023-10-15 18:07 UTC, onikyannn commented
Object is rendered at zero coordinates in any dimension other than 0.

2023-10-16 06:39 UTC, Xenius97 commented
What about dxDrawModel2D?
Non shadered version of https://wiki.multitheftauto.com/wiki/Resource:Object_preview

2023-10-16 08:20 UTC, tederis commented
> What about dxDrawModel2D? Non shadered version of https://wiki.multitheftauto.com/wiki/Resource:Object_preview

It will be enough just to call dxDrawModel3d inside a render target.

2023-10-16 10:23 UTC, PlatinMTA commented
> It will be enough just to call dxDrawModel3d inside a render target.

wiki says no rendertarget support

2023-10-16 11:50 UTC, tederis commented
> > It will be enough just to call dxDrawModel3d inside a render target.
> 
> wiki says no rendertarget support

Of course there is no RT support now. But it can be easily added.

2023-10-16 14:19 UTC, Dutchman101 commented
Reverted in 5b44a09 as a result of dev discord feedback:

_TEDERIs — Today at 2:24 PM
I respect the efforts of CrosRoad95. But I think #3172 (dxDrawModel3d feature) should be revoked. It's very buggy now, has a lot of internal problems and even cause crashes. It renders an object randomly (due to the nature of CClientGame::GameEntityRenderHandler) which leads to an unpredictable appearience(and can even disappear). Even after #3210 it contains unused code(see HOOKPOS_CRenderer__RenderFadingInEntities_MID). And it can crash the game(see model handling in DxDrawModel3D). This is nice PR, but it still has a long way to go before it is ready for production use_