added new function setVehicleRespawnPosition/Rotation
multitheftauto/mtasa-blue pull request #338
Opened 2018-08-23 20:51 UTC by l0nger

function **setVehicleRespawnPosition** has been changed to:
- setVehicleRespawnPosition( vehicle theVehicle, x, y, z )
- setVehicleRespawnRotation( vehicle theVehicle, rx, ry, rz )
- getVehicleRespawnPosition( vehicle theVehicle )
- getVehicleRespawnRotation( vehicle theVehicle )

adapted under OOP:
- vehicle:setRespawnPosition( x, y, z )
- vehicle:setRespawnRotation( x, y, z )
- vehicle:getRespawnPosition( )
- vehicle:getRespawnRotation( )

lua class variables inherit to vehicle element
- vehicle.respawnPosition
- vehicle.respawnRotation

2018-08-23 22:07 UTC, qaisjp requested changes

2018-08-23 22:07 UTC, qaisjp commented on Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
> -    argStream.ReadVector3D(vecRotation, CVector());
SetVehicleRespawnPosition should still support rotation due to backwards compat

2018-08-23 22:07 UTC, Addlibs commented on Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
> -    argStream.ReadVector3D(vecRotation, CVector());
What about existing code? setVehicleRespawnPosition should retain the ability to set respawn rotations, as existing code could rely on this behaviour. 

The most you could do is deprecate this for now, meaning add a warning like this or something, but retain the functionality (not tested nor attempted to compile):
```cpp
if (argStream.NextIsVector3D())
{
    CVector vecRotation;
    argStream.ReadVector3D(vecRotation);

    // Set deprecation warning
    argStream.SetCustomWarning("Setting respawn rotation in setVehicleRespawnPosition is deprecated and may not work in future versions. Please consider using setVehicleRespawnRotation.");
    if (!argStream.HasErrors()) // Deprecation warning is printed out at this call
    {
        // Update position and rotation
    }
}
else if (!argStream.HasErrors())
{
    // Update position only
}
```

2018-08-24 08:33 UTC, l0nger commented
Fixed, thanks for tip @Addlibs

2018-09-04 23:50 UTC, merged