Allow setElementCollisionsEnabled for buildings
multitheftauto/mtasa-blue pull request #3384
Opened 2024-05-11 16:25 UTC by TheNormalnij

Test:
```
crun o = createBuilding(1337, 0, 0, 5, 0,0,0)
crun setElementCollisionsEnabled(o, false)
```

2024-05-11 17:35 UTC, Nico8340 approved these changes
Looks good 🚀

2024-05-28 12:21 UTC, botder requested changes

2024-05-28 12:21 UTC, botder commented on Client/mods/deathmatch/logic/CClientBuilding.h
> +    bool       m_bUsesCollision;
Rename this to `m_usesCollision`

2024-05-28 12:21 UTC, botder commented on Client/mods/deathmatch/logic/CClientBuilding.cpp
> +    if (m_bUsesCollision == false)
```suggestion
    if (!m_bUsesCollision)
```

2024-05-28 12:21 UTC, botder commented on Client/mods/deathmatch/logic/CClientBuilding.cpp
> +    m_bUsesCollision = state;
Add please
```cpp
if (m_bUsesCollision == state)
    return;
```

2024-05-28 18:57 UTC, TheNormalnij commented
@botder ty

2024-05-28 20:17 UTC, botder approved these changes

2024-05-28 20:17 UTC, merged