Update acl.xml - add runcode loadstring permission
multitheftauto/mtasa-blue pull request #3393
Opened 2024-05-17 12:35 UTC by Fernando-A-Rocha

Default MTA Resource `runcode` requires function.loadstring access.

With default acl.xml, it kept printing a warning when you start the MTA server.

2024-05-24 15:51 UTC, Nico8340 requested changes

2024-05-24 15:51 UTC, ghost commented on Server/mods/deathmatch/acl.xml
> +   <group name="runcodeACLGroup">
I think we should stick with the previous naming conventions, RuncodeGroup would be a better name.

2024-05-24 15:51 UTC, ghost commented on Server/mods/deathmatch/acl.xml
> +   <acl name="runcodeACL">
I think we should stick with the previous naming conventions, RuncodeACL would be a better name.

2024-05-25 03:21 UTC, jlillis commented
I don't think we should give `runcode` any rights by default. It would be better to make admins explicitly give it `loadstring` access using an aclrequest.

2024-05-25 10:27 UTC, Fernando-A-Rocha commented
> I don't think we should give `runcode` any rights by default. It would be better to make admins explicitly give it `loadstring` access using an aclrequest.

Sure, it should only be used by server developers that know what they're doing with the code ran...

2024-05-31 09:41 UTC, Fernando-A-Rocha commented
Naming changes were made in case you guys want to implement this

2024-05-31 23:44 UTC, Nico8340 reviewed
Naming is suitable for me, it fits into our scheme, but the team has to make the decision in this matter for security reasons.

2024-06-03 13:14 UTC, botder commented
Personally, I would not add this to the default acl.xml

2024-06-11 01:59 UTC, Dutchman101 commented
Thanks for the suggestion, but no

2024-06-11 01:59 UTC, closed without merging