Fix #3441 - Add vehicle respawn related functions
multitheftauto/mtasa-blue pull request #3442
Opened 2024-06-08 13:25 UTC by TracerDS

`bool isVehicleRespawnable ( Vehicle vehicle )`
Returns **true** if vehicle is respawnable, **false** otherwise.

`int getVehicleRespawnDelay ( vehicle theVehicle )`
Returns number of milliseconds (probably) for vehicle to respawn after being destroyed

`int getVehicleIdleRespawnDelay ( vehicle theVehicle )`
Returns number of milliseconds (probably) for vehicle to respawn after waiting for some time

2024-06-08 13:40 UTC, Nico8340 approved these changes
LGTM

2024-06-09 00:14 UTC, botder requested changes

2024-06-09 00:14 UTC, botder commented on Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.h
> +    static std::uint32_t GetVehicleIdleRespawnDelay(CVehicle* vehicle) noexcept;
```suggestion
    static uint32_t GetVehicleRespawnDelay(CVehicle* vehicle) noexcept;
    static uint32_t GetVehicleIdleRespawnDelay(CVehicle* vehicle) noexcept;
```

2024-06-09 00:14 UTC, botder commented on Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp
> +}
```suggestion
uint32_t CLuaVehicleDefs::GetVehicleRespawnDelay(CVehicle* vehicle) noexcept
{
    return vehicle->GetBlowRespawnInterval();
}

uint32_t CLuaVehicleDefs::GetVehicleIdleRespawnDelay(CVehicle* vehicle) noexcept
{
    return vehicle->GetIdleRespawnInterval();
}
```

2024-06-09 00:14 UTC, botder commented on Server/mods/deathmatch/logic/CVehicle.h
> +    bool           GetRespawnEnabled() const { return m_bRespawnEnabled; }
```suggestion
    bool           GetRespawnEnabled() const noexcept { return m_bRespawnEnabled; }
```

2024-06-09 00:15 UTC, botder approved these changes

2024-06-09 00:33 UTC, merged