Read a file directly from path - `fileRead` update
multitheftauto/mtasa-blue pull request #3490
Opened 2024-06-18 13:59 UTC by TracerDS

Currently, to read a file you have to have a boilerplate code for opening and closing a file:
```lua
local file = fileOpen('path.extension')
-- ...
fileClose(file)
```
This PR will allow you to read file from path without having to define this boilerplate:
```lua
local content = fileRead('MyFile.txt')
```

2024-06-18 14:07 UTC, Fernando-A-Rocha commented
Genius

2024-06-18 14:09 UTC, tederis commented
Are you aware of function `fileGetContents`? You can just `fileGetContents(fileOpen("file.txt"))`.

2024-06-18 14:14 UTC, TracerDS commented
> Are you aware of function `fileGetContents`? You can just `fileGetContents(fileOpen("file.txt"))`.

Does `fileGetContents` close the file automatically for you?
It also requires a file handle. It was either that or modify `fileGetContents`

2024-06-18 14:15 UTC, MegadreamsBE commented
> > Are you aware of function `fileGetContents`? You can just `fileGetContents(fileOpen("file.txt"))`.
> 
> Does `fileGetContents` close the file automatically for you? It also requires a file handle. It was either that or modify `fileGetContents`

It doesn't no. So I'm fine with this change for quality of life. Perhaps fileGetContents could have something similar

2024-06-18 14:17 UTC, tederis commented
> > Are you aware of function `fileGetContents`? You can just `fileGetContents(fileOpen("file.txt"))`.
> 
> Does `fileGetContents` close the file automatically for you? It also requires a file handle. It was either that or modify `fileGetContents`

Oh, you're right, it doesn't. Okay then.

2024-06-18 14:22 UTC, tederis requested changes

2024-06-18 14:22 UTC, tederis commented on Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
> +        throw std::runtime_error(SString("unable to load file '%s'", strInputPath.c_str()));
This will lead to std::terminate because `runtime_error` isn't properly handled by the argument parser.

2024-06-18 14:22 UTC, tederis commented on Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
> +    auto content = ReadFile(pFile, pFile->GetSize());
Please, don't use auto for implicit types.

2024-06-18 14:22 UTC, tederis commented on Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
> +            throw std::runtime_error(canModify.second);
This will lead to std::terminate because runtime_error isn't properly handled by the argument parser.

2024-06-18 14:22 UTC, tederis commented on Shared/mods/deathmatch/logic/luadefs/CLuaFileDefs.cpp
> +            throw std::runtime_error(canModify.second);
This will lead to std::terminate because runtime_error isn't properly handled by the argument parser.

2024-06-18 14:31 UTC, Fernando-A-Rocha commented
@TracerDS Make fileGetContents accept a string as argument, so it does the opening and closing of the file automatically. It can keep working with an open file handle as argument for backwards compatibility and certain use cases.

2024-06-18 14:32 UTC, TracerDS commented
> @TracerDS Make fileGetContents accept a string as argument, so it does the opening and closing of the file automatically. It can keep working with an open file handle as argument for backwards compatibility and certain use cases.

so, the same thing as `fileRead` but for `fileGetContents`?

2024-06-18 14:32 UTC, Fernando-A-Rocha commented
> > @TracerDS Make fileGetContents accept a string as argument, so it does the opening and closing of the file automatically. It can keep working with an open file handle as argument for backwards compatibility and certain use cases.
> 
> so, the same thing as `fileRead` but for `fileGetContents`?

I don't see any cons to that

2024-06-18 15:35 UTC, Fernando-A-Rocha commented
So uhmmm, arent fileRead and fileGetContents the same now? Is fileRead necessary?

2024-06-18 15:36 UTC, MegadreamsBE commented
> So uhmmm, arent fileRead and fileGetContents the same now? Is fileRead necessary?

One major difference at least is that fileGetContents requires files to be in meta.xml, and has the ability to validate them. But overall they are getting pretty close to each other

2024-06-19 03:12 UTC, tederis commented
> > So uhmmm, arent fileRead and fileGetContents the same now? Is fileRead necessary?
> 
> One major difference at least is that fileGetContents requires files to be in meta.xml, and has the ability to validate them. But overall they are getting pretty close to each other

Only if the second argument is set to true.

2024-06-21 14:05 UTC, Fernando-A-Rocha commented
I like fileRead but it's exactly the same as doing fileGetContents(path, false)

Can we have fileRead still?

2024-06-21 14:20 UTC, TracerDS commented
> I like fileRead but it's exactly the same as doing fileGetContents(path, false)
> 
> Can we have fileRead still?

There is no reason to remove it

2024-06-21 14:22 UTC, Fernando-A-Rocha commented
> > I like fileRead but it's exactly the same as doing fileGetContents(path, false)
> > Can we have fileRead still?
> 
> There is no reason to remove it

Sorry, I had a brain fart. Forgot fileRead already existed.
This is nice QoL feature.

PR LGTM then :shipit:

2024-06-24 15:31 UTC, merged

2024-06-30 19:29 UTC, Dutchman101 commented
This PR has been reverted after merge

Details on revert reason: https://github.com/multitheftauto/mtasa-blue/commit/97920d83de400e0378f73ea93e87b27cf59dd758#commitcomment-143697266 (and up)

cc @TracerDS