Fixed backward compatibility of checkpoints and arrows marker
multitheftauto/mtasa-blue pull request #3540
Opened 2024-07-03 13:18 UTC by FileEX

Added a new optional argument to createMarker
``ignoreAlphaLimits = false``

This argument is only valid for checkpoint and arrow markers. It defines whether the alpha of these markers can be changed. If the argument is false, the marker has a constant alpha as before, i.e. checkpoint always 128 and arrow always 255. If the argument is true, alpha can be changed.

Default is **false**

2024-07-03 13:46 UTC, TracerDS requested changes

2024-07-03 13:46 UTC, TracerDS commented on Client/mods/deathmatch/logic/CClient3DMarker.h
> +    void   SetColor(const SColor& color);
`noexcept`

2024-07-03 13:46 UTC, TracerDS commented on Client/mods/deathmatch/logic/CClientCheckpoint.h
> +    void IgnoreAlphaLimits(bool ignore) noexcept { m_ignoreAlphaLimits = ignore; };
What do you think about `SetIgnoreAlphaLimits`?

2024-07-03 13:46 UTC, TracerDS commented on Client/mods/deathmatch/logic/CClientMarkerCommon.h
> +    virtual bool AreAlphaLimitsIgnored() const = 0;
`noexcept`?

2024-07-15 11:49 UTC, Dutchman101 commented
Please resolve conflicts
@FileEX

2024-07-15 13:07 UTC, FileEX commented
> Please resolve conflicts @FileEX

Done

2024-07-15 13:17 UTC, merged