Added ShakeCamera
multitheftauto/mtasa-blue pull request #3585
Opened 2024-07-19 19:50 UTC by TracerDS

Resolves #3584 

Usage:
```lua
bool shakeCamera(float power, [float x, float y, float z])
```
* power - intensity **and** time of the shake
* x - center x coordinate of the shake
* y - center y coordinate of the shake
* z - center z coordinate of the shake

2024-07-20 00:27 UTC, Nico8340 approved these changes
LGTM

2024-07-20 12:20 UTC, G-Moris commented
Perhaps getting a local player in the lua function should be replaced with `const CClientPlayer* pPlayer = CStaticFunctionDefinitions::GetLocalPlayer();`?

2024-07-20 12:23 UTC, TracerDS commented
> Perhaps getting a local player in the lua function should be replaced with `const CClientPlayer* pPlayer = CStaticFunctionDefinitions::GetLocalPlayer();`?

So just add `const`? Sure, thats a good idea

2024-07-20 12:29 UTC, G-Moris commented
> > Perhaps getting a local player in the lua function should be replaced with `const CClientPlayer* pPlayer = CStaticFunctionDefinitions::GetLocalPlayer();`?
> 
> So just add `const`? Sure, thats a good idea

Just to make the code easier to read, you can replace `auto*` with `CClientPlayer*`. What is your opinion about this?

2024-07-20 12:30 UTC, TracerDS commented
> Just to make the code easier to read, you can replace `auto*` with `CClientPlayer*`. What is your opinion about this?

That would make it harder to read. I'm gonna leave it at `const auto*`

2024-07-20 12:31 UTC, G-Moris commented
> > Just to make the code easier to read, you can replace `auto*` with `CClientPlayer*`. What is your opinion about this?
> 
> Actually, that would make it harder to read. I'm gonna leave it at `const auto*`

Good

2024-07-20 17:08 UTC, Nico8340 requested changes

2024-07-20 17:08 UTC, Nico8340 commented on Client/mods/deathmatch/logic/luadefs/CLuaCameraDefs.cpp
> +        z = out.fZ;
```suggestion
        if (!x) x = out.fX;
        if (!y) y = out.fY;
        if (!z) z = out.fZ;
```

2024-07-20 17:11 UTC, Nico8340 approved these changes
Awesome

2024-07-21 15:58 UTC, Lpsd approved these changes

2024-07-21 15:58 UTC, merged

2024-07-21 15:59 UTC, Lpsd commented
Please add the relevant wiki page

2024-07-21 15:59 UTC, TracerDS commented
> Please add the relevant wiki page

Of course