Update CONTRIBUTING.md and links
multitheftauto/mtasa-blue pull request #3590
Opened 2024-07-20 14:38 UTC by Fernando-A-Rocha

The new information is now available at mtasa-docs https://github.com/multitheftauto/mtasa-docs/blob/main/mtasa-blue/CONTRIBUTING.md

2024-07-20 15:07 UTC, Lpsd requested changes

2024-07-20 15:07 UTC, Lpsd commented on CONTRIBUTING.md
> +The information previously available on this document may now be available at [mtasa-docs (mtasa-blue CONTRIBUTING.md)](https://github.com/multitheftauto/mtasa-docs/blob/main/mtasa-blue/CONTRIBUTING.
> This information is now available at [...]

2024-07-22 09:17 UTC, TracerDS approved these changes

2024-09-03 12:41 UTC, Fernando-A-Rocha commented
Ready

2024-09-12 11:39 UTC, tederis approved these changes

2024-09-12 18:07 UTC, Lpsd approved these changes

2024-09-12 18:07 UTC, merged