Add "flyingcomponents" special world property
multitheftauto/mtasa-blue pull request #3597
Opened 2024-07-22 00:18 UTC by FileEX

Merge after #3572 

This PR adds a new special world property called ``flyingcomponents`` (default is true). This property determines whether the detached components such as doors, bumpers, etc., should respawn after a vehicle is recreated or streamed in. This PR solves a very frustrating and annoying issue where all missing components fall off again after using ``setElementModel`` or ``setVehicleVariant``:

![image](https://github.com/user-attachments/assets/9b90fb3a-219c-48ce-8b62-4dd661d2858a)

Thanks to this property, various car garages and vehicle spawners will be able to look normal without flying components around

2024-07-22 00:41 UTC, Dark-Dragon commented
Again I'll have to point out that this to me seems like more of a bug-fix-scenario, rather than a special-world-property-scenario. What about the current behavior is desirable?

2024-07-22 00:46 UTC, FileEX commented
Probably nothing, but it's better to set it to the current default than for the PR to get labeled as 'backwards-incompatible' and sit for several months, or possibly even years

2024-10-01 16:55 UTC, TheNormalnij commented
> Probably nothing, but it's better to set it to the current default than for the PR to get labeled as 'backwards-incompatible'

It won't. Current state is bugged

2024-10-05 15:52 UTC, FileEX commented
> > Probably nothing, but it's better to set it to the current default than for the PR to get labeled as 'backwards-incompatible'
> 
> It won't. Current state is bugged

Done

2024-11-06 12:15 UTC, Fernando-A-Rocha approved these changes
Fine to merge

2025-01-10 20:44 UTC, botder requested changes

2025-01-10 20:44 UTC, botder commented on Client/mods/deathmatch/logic/CClientVehicleManager.cpp
> +    m_spawnFlyingComponentsDuringRecreate = true;
```suggestion
```

2025-01-10 20:44 UTC, botder commented on Client/mods/deathmatch/logic/CClientVehicleManager.h
> +    bool                          m_spawnFlyingComponentsDuringRecreate;
```suggestion
    bool                          m_spawnFlyingComponentsDuringRecreate{true};
```

2025-01-10 20:44 UTC, botder commented on Server/mods/deathmatch/logic/CGame.cpp
> +    m_WorldSpecialProps[WorldSpecialProperty::FLYINGCOMPONENTS] = false;
```suggestion
    m_WorldSpecialProps[WorldSpecialProperty::FLYINGCOMPONENTS] = true;
```

2025-01-10 20:44 UTC, botder commented on Shared/sdk/net/SyncStructures.h
> +
```suggestion

```

2025-01-10 20:44 UTC, botder commented on Shared/sdk/net/SyncStructures.h
> +        data7.flyingcomponents = false;
```suggestion
        data7.flyingcomponents = true;
```

2025-01-10 20:46 UTC, botder commented on Shared/sdk/net/SyncStructures.h
> +            bitStream.WriteBits(reinterpret_cast<const char*>(&data7), BITCOUNT7);
```suggestion
        if (bitStream.Can(eBitStreamVersion::WorldSpecialProperty_FlyingComponents))
            bitStream.WriteBits(reinterpret_cast<const char*>(&data7), BITCOUNT7);

```

2025-01-10 20:48 UTC, botder approved these changes
I've fixed defaults in the sync structures where you used `false` instead of `true` for this new special world property.

2025-01-10 21:24 UTC, merged