Allow longer LOD distances
multitheftauto/mtasa-blue pull request #3606
Opened 2024-07-24 17:20 UTC by TheNormalnij

Fixes #3601
LOD distance is limited up to 325 in `engineSetModelLODDistance`.
It's limited to create alpha fade effect in `setLowLODElement` for objects.
Buildings use the GTA LOD's implementation and request a larger model LOD distance

2024-07-25 14:34 UTC, Pirulax requested changes
So if I understand correctly, this higher LOD distance will only works for buildings? (From `createBuilding`)? 
If so, there's no need for an extra argument, no?
Otherwise, I dont understand why there was a limitation there in the first place, if it can be ignored using a bool argument.

2024-07-25 14:34 UTC, Pirulax commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
>      // bool engineSetModelLODDistance ( int/string modelID, float distance )
update the comment too

2024-07-27 21:55 UTC, TheNormalnij commented on Client/mods/deathmatch/logic/luadefs/CLuaEngineDefs.cpp
>      // bool engineSetModelLODDistance ( int/string modelID, float distance )
thx

2024-07-27 22:22 UTC, TheNormalnij commented
> If so, there's no need for an extra argument, no?

This function is used for a long time with objects LOD's. I tried a LOD distance longer than 325 with big maps loaded by `createObject` and it caused object popping.
Technically, we could increase the limit and break old maps or we could add an argument to prevent destructive behavior.

If we are very close to the next MTA release, i'd prefer the first option

2024-07-28 13:03 UTC, Pirulax commented
But wait. Doesn't that "extendedLod" argument just remove the limit on the "distance" paramter?

2024-07-28 13:05 UTC, TheNormalnij commented
> But wait. Doesn't that "extendedLod" argument just remove the limit on the "distance" paramter?

yes

2024-07-31 14:35 UTC, FileEX approved these changes

2024-08-01 06:09 UTC, gta191977649 approved these changes

2024-08-14 18:49 UTC, merged

2024-09-13 19:48 UTC, Einheit-101 commented
Did somebody test if this doesnt cause any problems if weird numbers are put in? This new argument removes the limit entirely, so strange things or even crashes could eventually happen.

2024-09-16 16:04 UTC, TheNormalnij commented
> Did somebody test if this doesnt cause any problems if weird numbers are put in? This new argument removes the limit entirely, so strange things or even crashes could eventually happen.

Big numbers can cause render issues for lod's, when this functions is used for objects.