0007448: Add guiBlur and guiFocus functions
multitheftauto/mtasa-blue pull request #365
Opened 2018-09-02 15:47 UTC by patrikjuvonen

### Mantis Bug Tracker issue
[9814](https://bugs.multitheftauto.com/view.php?id=9814)

### Summary
- Add guiBlur function, which "de-focuses" the specified gui element.
`bool guiBlur ( element guiElement )`
- Add guiFocus function, which "focuses" the specified gui element.
`bool guiFocus ( element guiElement [, bool bMoveCaretToEnd = true ] )`
- [onClientGUIBlur](https://wiki.multitheftauto.com/wiki/OnClientGUIBlur) and [onClientGUIFocus](https://wiki.multitheftauto.com/wiki/OnClientGUIFocus) events work with these functions.

### Requesting scripting feedback
The `bMoveCaretToEnd` argument is used only on editboxes and memos to move the caret to the end of text. I've enabled it by default. I introduced this argument so it would be easier for things like username/password fields where you usually want to autofocus to the end of the input field instead of the default CEGUI behavior where it focuses always to beginning of the field. With this approach to set a specific caret index, you'd have to use use [guiEditSetCaretIndex](https://wiki.multitheftauto.com/wiki/GuiEditSetCaretIndex) or [guiMemoSetCaretIndex](https://wiki.multitheftauto.com/wiki/GuiMemoSetCaretIndex) separate from this function.

Another approach would be to have a `uiCaretIndex` argument instead of `bMoveCaretToEnd` for more specific caret focusing without having to use [guiEditSetCaretIndex](https://wiki.multitheftauto.com/wiki/GuiEditSetCaretIndex) or [guiMemoSetCaretIndex](https://wiki.multitheftauto.com/wiki/GuiMemoSetCaretIndex) when focusing. I'm requesting feedback from you to vote on which is better.

2018-09-27 11:01 UTC, qaisjp commented
Regarding `Requesting scripting feedback` - I think we should do what browsers do, and set it to the most recent caret position.

2019-01-01 00:29 UTC, patrikjuvonen commented
> Regarding `Requesting scripting feedback` - I think we should do what browsers do, and set it to the most recent caret position.

@qaisjp Thanks for the feedback, I agree. I've now changed the behavior so that by default the caret position is set to the previous caret position. I still kept the `bMoveCaretToEnd` argument though, makes script code cleaner for those who want that behavior.

2019-01-01 12:42 UTC, qaisjp approved these changes
> I still kept the bMoveCaretToEnd argument though, makes script code cleaner for those who want that behavior.

This pull request looks ready to merge! Just not sure on the extra arg — it seems like it's just to save an extra line, which feels unnecessary to me.

@multitheftauto/blue-maintainers, what are your thoughts, can you weigh in on the extra argument? Please send another review and merge!

2019-01-02 19:35 UTC, botder commented
I don't mind the extra argument.

2019-01-02 20:46 UTC, qaisjp commented
> Thanks for the feedback, I agree. I've now changed the behavior so that by default the caret position is set to the previous caret position. I still kept the `bMoveCaretToEnd` argument though, makes script code cleaner for those who want that behavior.

But then server owners will have to keep track of whether the player moved the caret, and will always set `bMoveCaretToEnd=true`... right?

This is what I am imagining:

- There's a login panel with username and password
- User types in username (this caret positioning is now set to end of this field)
- User types in password (this caret positioning is now set to end of this field)
- User clicks submit (focus taken off password field)
- Password is incorrect
- Password field is focused to, which moves caret to the last caret position, which is the end of that field

Which is as intended, without an extra line or extra parameter... right?

2019-01-03 01:27 UTC, patrikjuvonen commented
Yes. However add a few complications to your image such as typing an error in the middle of your username and clicking at that specific caret position to fix it. Now your caret position is not in the end anymore. I don't know what the big hassle is about.

2019-01-03 01:31 UTC, qaisjp commented
Indeed, I thought about that. So I checked what browsers do, and they don't set the caret position to the end. I don't think we should either!

> hassle

I'm trying to avoid adding extra cruft to the Lua API when an extra line of code works just fine.

2019-01-03 01:41 UTC, patrikjuvonen commented
I understand that we don't want to add more redundant stuff. In this case the behavior is useful and reasonable. We're not providing the argument for setting the caret position to a specified index but rather just to the end. It's more of a choice/preference parameter and I believe it makes sense and doesn't haunt me at night thinking we have an extra argument in our code :)

2019-01-06 11:59 UTC, botder submitted a review, later dismissed

2019-01-06 11:59 UTC, botder commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> +        lua_pushboolean(luaVM, true);
You can reduce the two lines into `lua_pushboolean(luaVM, CStaticFunctionDefinitions::GUIBlur(*guiElement));`

2019-01-06 11:59 UTC, botder commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> +    lua_pushboolean(luaVM, false);
Change this line to `lua_pushnil(luaVM)`. Bad arguments must result in **nil**.

2019-01-06 11:59 UTC, botder commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> +    lua_pushboolean(luaVM, false);
Change this line to `lua_pushnil(luaVM)`. Bad arguments must result in **nil**.

2019-01-06 11:59 UTC, botder commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> +        lua_pushboolean(luaVM, true);
Use the return value of `CStaticFunctionDefinitions::GUIFocus` instead of `true`

2019-01-06 11:59 UTC, botder commented on Client/mods/deathmatch/logic/luadefs/CLuaGUIDefs.cpp
> +        if (bMoveCaretToEnd) {
This block will execute even if `CStaticFunctionDefinitions::GUIFocus` returns false, please correct.

2019-01-06 12:23 UTC, patrikjuvonen commented
@botder Thanks for your review. I've updated the code accordingly.

2019-01-12 17:55 UTC, qaisjp requested changes
I am pretty sure about the additional `bMoveCaretToEnd` being unnecessary. (Neither does JavaScript have this sort of argument for focus)

Also, I think @botder's review was incorrect. guiBlur and guiFocus both only return `true` for success, and so should return `false` for any sort of failure. `nil` is only returned for getters.

2019-01-12 19:51 UTC, patrikjuvonen commented
> I am pretty sure about the additional `bMoveCaretToEnd` being unnecessary. (Neither does JavaScript have this sort of argument for focus)
> 
> Also, I think @botder's review was incorrect. guiBlur and guiFocus both only return `true` for success, and so should return `false` for any sort of failure. `nil` is only returned for getters.

Thanks for the second review. I've now adjusted the functions accordingly.

2019-02-10 13:15 UTC, qaisjp approved these changes

2019-02-10 14:27 UTC, merged