Fixes getTimerDetails negative remaining duration
multitheftauto/mtasa-blue pull request #3663
Opened 2024-08-20 04:30 UTC by jvstns

Fixes #3355

2024-08-20 21:25 UTC, Nico8340 requested changes

2024-08-20 21:25 UTC, Nico8340 commented on Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp
>      return llTimeLeft;
What about using the ternary operator?
We could combine the logic into a single return statement.

```suggestion
    return llTimeLeft.ToLongLong() < 0 ? CTickCount(0LL) : llTimeLeft;
```

2024-08-21 02:42 UTC, Nico8340 approved these changes
LGTM

2024-08-22 04:03 UTC, tederis commented on Shared/mods/deathmatch/logic/lua/CLuaTimer.cpp
> +    return llTimeLeft.ToLongLong() < 0 ? CTickCount(0LL) : llTimeLeft;
`llTimeLeft.ToLongLong() < 0ll`

2024-08-23 15:34 UTC, tederis approved these changes

2024-08-24 04:49 UTC, merged