Add element data client trust functions.
multitheftauto/mtasa-blue pull request #3839
Opened 2024-11-03 13:50 UTC by TheNormalnij

```lua
-- Enables or disables element data changes from clients
nil setElementDataClientTrust(element theElement, bool status [, string key ] )

-- Returns true if a element data can be changed by clients and false if not
bool isElementDataClientTrusted(element theElement [, string key ])

-- Reset to default
nil resetElementDataClientTrust(element theElement [, string key ] )
```

Added event `onPlayerChangesProtectedData`
source: player
arguments:
* element,
* key,
* value

Examples:
```lua

-- Disable all changes from clients
setElementDataClientTrust(root, false)

-- Disable changes for a key from clients
setElementDataClientTrust(root, false, "serverOnlyKey")

-- Disable all keys except "allowedKey"
setElementDataClientTrust(root, false)
setElementDataClientTrust(root, true, "allowedKey")
```

2024-11-03 13:51 UTC, TracerDS commented
Whats the purpose of these functions?

2024-11-03 13:52 UTC, TracerDS requested changes

2024-11-03 13:52 UTC, TracerDS commented on Server/mods/deathmatch/logic/CCustomData.h
> +enum class ECustomDataClientTrust : std::uint8_t
lowercase e? (`eCustomDataClientTrust`)

2024-11-03 13:52 UTC, TracerDS commented on Server/mods/deathmatch/logic/luadefs/CLuaElementDefs.cpp
> +void CLuaElementDefs::ResetElementDataClientTrust(CElement* pElement, std::optional<std::string_view> key)
maybe noexcept?

2024-11-03 13:54 UTC, ffsPLASMA commented
isnt this kinda redundant with the way you can already detect elementdata changes in lua? thats why I added it to security resource.

https://github.com/multitheftauto/mtasa-resources/blob/master/%5Badmin%5D/security/players.lua#L9

2024-11-03 14:24 UTC, FileEX commented
From what I understand, the issue is that if we have an elementData key, like "user:points", which we only use in server-side scripts and it’s not synchronized on the server, a potential cheater could still overwrite it by using setElementData client-side with the sync parameter set to true. My suggestion is to add a new server-side argument, something like ignoreClientSync. Then, in the server’s elementData synchronization packet, if a particular elementData key has the ignoreClientSync parameter set to true, this synchronization packet would simply be ignored, and the value would remain unchanged.

In my opinion, a single simple argument is a much better solution than having entirely separate functions for this

2024-11-03 14:33 UTC, ffsPLASMA commented
> From what I understand, the issue is that if we have an elementData key, like "user:points", which we only use in server-side scripts and it’s not synchronized on the server, a potential cheater could still overwrite it by using setElementData client-side with the sync parameter set to true. My suggestion is to add a new server-side argument, something like ignoreClientSync. Then, in the server’s elementData synchronization packet, if a particular elementData key has the ignoreClientSync parameter set to true, this synchronization packet would simply be ignored, and the value would remain unchanged.
> 
> In my opinion, a single simple argument is a much better solution than having entirely separate functions for this

Ye I agree something like:

bool setElementData ( element theElement, string key, var value [, bool synchronize = true ], [bool acceptClientUpdate = true] )

If synchronize is set to false, acceptClientUpdate should also be set to false.

2024-11-03 16:07 UTC, PlatinMTA commented
> From what I understand, the issue is that if we have an elementData key, like "user:points", which we only use in server-side scripts and it’s not synchronized on the server, a potential cheater could still overwrite it by using setElementData client-side with the sync parameter set to true. My suggestion is to add a new server-side argument, something like ignoreClientSync. Then, in the server’s elementData synchronization packet, if a particular elementData key has the ignoreClientSync parameter set to true, this synchronization packet would simply be ignored, and the value would remain unchanged.
> 
> In my opinion, a single simple argument is a much better solution than having entirely separate functions for this

What if the elementdata is not set serverside? Should it be ignored by default? I do believe this should be the case but I also think its too late to be making these changes...

2024-11-03 16:47 UTC, FileEX commented
> 
> What if the elementdata is not set serverside? Should it be ignored by default? I do believe this should be the case but I also think its too late to be making these changes...

If an element data doesn’t exist on the server side for a given element, like player:vip, the scripter should simply set this element data to false by default rather than leaving it unset. If any element data isn’t used at all on the server side, it doesn’t matter if a potential cheater sets it. Yes, there’s still the issue that a cheater could send a packet manually, bypassing all checks, but I’ve already suggested a potential solution for this to Dutchman. In any case, an argument like acceptClientUpdate would make manipulating element data with executors impossible, as the server would ignore that packet

2024-11-05 21:04 UTC, wassmas commented
> From what I understand, the issue is that if we have an elementData key, like "user:points", which we only use in server-side scripts and it’s not synchronized on the server, a potential cheater could still overwrite it by using setElementData client-side with the sync parameter set to true. My suggestion is to add a new server-side argument, something like ignoreClientSync. Then, in the server’s elementData synchronization packet, if a particular elementData key has the ignoreClientSync parameter set to true, this synchronization packet would simply be ignored, and the value would remain unchanged.
> 
> In my opinion, a single simple argument is a much better solution than having entirely separate functions for this

Thats why i request for this: #3696

2024-11-05 21:29 UTC, TheNormalnij commented
> it doesn’t matter if a potential cheater sets it

Nope. The data will be synced with all clients. 

> What if the elementdata is not set serverside? Should it be ignored by default?

I'll add a server setting to ignore all unknown element data from clients.

2024-11-06 16:25 UTC, TheNormalnij commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +
```suggestion

```

2024-11-06 16:25 UTC, TheNormalnij commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
>              m_pPlayerManager->ClearElementData(pElement, szName);
```suggestion
            m_pPlayerManager->ClearElementData(pElement, szName);

```

2024-11-07 09:50 UTC, ffsPLASMA commented
Wouldnt it be better to just ourright dismiss all client sync updates to an elementdata if the data wasnt shared to client in first place?

eg. setElementData(root, "coolData", "mreow", false)

^doesnt get synced to client, so why not disregard any client updates for said key in first place?

2024-11-11 12:07 UTC, TheNormalnij commented
> Wouldnt it be better to just outright dismiss all client sync updates to an elementdata if the data wasnt shared to client in first place?
> 
> eg. setElementData(root, "coolData", "mreow", false)
> 
> ^doesnt get synced to client, so why not disregard any client updates for said key in first place?

It is not enough. Element data may be broadcasted by server only. In this case the element data is shared, but the server deny all changes from client. Whitelisting is the safest option.

2024-11-11 12:21 UTC, ffsPLASMA commented
> > Wouldnt it be better to just outright dismiss all client sync updates to an elementdata if the data wasnt shared to client in first place?
> > eg. setElementData(root, "coolData", "mreow", false)
> > ^doesnt get synced to client, so why not disregard any client updates for said key in first place?
> 
> It is not enough. Element data may be broadcasted by server only. In this case the element data is shared, but the server deny all changes from client. Whitelisting is the safest option.

I dont quite understand.

When I create an elementdata on server and specifically set it to not get synced to any clients, then the server should not accept/retrieve any updates from client for said key in first place. If I explicitly set an elementdata to get synced to other clients, I can use onElementDataChange to see if said client is allowed to change it or not.

Adding yet another parameter to setElementData to pay attention to and a server config setting is kinda nonsense.

2024-11-11 12:27 UTC, TheNormalnij commented
I agree that local serverside element data may be protected by default.
But broadcasted element data requests protection too

2024-11-12 21:15 UTC, Dutchman101 commented
Thanks!
Regarding desirability: the PR has been requested by AC team. You don't have to use it if you don't want to.

2024-11-12 21:16 UTC, merged

2024-11-12 22:25 UTC, Fernando-A-Rocha commented
Cool, script security wiki article should be updated