Add new glitch ignorefirestate
multitheftauto/mtasa-blue pull request #3845
Opened 2024-11-07 17:37 UTC by FileEX

This PR adds a new glitch, ``ignorefirestate`` which allows getting into burning vehicles (with fire particle, not the fire indicating low HP and explosion), as well as aiming 'special' weapons like the ``camera``, ``sniper``, ``RPG``, and ``rocket launcher HS`` while the ped is on fire. Thanks to @ds1-e  for the idea.

2024-11-09 11:01 UTC, TheNormalnij commented
It is not a sa glitch. This feature has more sense in `setWorldSpecialPropertyEnabled`

2024-11-09 11:08 UTC, Fernando-A-Rocha requested changes
Good job!

I agree with TheNormalnij, this feature should be added in a world property as you said it's not a proper glitch, but a different behavior like burn flipped cars.

2024-11-19 12:11 UTC, FileEX commented
Moved to special world property

2024-11-19 12:44 UTC, Fernando-A-Rocha approved these changes

2024-11-19 12:45 UTC, bum8hj commented on Client/mods/deathmatch/logic/CClientGame.cpp
A little nitpick on an unrelated change:
I would rather write "Kickout ..." as 2 words, like "Kick out ..."

2024-11-21 22:34 UTC, merged