Add CMatrix 4x4 lua table in ArgumentParser
multitheftauto/mtasa-blue pull request #3849
Opened 2024-11-09 13:29 UTC by W3lac3

This PR adds for ArgumentParser to accept a 4x4 lua table as a CMatrix.

2024-11-09 14:39 UTC, TracerDS requested changes

2024-11-09 14:39 UTC, TracerDS commented on Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
> +    uint uiRow = 0;
`std::uint32_t` instead of `uint`

2024-11-09 14:39 UTC, TracerDS commented on Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
> +        for (lua_pushnil(luaVM); lua_next(luaVM, uiArgIndex) != 0; lua_pop(luaVM, 1), uiRow++)
what is that weird for loop? you can initialize `uiRow` (btw dont use hungarian notation) in the loop directly if needed

2024-11-09 14:39 UTC, TracerDS commented on Client/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
> +bool IsValidMatrixLuaTable(lua_State* luaVM, uint uiArgIndex);
`noexcept`

2024-11-09 14:39 UTC, TracerDS commented on Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.cpp
> +
above

2024-11-09 14:39 UTC, TracerDS commented on Server/mods/deathmatch/logic/lua/CLuaFunctionParseHelpers.h
> +bool    IsValidMatrixLuaTable(lua_State* luaVM, uint uiArgIndex);
`noexcept`

2024-11-11 17:38 UTC, tracerjebanaciota commented
weź tracer nie wkurwiaj ludzi i zamknij ten pysk dzięki

2024-11-11 17:54 UTC, TracerDS commented
> weź tracer nie wkurwiaj ludzi i zamknij ten pysk dzięki

![image](https://github.com/user-attachments/assets/1bf300cf-516b-44b6-aea4-c29a0576d9b4)
heh

2024-11-28 20:23 UTC, TracerDS approved these changes

2024-12-18 08:39 UTC, tederis commented
CMatrix is a 3x4 matrix. The conversion from 4x4 implies a data loss. What is the practical meaning of that?

2024-12-18 11:13 UTC, W3lac3 commented
> CMatrix is a 3x4 matrix. The conversion from 4x4 implies a data loss. What is the practical meaning of that?

Currently there are functions that don't accept lua tables, but it's worth noting that all functions that use Matrix require a 4x4 matrix, not a 3x4 matrix. This change I've made will allow all future and current functions that don't have the conversion to accept tables from lua, without using the Matrix class to convert, because it's heavy.

2024-12-23 15:29 UTC, tederis approved these changes

2024-12-23 15:30 UTC, merged