Improved warnings for lua-package
multitheftauto/mtasa-blue pull request #683
Opened 2018-11-02 17:15 UTC by CrosRoad95

Make warnings user friendly

### Before
![image](https://user-images.githubusercontent.com/22455534/47930032-0ba6ac80-decb-11e8-9c71-a25df2a2176b.png)

### After
![image](https://user-images.githubusercontent.com/22455534/47930042-13665100-decb-11e8-81be-d9a5379ef0ab.png)
![image](https://user-images.githubusercontent.com/22455534/47930051-19f4c880-decb-11e8-84b1-6d792662c100.png)
![image](https://user-images.githubusercontent.com/22455534/47930057-1eb97c80-decb-11e8-937c-46eee73c5575.png)
![image](https://user-images.githubusercontent.com/22455534/47930064-24af5d80-decb-11e8-94c0-83b2c3c7bdf7.png)

2018-11-03 00:36 UTC, qaisjp requested changes
This misnumbers errors for empty files or files that return nil. See example resource [nil_require.zip](https://github.com/multitheftauto/mtasa-blue/files/2544510/nil_require.zip).

2018-11-03 00:39 UTC, qaisjp requested changes

2018-11-03 00:39 UTC, qaisjp commented on Shared/mods/deathmatch/logic/lua/CLuaMain.Shared.cpp
> +            strError += "#3: " + ConformPath(strFilePath, "resources/") + "\n\t";
"Module didn't return a value" information is lost

2019-01-12 23:26 UTC, qaisjp commented on Shared/mods/deathmatch/logic/lua/CLuaMain.Shared.cpp
> +#ifdef MTA_CLIENT
ifdef changes here need to be reverted.  it's annoying that clang-format does this

2019-02-20 18:21 UTC, patrikjuvonen approved these changes
I believe this PR is ready to be merged with `feature/lua-packages`.

2019-02-20 18:33 UTC, merged