Add setPedFightingStyle for clientside peds
multitheftauto/mtasa-blue pull request #810
Opened 2019-02-11 11:57 UTC by StrixG

2019-02-17 17:12 UTC, qaisjp commented
Please revert edc9180

It should return false on failure. Only getters return nil on failure.

2019-02-17 17:13 UTC, qaisjp submitted a review, later dismissed
Please revert edc9180

It should return false on failure. Only getters return nil on failure.

2019-02-17 17:46 UTC, botder commented
Wait for the result of #821 before reverting, if required.

2019-08-17 16:32 UTC, patrikjuvonen requested changes

2019-08-17 16:32 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
> +        m_pScriptDebugging->LogCustom(luaVM, argStream.GetFullErrorMessage());
The contents of this if-block should be changed to:
```cpp
return luaL_error(luaVM, argStream.GetFullErrorMessage());
```

2019-08-19 09:30 UTC, patrikjuvonen approved these changes
Thank you! All ready to go once 1.5.7 is released.

2019-09-02 14:19 UTC, merged