Add setPedArmor function for clientside peds
multitheftauto/mtasa-blue pull request #811
Opened 2019-02-11 13:00 UTC by StrixG

2019-02-13 10:02 UTC, StrixG commented
I will make one pull request with all missing clientside ped functions.

2019-02-13 10:10 UTC, qaisjp commented
separate pull requests are preferred

2019-02-17 17:13 UTC, qaisjp submitted a review, later dismissed
Should return false on failure. Only getters return nil on failure.

2019-02-22 19:14 UTC, patrikjuvonen commented
Waiting for #821 to resolve so we can make changes accordingly.

2019-08-17 00:32 UTC, botder commented
The decision in pull request #821 (**Pin down return value on failure**) is now settled.

2019-08-17 15:28 UTC, patrikjuvonen requested changes

2019-08-17 15:28 UTC, patrikjuvonen commented on Client/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp
> +        m_pScriptDebugging->LogCustom(luaVM, argStream.GetFullErrorMessage());
The contents of this if-block should be changed to:
```cpp
return luaL_error(luaVM, argStream.GetFullErrorMessage());
```

2019-08-17 18:06 UTC, patrikjuvonen approved these changes
Thank you! This PR is ready to be merged after 1.5.7 is released.

2019-09-02 14:54 UTC, merged