Add setPlayerDebugViewActive and setPlayerDebugViewMode
multitheftauto/mtasa-blue pull request #826
Opened 2019-02-18 23:18 UTC by knitz12

While i was making a new account system (MySQL) i found out i couldn't use /debugscript without creating an account in MTA's database AND adding it to the ACL, that was a problem because when i logged in my system i also had to login in MTA's system using /login to be able to view script errors, that's why i created this pull request, with this i could add a /debug command which would simulate /debugscript.

This PR adds two new functions, **setPlayerDebugViewActive** (OOP setDebugViewActive) and **setPlayerDebugViewMode** (OOP setDebugViewMode), I'm fairly new to the MTA's codebase so i don't know if i made any mistake, i also didn't bother adding getter functions as i don't think they would be useful (atleast for my usecase) but i could if you think its needed.

2019-02-19 02:34 UTC, Citizen01 commented
Thanks for your PR.

I have a question: Why not `setPlayerDebuggerVisible` and `setPlayerDebuggerLevel` ? (this needs other feedbacks than mine before renaming anything).

Also we dropped the hungarian notation for new devs (even though I prefer when the code is consistant).

Would be great if we could give `root` as element so it does for everyone. I don't have any valid use case though but I see `SetPlayerDebuggerVisible` was ready for it:
https://github.com/multitheftauto/mtasa-blue/blob/9c8ca2e56fcd4d8f7238931b2482c62e2fcaa479/Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L3051-L3058

2019-02-19 02:36 UTC, Citizen01 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +bool CStaticFunctionDefinitions::SetPlayerDebuggerMode(CPlayer* pElement, int iMode)
maybe `unsigned int` just like in `SetScriptDebugLevel` ?

2019-02-19 15:48 UTC, knitz12 commented
@Citizen01 I modified the functions to work with the root element, i didn't changed the hungarian notation as i don't know what to replace them with.

About the naming: I used **setPlayerDebugView*** instead of **setPlayerDebugger*** because of the existing (clientside) function named **setDebugViewActive** but i'm open to change it if others think its better 😃.

Thanks for the review.

2019-02-19 16:58 UTC, qaisjp commented
You can also enable debugscript for "Everyone" in the ACL to get around this

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +
Remove dis

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +
and dis

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +
and dis

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +    CElement* pElement;            // player or console
and some spaces here too

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +    CElement* pElement;            // player or console
and to

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +    CElement* pElement;            // player or console
and this bro

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +    unsigned int iMode;
This should be `uiMode` instead of `iMode`

2019-02-19 17:06 UTC, CrosRoad95 commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.h
> +};
and fix it, that's all

2019-02-19 18:59 UTC, knitz12 commented
@qaisjp Then everyone would have access to /debugscript, which is something i don't want, Or am i missing something?

@CrosRoad95 I fixed some things you mentioned, i also tried to fix the others whitespace changes but git didn't picked them (i don't know why) but i don't think they are relevant as they don't change anything visually.

2019-02-19 22:23 UTC, qaisjp commented
Oh, now I understand your problem.

How about `setPlayerScriptDebugLevel(player, boolean/int)`. Pass `false` to hide, and pass an integer for the level.

There should be a getter.

2019-02-20 15:37 UTC, knitz12 commented
@qaisjp Wouldn't it be better to pass **0** to setPlayerScriptDebugLevel to hide the debugger? In a similar way the getter (getPlayerScriptDebugLevel?) would return **0** if the player had the debugger closed

2019-02-21 01:44 UTC, qaisjp commented
I thought about that but don't want to conflict with `0: custom message` in https://wiki.multitheftauto.com/wiki/OutputDebugString

2019-02-21 19:13 UTC, knitz12 commented
@qaisjp Ok, i added set/getPlayerScriptDebugLevel, passing false to setPlayerScriptDebugLevel hides the debugger and passing an integer shows it.

2019-02-22 14:03 UTC, patrikjuvonen requested changes
I believe it is better to match these function names as well.

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +bool CStaticFunctionDefinitions::GetPlayerDebuggerLevel(CPlayer* pPlayer, unsigned int& uiLevel)
```suggestion
bool CStaticFunctionDefinitions::GetPlayerScriptDebugLevel(CPlayer* pPlayer, unsigned int& uiLevel)
```

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +bool CStaticFunctionDefinitions::SetPlayerDebuggerLevel(CElement* pElement, unsigned int uiLevel)
```suggestion
bool CStaticFunctionDefinitions::SetPlayerScriptDebugLevel(CElement* pElement, unsigned int uiLevel)
```

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp
> +        RUN_CHILDREN(SetPlayerDebuggerLevel(*iter, uiLevel));
```suggestion
        RUN_CHILDREN(SetPlayerScriptDebugLevel(*iter, uiLevel));
```

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
> +    static bool               GetPlayerDebuggerLevel(CPlayer* pPlayer, unsigned int& uiLevel);
```suggestion
    static bool               GetPlayerScriptDebugLevel(CPlayer* pPlayer, unsigned int& uiLevel);
```

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/CStaticFunctionDefinitions.h
> +    static bool SetPlayerDebuggerLevel(CElement* pElement, unsigned int uiLevel);
```suggestion
    static bool SetPlayerScriptDebugLevel(CElement* pElement, unsigned int uiLevel);
```

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +        if (CStaticFunctionDefinitions::SetPlayerDebuggerLevel(pElement, bHideDebugger ? 0 : uiMode))
```suggestion
        if (CStaticFunctionDefinitions::SetPlayerScriptDebugLevel(pElement, bHideDebugger ? 0 : uiMode))
```

2019-02-22 14:03 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +        if (CStaticFunctionDefinitions::GetPlayerDebuggerLevel(pPlayer, uiLevel))
```suggestion
        if (CStaticFunctionDefinitions::GetPlayerScriptDebugLevel(pPlayer, uiLevel))
```

2019-02-22 23:18 UTC, knitz12 commented
@patrikjuvonen Done :)

2019-02-23 11:56 UTC, patrikjuvonen approved these changes

2019-02-23 12:00 UTC, patrikjuvonen commented
Thanks for the changes. This PR is ready to be merged but I'd wait for #821 so we can make returns right for this from the start.

2019-08-17 00:32 UTC, botder commented
The decision in pull request #821 (**Pin down return value on failure**) is now settled.

2019-08-17 15:47 UTC, patrikjuvonen requested changes

2019-08-17 15:47 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +    if (!argStream.HasErrors())
As per #821 we should do a hard error here like so:
```cpp
if (argStream.HasErrors())
{
    return luaL_error(luaVM, argStream.GetFullErrorMessage());
}
```
and then move the passing code after that.

2019-08-17 15:47 UTC, patrikjuvonen commented on Server/mods/deathmatch/logic/luadefs/CLuaPlayerDefs.cpp
> +    if (!argStream.HasErrors())
As per #821 we should do a hard error here like so:
```cpp
if (argStream.HasErrors())
{
    return luaL_error(luaVM, argStream.GetFullErrorMessage());
}
```
and then move the passing code after that.

2019-08-21 17:06 UTC, knitz12 commented
Done @patrikjuvonen :)

2019-08-21 17:23 UTC, patrikjuvonen approved these changes
Thank you!
Good job. This PR is ready to be merged afrer 1.5.7 is released.

2019-09-02 14:18 UTC, merged

2019-09-13 21:31 UTC, ccw808 commented
Sorry about late review, but does `function.setPlayerScriptDebugLevel` really need to be restricted to Admin ACL by default?

2019-09-16 05:00 UTC, knitz12 commented
@ccw808 Well, my thought for doing this was that a malicious resource could make a backdoor command which would allow the attacker to read all the debug messages, gaining knowledge on the internals of the server or observing how a specific system reacts to certain inputs etc depending on how the server uses the logging functions.

With that scenario in mind i put it in the admin ACL, also to conform with /debugscript.

2020-06-03 22:07 UTC, qaisjp commented
No, you're right, 0 is better for closing